from pathlib import Path

p=Path('sticker-market-demo/index.html')
s=p.read_text()
s=s.replace('Public Demo v1.0.2','Public Demo v1.1.0').replace('Public Demo v1.0.1','Public Demo v1.1.0')

CSS=r'''
/* v1.1 enhanced marketplace UX */
.market-guide{margin:42px 0;border-top:1px solid var(--line)}
.market-guide details{border-bottom:1px solid var(--line);background:color-mix(in srgb,var(--card) 92%,transparent)}
.market-guide summary{list-style:none;padding:20px 6px;font-size:18px;font-weight:900;cursor:pointer}.market-guide summary::-webkit-details-marker{display:none}.market-guide summary:after{content:'⌄';float:right;color:var(--accent);font-size:22px}.market-guide details[open] summary:after{content:'⌃'}
.market-guide-body{padding:0 6px 20px;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.guide-link{border:1px solid var(--line);background:var(--soft);border-radius:14px;padding:13px;text-align:left}
.disclaimer{border:1px solid var(--line);border-radius:14px;background:var(--soft);margin:24px 0;overflow:hidden}.disclaimer summary{padding:15px 16px;font-weight:900;cursor:pointer}.disclaimer p{margin:0;padding:0 16px 16px;color:var(--muted);font-size:13px}
.related-search{margin:28px 0}.related-chips{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.related-chip{border:0;background:var(--soft);border-radius:999px;padding:13px 16px;font-weight:800;text-align:left}
.price-slider-box{padding:10px 4px 4px}.price-range-labels{display:flex;justify-content:space-between;font-weight:800;margin-bottom:8px}.price-slider{position:relative;height:44px}.price-slider .price-track{position:absolute;left:8px;right:8px;top:19px;height:8px;border-radius:999px;background:var(--line)}.price-slider .price-fill{position:absolute;top:0;height:100%;border-radius:999px;background:var(--accent)}
.price-slider input[type=range]{position:absolute;left:0;top:7px;width:100%;height:28px;margin:0;background:transparent;pointer-events:none;-webkit-appearance:none;appearance:none}.price-slider input[type=range]::-webkit-slider-runnable-track{height:8px;background:transparent}.price-slider input[type=range]::-webkit-slider-thumb{-webkit-appearance:none;appearance:none;width:28px;height:28px;border-radius:50%;background:var(--card);border:1px solid var(--line);box-shadow:0 3px 8px #0002;pointer-events:auto;margin-top:-10px}.price-slider input[type=range]::-moz-range-thumb{width:28px;height:28px;border-radius:50%;background:var(--card);border:1px solid var(--line);pointer-events:auto}
.product-accordion{border-top:1px solid var(--line);border-bottom:1px solid var(--line);margin-top:18px}.product-accordion details{border-bottom:1px solid var(--line)}.product-accordion details:last-child{border-bottom:0}.product-accordion summary{padding:16px 2px;font-size:17px;font-weight:900;cursor:pointer}.product-accordion .detail-body{padding:0 2px 16px;color:var(--muted)}
.seller-badge{padding:13px 15px;border-radius:14px;background:color-mix(in srgb,var(--accent) 14%,var(--card));font-weight:900;margin-top:14px}.seller-card{display:flex;justify-content:space-between;gap:14px;align-items:center;border-top:1px solid var(--line);border-bottom:1px solid var(--line);padding:20px 0;margin:22px 0}.seller-avatar{width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:var(--soft);font-size:28px}
.tag-section{margin:24px 0}.tag-strip{display:flex;gap:8px;overflow-x:auto;scrollbar-width:none;padding-bottom:6px}.tag-strip::-webkit-scrollbar{display:none}.tag-chip{flex:0 0 auto;border:1px solid var(--line);background:var(--soft);border-radius:12px;padding:10px 14px;font-weight:800}
.review-section{margin:34px 0}.review-summary{display:grid;grid-template-columns:auto 1fr;gap:16px;align-items:center;padding:18px;border:1px solid var(--line);border-radius:18px;background:var(--card)}.review-score{font-size:52px;line-height:1;font-weight:500}.ai-review{margin-top:12px;padding:14px;border-radius:14px;background:color-mix(in srgb,var(--accent) 10%,var(--soft));border:1px solid color-mix(in srgb,var(--accent) 24%,var(--line))}.review-card{padding:20px 2px;border-bottom:1px solid var(--line)}.review-card .stars{color:#e9aa34;font-size:18px;font-weight:900}.review-meta{display:flex;gap:8px;align-items:center;color:var(--muted);font-size:13px;flex-wrap:wrap}.review-translate{border:0;background:none;padding:8px 0;color:var(--text);font-weight:800}.product-v11-extra{max-width:920px;margin:0 auto}
@media(max-width:700px){.market-guide-body{grid-template-columns:1fr}.related-chips{grid-template-columns:1fr 1fr}.review-summary{grid-template-columns:1fr}.seller-card{align-items:flex-start}}@media(max-width:460px){.related-chips{grid-template-columns:1fr}}
'''

JS=r'''
/* v1.1 enhanced marketplace UX */
function v11Guide(){return `<section class="market-guide"><details><summary>Sticker Marketで「売りたい」</summary><div class="market-guide-body"><button class="guide-link" onclick="state.user?go('sell'):go('signup')"><b>デザインを販売</b><br><span class="muted">デジタルデータを登録して販売</span></button><button class="guide-link" onclick="state.user?go('sell'):go('signup')"><b>シールとして販売</b><br><span class="muted">印刷商品として届ける</span></button><button class="guide-link" onclick="state.user&&state.user.role==='creator'?go('creator'):go('signup')"><b>販売を伸ばす</b><br><span class="muted">分析・AI支援・タグ改善</span></button></div></details><details><summary>Sticker Marketで「買いたい」</summary><div class="market-guide-body"><button class="guide-link" onclick="go('search')"><b>作品を探す</b><br><span class="muted">カテゴリ・タグ・価格から検索</span></button><button class="guide-link" onclick="go('search')"><b>データを買う</b><br><span class="muted">購入後にデザインデータを取得</span></button><button class="guide-link" onclick="state.user?go('create'):go('signup')"><b>自分で作る</b><br><span class="muted">画像からオリジナルシールを作成</span></button></div></details><details><summary>サポート・お問い合わせ</summary><div class="market-guide-body"><div class="guide-link"><b>ご利用ガイド</b><br><span class="muted">購入・販売・ライセンスの基本</span></div><div class="guide-link"><b>よくある質問</b><br><span class="muted">注文・配送・ダウンロードについて</span></div><div class="guide-link"><b>お問い合わせ</b><br><span class="muted">運営への連絡窓口</span></div></div></details></section>`}
function v11Tags(p){return [...new Set([p.category,p.material,p.shape,p.creator.includes('Haru')?'風景':'デザイン',p.digital?'デジタル':'',p.physical?'ステッカー':'','ギフト'].filter(Boolean))]}
function v11Terms(p){const b=p?[`${p.category} ステッカー`,`${p.material} ステッカー`,`${p.shape} ステッカー`,`${p.creator} 作品`]:['かわいいステッカー','アートステッカー','ギフトステッカー','防水ステッカー'];return [...new Set([...b,'日本のステッカー','コレクション用ステッカー','ノート用ステッカー'])].slice(0,8)}
function v11Quick(term){searchState.q=term;searchState.page=1;go('search')}
function v11Related(p){return `<section class="related-search"><h2>関連する検索をもっと見る</h2><div class="related-chips">${v11Terms(p).map(t=>`<button class="related-chip" onclick="v11Quick('${esc(t)}')">${esc(t)}</button>`).join('')}</div></section>`}
function v11Disclaimer(){return `<details class="disclaimer"><summary>免責事項</summary><p>商品説明、画像、ライセンス条件などの出品情報はクリエイターが登録した内容を含みます。購入前に商品仕様・利用条件・配送条件をご確認ください。権利侵害や不適切な商品を見つけた場合は運営へ報告できます。</p></details>`}
function v11Reviews(p){const n=13+(parseInt(p.id.slice(1))%18),score=Math.max(4,Math.min(5,p.rating)).toFixed(1),rs=[['画像どおりの雰囲気で、印刷もきれいでした。','Mika','2026/08/03',5],['デザインが使いやすく、データも整理されていました。','Camille','2026/08/01',5],['仕上がりは満足です。別サイズも試してみたいです。','Bee','2026/07/21',4]];return `<section class="review-section"><h2>この商品のレビュー</h2><div class="review-summary"><div class="review-score">${score}<span style="font-size:28px;color:#e9aa34">★</span></div><div><b>商品平均評価</b><div class="muted">${n}件のレビュー</div><div class="ai-review"><b>AIによるレビュー要約（デモ）</b><br>✓ デザインの見た目が好評　✓ 印刷・データ品質への評価が高い　✓ リピート意向の声があります</div></div></div>${rs.map(r=>`<article class="review-card"><div class="stars">${'★'.repeat(r[3])}${'☆'.repeat(5-r[3])}</div><p>${esc(r[0])}</p><div class="review-meta"><b>${r[1]}</b><span>${r[2]}</span></div><button class="review-translate" onclick="toast('日本語表示に切り替えました（デモ）')">日本語に翻訳する</button></article>`).join('')}</section>`}
function v11PriceSlider(){const lo=$('#smin'),hi=$('#smax');if(!lo||!hi||lo.type==='range')return;const min=searchState.min===''?0:+searchState.min,max=searchState.max===''?5000:+searchState.max,wrap=lo.closest('.field');if(!wrap)return;wrap.innerHTML=`<label>価格</label><div class="price-slider-box"><div class="price-range-labels"><span id="priceLow">${yen(min)}</span><span id="priceHigh">${max>=5000?'¥5,000+':yen(max)}</span></div><div class="price-slider"><div class="price-track"><div class="price-fill" id="priceFill"></div></div><input id="smin" type="range" min="0" max="5000" step="100" value="${min}"><input id="smax" type="range" min="0" max="5000" step="100" value="${max}"></div></div>`;const a=$('#smin'),b=$('#smax'),fill=$('#priceFill'),l=$('#priceLow'),h=$('#priceHigh');const sync=from=>{let x=+a.value,y=+b.value;if(y-x<100){if(from==='a')x=y-100;else y=x+100}x=Math.max(0,x);y=Math.min(5000,y);a.value=x;b.value=y;l.textContent=yen(x);h.textContent=y>=5000?'¥5,000+':yen(y);fill.style.left=(x/50)+'%';fill.style.right=(100-y/50)+'%';searchState.min=x||'';searchState.max=y>=5000?'':y};a.oninput=()=>sync('a');b.oninput=()=>sync('b');sync()}
function v11EnhanceSearch(){v11PriceSlider();const main=document.querySelector('.app-main');if(main&&!main.querySelector('.related-search'))main.insertAdjacentHTML('beforeend',v11Related(null))}
function v11EnhanceProduct(id){const p=products.find(x=>x.id===id);if(!p)return;const root=document.querySelector('.app-main,.public-product-wrap');if(!root||root.querySelector('.product-v11-extra'))return;const right=root.querySelector('.product section');if(right&&!right.querySelector('.product-accordion'))right.insertAdjacentHTML('beforeend',`<div class="product-accordion"><details><summary>商品詳細</summary><div class="detail-body">カテゴリ：${esc(p.category)}<br>おすすめ素材：${esc(p.material)}<br>おすすめ形状：${esc(p.shape)}<br>デジタル価格：${yen(p.digital)}<br>シール価格：${yen(p.physical)}〜</div></details><details><summary>発送 & 返品ポリシー</summary><div class="detail-body">物理商品の発送目安は仕様・数量により異なります。製造開始前の変更可否、返品・返金条件は注文確認画面でご案内します。</div></details></div><div class="seller-badge">✦ ${esc(p.creator)} は注目クリエイターです</div>`);root.insertAdjacentHTML('beforeend',`<div class="product-v11-extra"><section class="tag-section"><h2>タグ</h2><div class="tag-strip">${v11Tags(p).map(t=>`<button class="tag-chip" onclick="v11Quick('${esc(t)}')">${esc(t)}</button>`).join('')}</div></section><section class="seller-card"><div style="display:flex;gap:12px;align-items:center"><div class="seller-avatar">${p.emoji}</div><div><h3 style="margin:0">${esc(p.creator)}</h3><div class="muted">${esc(p.category)}を中心に制作</div></div></div><button class="btn" id="v11Follow">フォロー</button></section>${v11Reviews(p)}${v11Related(p)}${v11Disclaimer()}</div>`);const f=$('#v11Follow');if(f)f.onclick=()=>{if(!state.user){sessionStorage.setItem('afterLogin',`product/${p.id}`);go('login');return}toast(`${p.creator}をフォローしました（デモ）`)}}
const v11OldLP=lp;lp=function(){v11OldLP();const main=document.querySelector('.lp-main');if(main&&!main.querySelector('.market-guide'))main.insertAdjacentHTML('beforeend',v11Guide())}
const v11OldHome=home;home=function(){v11OldHome();const main=document.querySelector('.app-main');if(main&&!main.querySelector('.market-guide'))main.insertAdjacentHTML('beforeend',v11Guide())}
const v11OldSearch=search;search=function(){v11OldSearch();v11EnhanceSearch()}
const v11OldProduct=product;product=function(id){v11OldProduct(id);v11EnhanceProduct(id)}
window.onhashchange=route;route();
'''

if '/* v1.1 enhanced marketplace UX */' not in s:
    s=s.replace('</style>',CSS+'\n</style>')
    s=s.replace('</script>',JS+'\n</script>')
p.write_text(s)
