// Existing-feature regression after formal MVP differential fixes.
import {test,expect} from '@playwright/test';

async function route(page,path){await page.evaluate(p=>{location.hash='#/'+p},path);await page.waitForTimeout(100);await expect(page.locator('#main')).toBeVisible();await expect(page.locator('body')).not.toContainText('画面を表示できませんでした')}
async function login(page,email='demo@example.test'){await page.goto('/#/login');await page.locator('#loginEmail').fill(email);await page.locator('#loginPass').fill('demo');await page.locator('#main').getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForTimeout(650)}
async function noOverflow(page,label=''){const x=await page.evaluate(()=>({w:document.documentElement.clientWidth,s:document.documentElement.scrollWidth,body:document.body.scrollWidth,hash:location.hash}));expect(Math.max(x.s,x.body),`horizontal overflow ${label||x.hash}: ${JSON.stringify(x)}`).toBeLessThanOrEqual(x.w+2)}
function captureErrors(page){const errors=[];page.on('pageerror',e=>errors.push(e.stack||e.message));return errors}
async function assertNoPageErrors(errors,label){expect(errors,`runtime errors after ${label}`).toEqual([])}

test('existing buyer/public screens remain reachable',async({page})=>{const errors=captureErrors(page);await page.goto('/#/landing');await expect(page.getByText('Sticker Market',{exact:false}).first()).toBeVisible();await expect(page.locator('.legal-footer')).toBeVisible();await route(page,'search');await route(page,'product/p1');await login(page);await assertNoPageErrors(errors,'login');for(const p of ['home','search','product/p1','favorites','orders','reviews','mypage','create-sticker']){await route(page,p);await noOverflow(page,p);await assertNoPageErrors(errors,p)}await page.evaluate(()=>{addCart('p1','physical',{qty:10,material:'耐水PET',size:'50mm',shape:'ダイカット'})});await route(page,'cart');await route(page,'checkout/shipping');await expect(page.getByText('配送先を選択')).toBeVisible();await assertNoPageErrors(errors,'checkout/shipping')});

test('existing creator management remains reachable',async({page})=>{const errors=captureErrors(page);await login(page,'creator@example.test');for(const p of ['creator-dashboard','works','creator-orders','sales','shop-manage','ai-studio']){await route(page,p);await noOverflow(page,p);await assertNoPageErrors(errors,p)}await route(page,'works');await expect(page.getByText(/作品|商品/).first()).toBeVisible()});

test('creator order navigation and mypage logout divider work in public demo',async({page})=>{await login(page,'creator@example.test');await route(page,'creator-dashboard');await page.locator('.mobile-nav').getByRole('button',{name:/注文管理/}).click();await expect(page).toHaveURL(/#\/creator-orders$/);await expect(page.locator('#main h1').filter({hasText:'注文管理'})).toBeVisible();await route(page,'mypage');const logout=page.getByRole('button',{name:/ログアウト/});await expect(logout).toBeVisible();const border=await logout.evaluate(el=>getComputedStyle(el).borderTopWidth);expect(Number.parseFloat(border)).toBeGreaterThan(0)});

test('existing admin moderation and management remain reachable',async({page})=>{const errors=captureErrors(page);await login(page,'admin@example.test');for(const p of ['admin','admin-review','admin-orders','admin-users','admin-menu','admin-moderation','admin-audit','admin-manufacturing','admin-manufacturers']){await route(page,p);await noOverflow(page,p);await assertNoPageErrors(errors,p)}await expect(page.getByText(/商品審査|審査/).first()).toBeVisible()});

test('mobile navigation remains operable at 390px class viewport',async({page})=>{await login(page);await route(page,'home');const nav=page.locator('.mobile-nav');await expect(nav).toBeVisible();for(const b of await nav.locator('button').all()){await expect(b).toBeEnabled()}await noOverflow(page,'home')});
