import {test,expect} from '@playwright/test';
import {deflateSync} from 'node:zlib';

const E=process.env;
const stripeReady=E.SM_STRIPE_READY==='true';
const required=[
  'SM_STAGING_BUYER_EMAIL','SM_STAGING_BUYER_PASSWORD',
  'SM_STAGING_APPLICANT_EMAIL','SM_STAGING_APPLICANT_PASSWORD',
  'SM_STAGING_CREATOR_EMAIL','SM_STAGING_CREATOR_PASSWORD',
  'SM_STAGING_ADMIN_EMAIL','SM_STAGING_ADMIN_PASSWORD',
  'SM_STAGING_MANUFACTURER_EMAIL','SM_STAGING_MANUFACTURER_PASSWORD',
  'SM_STAGING_PRODUCT_ID','SM_STAGING_MANUFACTURER_ID',
  'SM_STAGING_FULFILLMENT_ORDER_ID','SM_STAGING_FULFILLMENT_MFG_ID',
  'SM_STAGING_ISSUE_ORDER_ID','SM_STAGING_ISSUE_MFG_ID',
  'SM_STAGING_REFUND_ORDER_ID','SM_STAGING_REFUND_MFG_ID'
];
const state={
  listingProductId:null,
  listingName:null,
  fulfillmentOrderId:E.SM_STAGING_FULFILLMENT_ORDER_ID||null,
  fulfillmentMfgId:E.SM_STAGING_FULFILLMENT_MFG_ID||null,
  issueOrderId:E.SM_STAGING_ISSUE_ORDER_ID||null,
  issueMfgId:E.SM_STAGING_ISSUE_MFG_ID||null,
  reproductionMfgId:null
};

function crc32(buf){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function chunk(type,data=Buffer.alloc(0)){const t=Buffer.from(type),len=Buffer.alloc(4),crc=Buffer.alloc(4);len.writeUInt32BE(data.length);crc.writeUInt32BE(crc32(Buffer.concat([t,data])));return Buffer.concat([len,t,data,crc])}
function png600(){const w=600,h=600,ih=Buffer.alloc(13);ih.writeUInt32BE(w,0);ih.writeUInt32BE(h,4);ih[8]=8;ih[9]=6;const raw=Buffer.alloc((w*4+1)*h);for(let y=0;y<h;y++){const o=y*(w*4+1);raw[o]=0;for(let x=0;x<w;x++){const p=o+1+x*4;raw[p]=102;raw[p+1]=72;raw[p+2]=210;raw[p+3]=x<20||y<20||x>w-21||y>h-21?0:255}}return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',ih),chunk('IDAT',deflateSync(raw)),chunk('IEND')])}
const image=()=>({name:`staging-${Date.now()}.png`,mimeType:'image/png',buffer:png600()});

async function login(page,email,password){await page.goto('/?sm_mode=STAGING#/login');await expect(page.getByRole('heading',{name:'ログイン'})).toBeVisible();const body=await page.locator('body').innerText();if(/Publishable Key|公開キー.*更新が必要/.test(body))throw new Error('STAGING backend readiness is blocked by Supabase publishable-key configuration');await page.locator('#loginEmail').fill(email);await page.locator('#loginPass').fill(password);await page.locator('#main').getByRole('button',{name:'ログイン',exact:true}).click();await page.waitForFunction(()=>location.hash!=='#/login',{timeout:20000});await page.waitForTimeout(300);return page.evaluate(()=>({id:currentUser()?.id,role:currentUser()?.role,capabilities:currentUser()?.capabilities||[]}))}
async function newLoggedPage(browser,email,password){const ctx=await browser.newContext();const page=await ctx.newPage();await login(page,email,password);return{ctx,page}}
async function gotoHash(page,path){await page.evaluate(p=>go(p),path);await page.waitForTimeout(180);await expect(page.locator('#main')).toBeVisible()}
async function rest(page,path){return page.evaluate(async p=>await smMvpRest(p),path)}
async function rpc(page,name,args){return page.evaluate(async({name,args})=>await smMvpRpc(name,args),{name,args})}
async function latestOrder(page){const rows=await rest(page,'sm_orders?select=id,status,created_at&order=created_at.desc&limit=1');if(!rows?.[0])throw new Error('latest order not found');return rows[0]}
async function mfgForOrder(page,orderId){const rows=await rest(page,`sm_manufacturing_orders?select=id,status,order_id,reproduction_of&order_id=eq.${encodeURIComponent(orderId)}&order=created_at.asc`);const x=rows?.find(v=>!v.reproduction_of);if(!x)throw new Error(`manufacturing order missing for ${orderId}`);return x}
async function waitStatus(page,table,id,status,timeout=30000){await expect.poll(async()=>{const rows=await rest(page,`${table}?select=status&id=eq.${encodeURIComponent(id)}`);return rows?.[0]?.status},{timeout}).toBe(status)}
async function fillStripeCard(page){let cardFrame=null;await expect.poll(async()=>{for(const frame of page.frames()){if(await frame.locator('input[name="cardnumber"]').count()){cardFrame=frame;return true}}return false},{timeout:20000}).toBe(true);await cardFrame.locator('input[name="cardnumber"]').fill('4242424242424242');await cardFrame.locator('input[name="exp-date"]').fill('1234');await cardFrame.locator('input[name="cvc"]').fill('123')}
async function buyPhysical(page,productId){await gotoHash(page,`product/${productId}`);await page.getByRole('button',{name:'シールを買う',exact:true}).click();await expect(page.getByRole('heading',{name:'シールをカスタマイズ'})).toBeVisible();await page.locator('#customQty').selectOption('10');await page.getByRole('button',{name:'カートに追加',exact:true}).click();await expect(page.getByRole('heading',{name:'カート'})).toBeVisible({timeout:5000});await page.getByRole('button',{name:'購入手続きへ'}).click();await page.getByRole('button',{name:'次へ'}).click();await expect(page.locator('#sm-card-element')).toBeVisible();await fillStripeCard(page);await page.locator('#smPaymentNext').click();await expect(page.getByRole('heading',{name:'注文内容の確認'})).toBeVisible({timeout:20000});await page.locator('#smPayButton').click();await expect(page.getByRole('heading',{name:'ご注文が完了しました！'})).toBeVisible({timeout:45000});return latestOrder(page)}

// Dedicated STAGING fixtures are mandatory. No test is silently skipped.
test.beforeAll(()=>{const missing=required.filter(k=>!E[k]);if(missing.length)throw new Error(`Missing STAGING E2E configuration: ${missing.join(', ')}`)});
test.describe.configure({mode:'serial'});

test('E2E-01 購入：検索/商品/カート/配送先/Stripe Test/注文履歴',async({page})=>{await login(page,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);await gotoHash(page,`search?q=${encodeURIComponent(E.SM_STAGING_PRODUCT_ID)}`);await gotoHash(page,`product/${E.SM_STAGING_PRODUCT_ID}`);const o=await buyPhysical(page,E.SM_STAGING_PRODUCT_ID);expect(o.status).toBe('confirmed');await gotoHash(page,'orders');await expect(page.getByText(o.id,{exact:false})).toBeVisible()});

test('E2E-02 出品：購入者→クリエイター申請→承認→商品登録→入稿→出品申請',async({browser})=>{const a=await newLoggedPage(browser,E.SM_STAGING_APPLICANT_EMAIL,E.SM_STAGING_APPLICANT_PASSWORD);const initial=await a.page.evaluate(()=>({caps:currentUser()?.capabilities||[],app:userData()?.creatorApplication||null}));if(initial.caps.includes('creator')||initial.app?.status==='pending')throw new Error('STAGING applicant fixture must be reset to buyer-only with no pending application');const shop=`E2E Atelier ${Date.now()}`;await a.page.evaluate(()=>creatorApplyModal());await a.page.locator('#caShop').fill(shop);await a.page.locator('#caBio').fill('STAGING E2E専用。オリジナルステッカーの製造・配送確認用。');await a.page.locator('#caAgree').check();await a.page.getByRole('button',{name:'申請する'}).click();await expect.poll(async()=>a.page.evaluate(()=>userData()?.creatorApplication?.status)).toBe('pending');const admin=await newLoggedPage(browser,E.SM_STAGING_ADMIN_EMAIL,E.SM_STAGING_ADMIN_PASSWORD);await admin.page.evaluate(()=>s1AdminCreatorApplications());const card=admin.page.locator('article').filter({hasText:shop});await expect(card).toBeVisible();await card.getByRole('button',{name:'承認'}).click();await expect.poll(async()=>{const rows=await rest(admin.page,`sm_creator_applications?select=status&shop_name=eq.${encodeURIComponent(shop)}`);return rows?.[0]?.status}).toBe('approved');await admin.ctx.close();await a.ctx.close();const c=await newLoggedPage(browser,E.SM_STAGING_APPLICANT_EMAIL,E.SM_STAGING_APPLICANT_PASSWORD);const user=await c.page.evaluate(()=>({role:currentUser()?.role,caps:currentUser()?.capabilities||[]}));expect(user.caps).toContain('creator');await c.page.evaluate(()=>sellWizard());state.listingName=`E2E Physical Sticker ${Date.now()}`;await c.page.locator('#smNewName').fill(state.listingName);await c.page.locator('#smNewDesc').fill('STAGING E2Eで製造・配送・差し戻し・返金を検証する物理ステッカー。');await c.page.locator('#smNewDigital').fill('0');await c.page.locator('#smNewPhysical').fill('980');await c.page.locator('#smNewMaterial').selectOption({label:'耐水PET'});await c.page.locator('#smNewSize').selectOption({label:'50mm'});await c.page.locator('#smNewRights').check();await c.page.locator('#smNewPublic').setInputFiles(image());await c.page.locator('#smNewPrint').setInputFiles(image());await c.page.getByRole('button',{name:'保存して審査申請'}).click();await c.page.waitForFunction(()=>location.hash.includes('/work/'),{timeout:30000});state.listingProductId=(await c.page.evaluate(()=>location.hash)).split('/work/')[1].split('?')[0];expect(state.listingProductId).toBeTruthy();const rows=await rest(c.page,`sm_products?select=status&id=eq.${encodeURIComponent(state.listingProductId)}`);expect(rows?.[0]?.status).toBe('reviewing');await c.ctx.close()});

test('E2E-03 商品審査：原価設定→承認→購入者側公開',async({browser})=>{expect(state.listingProductId).toBeTruthy();const admin=await newLoggedPage(browser,E.SM_STAGING_ADMIN_EMAIL,E.SM_STAGING_ADMIN_PASSWORD);await rpc(admin.page,'sm_admin_set_manufacturer_routing',{p_manufacturer_id:E.SM_STAGING_MANUFACTURER_ID,p_priority:1,p_is_default:true});await gotoHash(admin.page,`admin-work/${state.listingProductId}`);await expect(admin.page.locator('.sm-mvp-admin-publish-readiness')).toBeVisible();const cost=admin.page.locator('[data-sm-mvp-variant-cost]').first();await cost.fill('120');await admin.page.getByRole('button',{name:'原価保存'}).first().click();await admin.page.getByRole('button',{name:'承認する'}).click();await expect.poll(async()=>{const rows=await rest(admin.page,`sm_products?select=status&id=eq.${encodeURIComponent(state.listingProductId)}`);return rows?.[0]?.status}).toBe('published');await admin.ctx.close();const buyer=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);await gotoHash(buyer.page,`search?q=${encodeURIComponent(state.listingName)}`);await expect(buyer.page.getByText(state.listingName,{exact:false}).first()).toBeVisible();await buyer.ctx.close()});

test('E2E-04 製造：注文→自動割当→製造→検品→発送準備→発送',async({browser})=>{if(stripeReady){const buyer=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);const o=await buyPhysical(buyer.page,state.listingProductId);state.fulfillmentOrderId=o.id;await buyer.ctx.close()}else{const buyer=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);const rows=await rest(buyer.page,`sm_orders?select=id,status&id=eq.${encodeURIComponent(state.fulfillmentOrderId)}`);expect(rows?.[0]?.status).toBe('confirmed');await buyer.ctx.close()}const mf=await newLoggedPage(browser,E.SM_STAGING_MANUFACTURER_EMAIL,E.SM_STAGING_MANUFACTURER_PASSWORD);const m=await mfgForOrder(mf.page,state.fulfillmentOrderId);state.fulfillmentMfgId=m.id;await gotoHash(mf.page,`manufacturer-order/${m.id}`);await mf.page.getByRole('button',{name:'製造を開始'}).click();await expect(mf.page.getByRole('button',{name:'検品へ進む'})).toBeVisible();await mf.page.getByRole('button',{name:'検品へ進む'}).click();await expect(mf.page.getByRole('button',{name:'発送準備へ進む'})).toBeVisible();await mf.page.getByRole('button',{name:'発送準備へ進む'}).click();await mf.page.locator('#mfgCarrier').fill('ヤマト運輸 E2E');await mf.page.locator('#mfgTracking').fill(`E2E${Date.now()}`);await mf.page.getByRole('button',{name:'発送する'}).click();await waitStatus(mf.page,'sm_manufacturing_orders',m.id,'shipped');await mf.ctx.close()});

test('E2E-05 配送・売上確定：購入者受取→取引完了→報酬確定',async({browser})=>{const buyer=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);await gotoHash(buyer.page,`order/${state.fulfillmentOrderId}`);await buyer.page.getByRole('button',{name:'受け取りを完了する'}).click();await expect(buyer.page.getByRole('button',{name:'内容を確認して取引完了'})).toBeVisible();await buyer.page.getByRole('button',{name:'内容を確認して取引完了'}).click();await waitStatus(buyer.page,'sm_orders',state.fulfillmentOrderId,'completed');await buyer.ctx.close();const creatorEmail=stripeReady?E.SM_STAGING_APPLICANT_EMAIL:E.SM_STAGING_CREATOR_EMAIL;const creatorPassword=stripeReady?E.SM_STAGING_APPLICANT_PASSWORD:E.SM_STAGING_CREATOR_PASSWORD;const productId=stripeReady?state.listingProductId:E.SM_STAGING_PRODUCT_ID;const creator=await newLoggedPage(browser,creatorEmail,creatorPassword);const rows=await rpc(creator.page,'sm_creator_sales_detail',{});const row=rows.find(x=>x.order_id===state.fulfillmentOrderId&&x.product_id===productId);expect(row).toBeTruthy();expect(['confirmed','scheduled','paid']).toContain(row.payout_status);expect(Number(row.payout_confirmed)).toBeGreaterThan(0);await creator.ctx.close()});

test('E2E-06 製造不能：保留→修正依頼→修正版→製造再開',async({browser})=>{if(stripeReady){const buyer=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);const o=await buyPhysical(buyer.page,state.listingProductId);state.issueOrderId=o.id;await buyer.ctx.close()}else{const buyer=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);const rows=await rest(buyer.page,`sm_orders?select=id,status&id=eq.${encodeURIComponent(state.issueOrderId)}`);expect(rows?.[0]?.status).toBe('confirmed');await buyer.ctx.close()}const mf=await newLoggedPage(browser,E.SM_STAGING_MANUFACTURER_EMAIL,E.SM_STAGING_MANUFACTURER_PASSWORD);const m=await mfgForOrder(mf.page,state.issueOrderId);state.issueMfgId=m.id;await gotoHash(mf.page,`manufacturer-order/${m.id}`);await mf.page.getByRole('button',{name:'製造できない'}).click();await mf.page.locator('#smMvpUnableCategory').selectOption('low_resolution');await mf.page.locator('#smMvpUnableDescription').fill('E2E: 印刷解像度を再確認する必要があります。');await mf.page.getByRole('button',{name:'注文を保留して修正依頼'}).click();await waitStatus(mf.page,'sm_manufacturing_orders',m.id,'unable');await mf.ctx.close();const creatorEmail=stripeReady?E.SM_STAGING_APPLICANT_EMAIL:E.SM_STAGING_CREATOR_EMAIL;const creatorPassword=stripeReady?E.SM_STAGING_APPLICANT_PASSWORD:E.SM_STAGING_CREATOR_PASSWORD;const productId=stripeReady?state.listingProductId:E.SM_STAGING_PRODUCT_ID;const creator=await newLoggedPage(browser,creatorEmail,creatorPassword);await gotoHash(creator.page,`work/${productId}?tab=edit`);const card=creator.page.locator('.sm-mvp-revision-card').filter({hasText:m.id});await expect(card).toBeVisible();await card.locator('input[type=file]').setInputFiles(image());await card.getByRole('button',{name:'修正版を提出'}).click();await expect.poll(async()=>{const r=await rpc(creator.page,'sm_creator_revision_requests',{});return r?.find(x=>x.manufacturingOrderId===m.id)?.status}).toBe('revision_requested');await creator.ctx.close();const mf2=await newLoggedPage(browser,E.SM_STAGING_MANUFACTURER_EMAIL,E.SM_STAGING_MANUFACTURER_PASSWORD);await gotoHash(mf2.page,`manufacturer-order/${m.id}`);await mf2.page.getByRole('button',{name:'修正版を確認して製造再開'}).click();await waitStatus(mf2.page,'sm_manufacturing_orders',m.id,'manufacturing');await mf2.ctx.close()});

test('E2E-07 不良・再製造：写真申告→再製造→再発送→案件完了',async({browser})=>{const buyer=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);await gotoHash(buyer.page,`support/new?order=${encodeURIComponent(state.fulfillmentOrderId)}`);await buyer.page.locator('#supType').selectOption({label:'印刷不良'});await buyer.page.locator('#supBody').fill('E2E: 印刷面に不良があるため写真を添付します。');await buyer.page.locator('#supFile').setInputFiles(image());await buyer.page.getByRole('button',{name:'問い合わせを開始'}).click();await buyer.page.waitForFunction(()=>location.hash.startsWith('#/support/')&&!location.hash.startsWith('#/support/new'),{timeout:20000});const caseId=(await buyer.page.evaluate(()=>location.hash)).split('/support/')[1].split('?')[0];await buyer.ctx.close();const admin=await newLoggedPage(browser,E.SM_STAGING_ADMIN_EMAIL,E.SM_STAGING_ADMIN_PASSWORD);await gotoHash(admin.page,`support/${caseId}`);await admin.page.getByRole('button',{name:'再製造を手配'}).click();await expect.poll(async()=>{const r=await rest(admin.page,`sm_manufacturing_orders?select=id,reproduction_of,support_case_id,status&order_id=eq.${encodeURIComponent(state.fulfillmentOrderId)}`);const x=r.find(v=>v.reproduction_of&&v.support_case_id===caseId);state.reproductionMfgId=x?.id||null;return !!x}).toBe(true);await admin.ctx.close();const mf=await newLoggedPage(browser,E.SM_STAGING_MANUFACTURER_EMAIL,E.SM_STAGING_MANUFACTURER_PASSWORD);await gotoHash(mf.page,`manufacturer-order/${state.reproductionMfgId}`);for(const label of ['製造を開始','検品へ進む','発送準備へ進む']){await mf.page.getByRole('button',{name:label}).click()}await mf.page.locator('#mfgCarrier').fill('ヤマト運輸 E2E 再発送');await mf.page.locator('#mfgTracking').fill(`RE${Date.now()}`);await mf.page.getByRole('button',{name:'発送する'}).click();await mf.page.getByRole('button',{name:'配送完了を登録'}).click();await waitStatus(mf.page,'sm_manufacturing_orders',state.reproductionMfgId,'delivered');await mf.ctx.close();const check=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);await expect.poll(async()=>{const r=await rest(check.page,`sm_support_cases?select=status&id=eq.${encodeURIComponent(caseId)}`);return r?.[0]?.status}).toBe('resolved');await check.ctx.close()});

test('E2E-08 返金：問い合わせ→Stripe Test Refund→Order/Payout調整→通知',async({browser})=>{const buyer=await newLoggedPage(browser,E.SM_STAGING_BUYER_EMAIL,E.SM_STAGING_BUYER_PASSWORD);const o=await buyPhysical(buyer.page,state.listingProductId);await gotoHash(buyer.page,`support/new?order=${encodeURIComponent(o.id)}`);await buyer.page.locator('#supType').selectOption({label:'返金'});await buyer.page.locator('#supBody').fill('E2E: 返金連動確認用の問い合わせです。');await buyer.page.getByRole('button',{name:'問い合わせを開始'}).click();await buyer.page.waitForFunction(()=>location.hash.startsWith('#/support/')&&!location.hash.startsWith('#/support/new'),{timeout:20000});const caseId=(await buyer.page.evaluate(()=>location.hash)).split('/support/')[1].split('?')[0];await buyer.ctx.close();const admin=await newLoggedPage(browser,E.SM_STAGING_ADMIN_EMAIL,E.SM_STAGING_ADMIN_PASSWORD);await gotoHash(admin.page,`support/${caseId}`);await admin.page.getByRole('button',{name:'返金処理'}).click();await admin.page.getByRole('button',{name:'返金する'}).click();await expect.poll(async()=>{const r=await rest(admin.page,`sm_orders?select=status&id=eq.${encodeURIComponent(o.id)}`);return r?.[0]?.status},{timeout:45000}).toBe('refunded');const payout=await rest(admin.page,`sm_creator_payouts?select=status,adjustment,amount&order_id=eq.${encodeURIComponent(o.id)}`);expect(payout.length).toBeGreaterThan(0);expect(payout.every(x=>x.status==='adjusted')).toBe(true);const notices=await rest(admin.page,`sm_notifications?select=type,title,ref&user_id=eq.${encodeURIComponent((await rest(admin.page,`sm_orders?select=user_id&id=eq.${encodeURIComponent(o.id)}`))[0].user_id)}&type=eq.refund`);expect(notices.length).toBeGreaterThan(0);await admin.ctx.close()});
