/* Sticker Market Commercial MVP — persistence for existing D-01..D-24 flows. */
const smMvpDemoSubmitDemand=s1SubmitDemand,smMvpDemoLinkDemand=s1LinkDemand,smMvpDemoCreateCustom=s1CreateCustomOrder,smMvpDemoCustomTransition=s1CustomTransition,smMvpDemoCustomMessage=s1CustomSendMessage,smMvpDemoCreateSupport=s1CreateSupport,smMvpDemoSubmitReport=s1SubmitReport,smMvpDemoSubmitAppeal=s1SubmitAppeal,smMvpDemoCloseAccount=s1CloseAccount;

s1SubmitDemand=async function(){if(!SM_MVP.live())return smMvpDemoSubmitDemand();const title=$('#drTitle')?.value.trim();if(!title)return toast('希望デザインを入力してください');try{const id=smMvpNewId('demand');await smMvpRest('sm_demand_requests',{method:'POST',body:JSON.stringify({id,user_id:currentUser().id,desired_design:title,size:$('#drSize').value,material:$('#drMat').value,use_case:$('#drUse').value,reference_text:$('#drRef').value.trim()}),headers:{Prefer:'return=minimal'}});await smMvpHydrateOperationalCaches();closeModal();toast('需要リクエストを登録しました');go('demand-requests')}catch(e){toast(e.message||'リクエストを登録できませんでした')}};
s1LinkDemand=async function(id){if(!SM_MVP.live())return smMvpDemoLinkDemand(id);const pid=$('#demandProduct')?.value;if(!pid)return;try{await smMvpRpc('sm_link_demand_product',{p_request_id:id,p_product_id:pid});await smMvpHydrateOperationalCaches();closeModal();toast('購入者へ通知しました');render()}catch(e){toast(e.message||'商品を紐付けできませんでした')}};

s1CreateCustomOrder=async function(creatorId){if(!SM_MVP.live())return smMvpDemoCreateCustom(creatorId);const title=$('#coTitle')?.value.trim(),body=$('#coBody')?.value.trim();if(!title||!body)return toast('タイトルと希望内容を入力してください');try{const id=smMvpNewId('custom');await smMvpRest('sm_custom_orders',{method:'POST',body:JSON.stringify({id,buyer_user_id:currentUser().id,creator_id:creatorId,request:{title,body,useCase:$('#coUse').value,budget:Number($('#coBudget').value),revisionCount:0}}),headers:{Prefer:'return=minimal'}});await smMvpHydrateOperationalCaches();go(`custom-order/${id}`)}catch(e){toast(e.message||'オーダーメイドを依頼できませんでした')}};
s1CustomTransition=async function(id,status){if(!SM_MVP.live())return smMvpDemoCustomTransition(id,status);const internal=({'依頼':'requested','受注':'accepted','制作中':'working','初稿':'draft','修正':'revision','承認':'approved','購入手続き':'checkout','決済':'paid','キャンセル':'cancelled'})[status]||status;try{await smMvpRpc('sm_transition_custom_order',{p_custom_order_id:id,p_status:internal,p_note:null});await smMvpHydrateOperationalCaches();render()}catch(e){toast(e.message||'案件状態を変更できませんでした')}};
s1SubmitCustomDraft=async function(id){if(!SM_MVP.live())return;const t=$('#coDraft')?.value.trim();if(!t)return toast('初稿内容を入力してください');try{const file=$('#modal input[type=file]')?.files?.[0];if(file)await smMvpUploadAndRegister(file,'sm-user-private','custom_order_asset','custom_order',id);await smMvpRpc('sm_transition_custom_order',{p_custom_order_id:id,p_status:'draft',p_note:t});await smMvpHydrateOperationalCaches();closeModal();render()}catch(e){toast(e.message||'初稿を提出できませんでした')}};
s1CustomSendMessage=async function(id){if(!SM_MVP.live())return smMvpDemoCustomMessage(id);const t=$('#coMsg')?.value.trim();if(!t)return;try{await smMvpRest('sm_custom_order_messages',{method:'POST',body:JSON.stringify({custom_order_id:id,sender_user_id:currentUser().id,body:t}),headers:{Prefer:'return=minimal'}});await smMvpHydrateOperationalCaches();render()}catch(e){toast(e.message||'メッセージを送信できませんでした')}};

s1CreateSupport=async function(){if(!SM_MVP.live())return smMvpDemoCreateSupport();const orderId=$('#supOrder')?.value,type=$('#supType')?.value,body=$('#supBody')?.value.trim();if(!orderId||!body)return toast('注文と状況を確認してください');try{const id=smMvpNewId('support');await smMvpRest('sm_support_cases',{method:'POST',body:JSON.stringify({id,order_id:orderId,user_id:currentUser().id,type,body,attachment_key:null}),headers:{Prefer:'return=minimal'}});const file=$('#supFile')?.files?.[0];if(file){const up=await smMvpUploadAndRegister(file,'sm-user-private','support_attachment','support_case',id);await smMvpRest(`sm_support_cases?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({attachment_key:up.fileId}),headers:{Prefer:'return=minimal'}})}await smMvpHydrateOperationalCaches();go(`support/${id}`)}catch(e){toast(e.message||'問い合わせを開始できませんでした')}};

s1SubmitReport=async function(type,targetId){if(!SM_MVP.live())return smMvpDemoSubmitReport(type,targetId);try{const id=smMvpNewId('report');await smMvpRest('sm_reports',{method:'POST',body:JSON.stringify({id,reporter_user_id:currentUser().id,target_type:type,target_id:targetId,reason:$('#repReason').value,body:$('#repBody').value.trim()}),headers:{Prefer:'return=minimal'}});await smMvpHydrateOperationalCaches();closeModal();toast('通報を受け付けました')}catch(e){toast(e.message||'通報を送信できませんでした')}};
s1SubmitAppeal=async function(productId){if(!SM_MVP.live())return smMvpDemoSubmitAppeal(productId);const body=$('#appealBody')?.value.trim();if(!body)return toast('申立て内容を入力してください');try{const id=smMvpNewId('rights');let evidence=null;const f=$('#appealFile')?.files?.[0];if(f){const up=await smMvpUploadAndRegister(f,'sm-user-private','rights_evidence','product',productId);evidence=up.fileId}await smMvpRest('sm_rights_cases',{method:'POST',body:JSON.stringify({id,product_id:productId,creator_id:currentUser().creatorId,type:'異議申立て',body,evidence_key:evidence}),headers:{Prefer:'return=minimal'}});await smMvpHydrateOperationalCaches();toast('異議申立てを送信しました');go(`work/${productId}?tab=review`)}catch(e){toast(e.message||'異議申立てを送信できませんでした')}};

/* Server account closure check. Auth identity is retained for records, but capabilities are removed. */
s1AccountClosePage=async function(){if(!SM_MVP.live())return;const u=currentUser();if(!u)return go('login');shell(`<h1>退会条件の確認</h1><div class="notice">サーバーで未完了取引を確認しています…</div>`,{title:'退会',back:true,cart:false});try{const c=await smMvpRpc('sm_account_closure_check',{});const rows=[['未完了注文',c.incompleteOrders],['未処理返金',c.openRefunds],['未処理オーダーメイド',c.openCustomOrders],['未解決問い合わせ',c.openSupport],['公開・審査中商品',c.publicProducts],['未払い報酬',c.unpaidPayouts]].filter(x=>Number(x[1])>0);shell(`<h1>退会条件の確認</h1>${c.canClose?`<div class="card panel"><h2>退会可能です</h2><p>取引記録は法令・会計・監査上必要な範囲で保持します。</p><button class="btn danger" onclick="s1CloseAccount()">退会する</button></div>`:`<div class="notice demo"><b>現在は退会できません。</b><div class="detail-list" style="margin-top:10px">${rows.map(x=>`<div><span>${x[0]}</span><b>${x[1]}件</b></div>`).join('')}</div></div>`}`,{title:'退会',back:true,cart:false})}catch(e){shell(`<div class="empty"><h2>退会条件を確認できません</h2><p>${esc(e.message||'サーバーエラー')}</p></div>`,{title:'退会',back:true,cart:false})}};
s1CloseAccount=function(){if(!SM_MVP.live())return smMvpDemoCloseAccount();confirmAction('アカウントを退会しますか？','未完了業務がないことをサーバーで再確認して退会します。','退会する',async()=>{try{await smMvpRpc('sm_close_account',{});smMvpAuthSave(null);db.session.userId=null;save();history.replaceState({},'','#/landing');render()}catch(e){toast(e.message||'退会できませんでした',3200)}})};
