/* Sticker Market MVP formal delta v1.0 — additive only. */
const SM_MVP_DELTA_VERSION='1.0';
const SM_MVP_MFG_ISSUE_LABELS={low_resolution:'解像度不足',corrupt_data:'データ破損',cutline:'カットライン不備',transparency:'透明処理不備',unsupported_spec:'対応外仕様',other:'その他'};

smMvpOrderLabel=function(s){return({pending_payment:'支払い待ち',paid:'支払済み',confirmed:'注文確定',on_hold:'製造確認中',manufacturing:'製造中',inspection:'検品中',shipped:'発送済み',delivered:'配送完了',completed:'取引完了',cancelled:'キャンセル',refunded:'返金済み'})[s]||s};
smMvpMfgLabel=function(s){return({confirmed:'注文受付',manufacturing:'製造中',inspection:'検品',ready_to_ship:'発送準備',shipped:'発送済み',delivered:'配送完了',unable:'製造できません',revision_requested:'入稿データ修正待ち',cancelled:'キャンセル'})[s]||s};

function smMvpMfgInternal(m){if(m?.serverStatus)return m.serverStatus;return({'注文受付':'confirmed','製造中':'manufacturing','検品':'inspection','発送準備':'ready_to_ship','発送済み':'shipped','配送完了':'delivered','製造できません':'unable','製造不能':'unable','入稿データ修正待ち':'revision_requested','キャンセル':'cancelled'})[m?.status]||m?.status||'confirmed'}
async function smMvpDeltaHydrate(u){
 if(!SM_MVP.live()||!u)return;
 try{const os=await smMvpRest('sm_orders?select=id,status,received_at,completed_at');for(const x of os||[]){const o=userData().orders.find(v=>v.id===x.id);if(o){o.serverStatus=x.status;o.status=smMvpOrderLabel(x.status);o.receivedAt=x.received_at;o.completedAt=x.completed_at}}}catch{}
 try{const rows=await smMvpRest('sm_manufacturing_orders?select=id,status,manufacturer_id,issue_order_item_id,issue_category,issue_description,issue_attachment_file_id,issue_reported_at,revision_requested_at,revision_resolved_at,source_revision,updated_at');for(const x of rows||[]){const m=s1Scenario().manufacturingOrders.find(v=>v.id===x.id);if(m)Object.assign(m,{serverStatus:x.status,status:smMvpMfgLabel(x.status),manufacturerId:x.manufacturer_id,issueOrderItemId:x.issue_order_item_id,issueCategory:x.issue_category,issueDescription:x.issue_description,issueAttachmentFileId:x.issue_attachment_file_id,issueReportedAt:x.issue_reported_at,revisionRequestedAt:x.revision_requested_at,revisionResolvedAt:x.revision_resolved_at,sourceRevision:Number(x.source_revision||0),updatedAt:x.updated_at})}}catch{}
 if(u.capabilities?.includes('creator')||u.role==='creator'){
  try{SM_MVP.revisionRequests=await smMvpRpc('sm_creator_revision_requests',{})||[]}catch{SM_MVP.revisionRequests=[]}
  try{SM_MVP.creatorSalesDetail=await smMvpRpc('sm_creator_sales_detail',{})||[]}catch{SM_MVP.creatorSalesDetail=[]}
 }
}
const smMvpDeltaBaseHydrate=smMvpHydrateUser;
smMvpHydrateUser=async function(){const u=await smMvpDeltaBaseHydrate();if(u)await smMvpDeltaHydrate(u);return u};

const smMvpDeltaBasePurchased=s1PurchasedProduct;
s1PurchasedProduct=function(userId,productId){if(!SM_MVP.live())return smMvpDeltaBasePurchased(userId,productId);const d=db.userData[userId],orders=d?.orders||[];for(const o of orders){const item=(o.items||[]).find(x=>x.productId===productId);if(!item||['cancelled','refunded'].includes(o.serverStatus))continue;if(item.kind==='digital')return !['pending_payment','cancelled','refunded'].includes(o.serverStatus);if(item.kind==='physical'&&o.serverStatus==='completed')return true}return false};

const smMvpDeltaBaseSetMfg=s1SetManufacturingStatus;
s1SetManufacturingStatus=async function(id,status,note=''){
 if(!SM_MVP.live())return smMvpDeltaBaseSetMfg(id,status,note);
 const internal=({'注文受付':'confirmed','製造中':'manufacturing','検品':'inspection','発送準備':'ready_to_ship','発送済み':'shipped','配送完了':'delivered','製造できません':'unable','入稿データ修正待ち':'revision_requested'})[status]||status;
 if(internal==='unable')return smMvpOpenUnableModal(id);
 try{await smMvpRpc('sm_set_manufacturing_status',{p_mfg_id:id,p_status:internal,p_carrier:$('#mfgCarrier')?.value.trim()||null,p_tracking:$('#mfgTracking')?.value.trim()||null});await smMvpHydrateUser();render()}catch(e){const map={INVALID_TRANSITION:'現在の工程からその状態へは変更できません。前工程を完了してください。',SHIPPING_INFO_REQUIRED:'発送時は配送会社と追跡番号を入力してください。',ADMIN_REQUIRED:'キャンセルは運営管理者が処理してください。'};toast(map[e.message]||e.message||'製造状態を更新できませんでした',3600)}
};
function smMvpOpenUnableModal(id){const m=s1Scenario().manufacturingOrders.find(x=>x.id===id),o=userData().orders.find(x=>x.id===m?.orderId),items=(o?.items||[]).filter(x=>x.kind==='physical');showModal(`<div class="section-head"><div><h2>製造できない</h2><p class="muted">注文を保留し、運営と該当クリエイターへ修正依頼を通知します。</p></div><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>対象商品</label><select id="smMvpUnableItem"><option value="">注文全体</option>${items.map(x=>`<option value="${x.id}">${esc(productBy(x.productId)?.name||x.productId)}</option>`).join('')}</select></div><div class="field"><label>問題分類</label><select id="smMvpUnableCategory"><option value="low_resolution">解像度不足</option><option value="corrupt_data">データ破損</option><option value="cutline">カットライン不備</option><option value="transparency">透明処理不備</option><option value="unsupported_spec">対応外仕様</option><option value="other">その他</option></select></div><div class="field"><label>問題説明 <span class="small muted">必須</span></label><textarea id="smMvpUnableDescription" rows="5" placeholder="修正すべき箇所と、製造再開に必要な条件を具体的に記載してください"></textarea></div><div class="field"><label>参考画像・資料（任意）</label><input id="smMvpUnableFile" type="file" accept="image/png,image/jpeg,image/webp,application/pdf,.pdf"></div><button class="btn danger" onclick="smMvpSubmitUnable('${id}')">注文を保留して修正依頼</button>`)}
async function smMvpSubmitUnable(id){const category=$('#smMvpUnableCategory')?.value,description=$('#smMvpUnableDescription')?.value.trim(),item=$('#smMvpUnableItem')?.value||null;if(!description)return toast('問題説明を入力してください');busy('製造差し戻しを登録しています…');try{let attachment=null;const f=$('#smMvpUnableFile')?.files?.[0];if(f){const up=await smMvpUploadAndRegister(f,'sm-user-private','manufacturing_issue','manufacturing_order',id);attachment=up.fileId}await smMvpRpc('sm_mark_manufacturing_unable',{p_mfg_id:id,p_order_item_id:item,p_category:category,p_description:description,p_attachment_file_id:attachment});await smMvpHydrateUser();done();closeModal();toast('製造を保留し、修正依頼を通知しました');render()}catch(e){done();toast(e.message||'差し戻しを登録できませんでした',3600)}}
async function smMvpOpenManufacturingSource(mfgId,orderItemId){try{const r=await smMvpEdge('sm-private-file',{manufacturingOrderId:mfgId,orderItemId,download:true});location.assign(r.url)}catch(e){toast(e.message||'この注文の印刷元データを取得できませんでした',3400)}}
async function smMvpOpenRegisteredFile(fileId){try{const r=await smMvpEdge('sm-private-file',{fileId,download:false});window.open(r.url,'_blank','noopener')}catch(e){toast(e.message||'資料を開けませんでした',3200)}}

function smMvpEnhanceManufacturerOrder(id){
 if(!SM_MVP.live())return;const m=s1Scenario().manufacturingOrders.find(x=>x.id===id),main=$('#main');if(!m||!main)return;const state=smMvpMfgInternal(m),o=userData().orders.find(x=>x.id===m.orderId),physical=(o?.items||[]).filter(x=>x.kind==='physical');
 const section=[...main.querySelectorAll('section')].find(x=>x.querySelector('h2')?.textContent.includes('工程更新'));if(section){const row=section.querySelector('.btn-row');if(row){const next={confirmed:['製造を開始','manufacturing'],manufacturing:['検品へ進む','inspection'],inspection:['発送準備へ進む','ready_to_ship'],ready_to_ship:['発送する','shipped'],shipped:['配送完了を登録','delivered'],revision_requested:['修正版を確認して製造再開','manufacturing']}[state];row.innerHTML=`${next?`<button class="btn primary" onclick="s1SetManufacturingStatus('${id}','${next[1]}')">${next[0]}</button>`:''}${['confirmed','manufacturing','inspection','ready_to_ship'].includes(state)?`<button class="btn danger" onclick="smMvpOpenUnableModal('${id}')">製造できない</button>`:''}${state==='unable'?'<span class="status warn">クリエイターの修正版を待っています</span>':''}`}
   const oldSave=[...section.querySelectorAll('button')].find(b=>b.textContent.includes('製造・配送情報を保存'));if(oldSave)oldSave.hidden=true;
 }
 const printButtons=[...main.querySelectorAll('button')].filter(b=>b.textContent.trim()==='印刷元データ');printButtons.forEach((b,i)=>{const it=physical[i];if(it)b.onclick=()=>smMvpOpenManufacturingSource(id,it.id)});
 if((m.issueCategory||m.issueDescription)&&!main.querySelector('.sm-mvp-mfg-issue')){const box=document.createElement('section');box.className='section card panel sm-mvp-mfg-issue';box.innerHTML=`<div class="section-head"><div><h2>製造上の問題</h2><span class="status ${state==='revision_requested'?'warn':'danger'}">${esc(smMvpMfgLabel(state))}</span></div></div><div class="detail-list"><div><span>分類</span><b>${esc(SM_MVP_MFG_ISSUE_LABELS[m.issueCategory]||m.issueCategory||'—')}</b></div><div><span>内容</span><b>${esc(m.issueDescription||'—')}</b></div><div><span>修正版</span><b>${m.sourceRevision?`第${m.sourceRevision}版`:'未提出'}</b></div></div>${m.issueAttachmentFileId?`<button class="btn" onclick="smMvpOpenRegisteredFile('${m.issueAttachmentFileId}')">参考資料を確認</button>`:''}`;section?.after(box)}
}
const smMvpDeltaBaseManufacturerOrder=s1ManufacturerOrderPage;
s1ManufacturerOrderPage=function(id){const out=smMvpDeltaBaseManufacturerOrder(id);if(SM_MVP.live())setTimeout(()=>smMvpEnhanceManufacturerOrder(id),0);return out};

async function smMvpSubmitManufacturingRevision(mfgId,orderItemId){const input=document.querySelector(`[data-sm-mvp-revision-file="${CSS.escape(mfgId)}"]`),note=document.querySelector(`[data-sm-mvp-revision-note="${CSS.escape(mfgId)}"]`),file=input?.files?.[0];if(!file)return toast('修正版ファイルを選択してください');busy('修正版を検証・保存しています…');try{const up=await smMvpUploadAndRegister(file,'sm-product-private','manufacturing_revision','manufacturing_order',mfgId);const rev=await smMvpRpc('sm_submit_manufacturing_revision',{p_mfg_id:mfgId,p_order_item_id:orderItemId,p_file_id:up.fileId,p_note:note?.value.trim()||null});await smMvpHydrateUser();done();toast(`修正版 第${rev}版を提出しました`);render()}catch(e){done();toast(e.message||'修正版を提出できませんでした',3600)}}
function smMvpEnhanceWorkRevision(productId){if(!SM_MVP.live())return;const reqs=(SM_MVP.revisionRequests||[]).filter(x=>x.productId===productId),main=$('#main'),form=main?.querySelector('.work-edit-form')||main;if(!reqs.length||!form||form.querySelector('.sm-mvp-revision-requests'))return;const sec=document.createElement('section');sec.className='section card panel sm-mvp-revision-requests';sec.innerHTML=`<h2>入稿データ修正依頼</h2><p class="muted">元ファイルは残したまま、この製造注文で使用する修正版を履歴付きで登録します。</p>${reqs.map(r=>`<article class="sm-mvp-revision-card"><div class="section-head"><div><span class="status ${r.status==='revision_requested'?'warn':'danger'}">${r.status==='revision_requested'?'製造側の再確認待ち':'修正が必要'}</span><h3>${esc(r.productName||productId)}</h3></div><span class="small muted">${esc(r.manufacturingOrderId)}</span></div><div class="detail-list"><div><span>問題分類</span><b>${esc(SM_MVP_MFG_ISSUE_LABELS[r.issueCategory]||r.issueCategory||'—')}</b></div><div><span>問題内容</span><b>${esc(r.issueDescription||'—')}</b></div><div><span>現在の修正版</span><b>${Number(r.sourceRevision||0)?`第${Number(r.sourceRevision)}版`:'未提出'}</b></div></div>${r.issueAttachmentFileId?`<button class="btn" onclick="smMvpOpenRegisteredFile('${r.issueAttachmentFileId}')">製造側の参考資料</button>`:''}<div class="field"><label>修正版印刷データ</label><input type="file" data-sm-mvp-revision-file="${esc(r.manufacturingOrderId)}" accept="image/png,image/jpeg,image/webp,application/pdf,application/zip,.zip"></div><div class="field"><label>修正内容メモ</label><textarea rows="2" data-sm-mvp-revision-note="${esc(r.manufacturingOrderId)}" placeholder="どこを修正したか記載してください"></textarea></div><button class="btn primary" onclick="smMvpSubmitManufacturingRevision('${r.manufacturingOrderId}','${r.orderItemId}')">修正版を提出</button></article>`).join('')}`;form.appendChild(sec)}

async function smMvpRunSubmissionValidation(productId){const out=$('#smMvpSubmissionValidation');if(out)out.innerHTML='確認しています…';try{const r=await smMvpRpc('sm_validate_product_submission',{p_product_id:productId});if(!out)return;const errors=r.errors||[],warnings=r.warnings||[];out.innerHTML=`<div class="notice ${r.ok?'':'demo'}"><b>${r.ok?'入稿チェックOK':'修正が必要です'}</b>${errors.length?`<ul>${errors.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${warnings.length?`<div class="small"><b>確認事項</b><ul>${warnings.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div>`:''}${r.printFile?.metadata?.width?`<div class="small muted">検出画像: ${r.printFile.metadata.width}×${r.printFile.metadata.height}px / 推奨短辺 ${r.printFile.requiredMinPx}px以上</div>`:''}</div>`}catch(e){if(out)out.innerHTML=`<div class="notice demo">入稿チェックを実行できません：${esc(e.message||'サーバーエラー')}</div>`}}
function smMvpEnhanceSubmissionValidation(productId){if(!SM_MVP.live())return;const form=$('#main .work-edit-form'),assets=$('#main .sm-mvp-assets');if(!form||form.querySelector('.sm-mvp-submission-validation'))return;const sec=document.createElement('section');sec.className='section card panel sm-mvp-submission-validation';sec.innerHTML=`<h2>入稿チェック</h2><p class="muted">形式・容量・解像度・印刷サイズ・PNG透過・印刷元ファイル・製造可能仕様をサーバー側でも確認します。</p><button class="btn" onclick="smMvpRunSubmissionValidation('${productId}')">入稿チェックを実行</button><div id="smMvpSubmissionValidation" style="margin-top:10px"></div>`;(assets||form).appendChild(sec)}

const smMvpDeltaBaseBuyerReceived=s1BuyerReceived;
s1BuyerReceived=async function(mfgId){if(!SM_MVP.live())return smMvpDeltaBaseBuyerReceived(mfgId);const m=s1Scenario().manufacturingOrders.find(x=>x.id===mfgId);if(!m)return;try{await smMvpRpc('sm_confirm_order_received',{p_order_id:m.orderId});await smMvpHydrateUser();toast('受取を記録しました。商品内容を確認してください。');render()}catch(e){toast(e.message||'受取を記録できませんでした',3400)}};
async function smMvpCompleteOrder(orderId){try{await smMvpRpc('sm_complete_order',{p_order_id:orderId});await smMvpHydrateUser();toast('取引が完了しました');render()}catch(e){toast(e.message||'取引を完了できませんでした',3400)}}
function smMvpEnhanceOrderCompletion(orderId){if(!SM_MVP.live())return;const o=userData().orders.find(x=>x.id===orderId),main=$('#main');if(!o||!main||main.querySelector('.sm-mvp-order-completion'))return;if(o.serverStatus==='on_hold'){const n=document.createElement('div');n.className='notice demo sm-mvp-order-completion';n.innerHTML='<b>製造データを確認しています。</b><br>修正版入稿または製造先確認後に製造を再開します。';main.prepend(n);return}if(o.serverStatus==='delivered'){const sec=document.createElement('section');sec.className='section card panel sm-mvp-order-completion';sec.innerHTML='<h2>商品内容の確認</h2><p>商品に問題がなければ取引を完了してください。問題がある場合は、完了前でも既存の問い合わせから不良・誤配送・未着を報告できます。</p><button class="btn primary" onclick="smMvpCompleteOrder(\''+orderId+'\')">内容を確認して取引完了</button>';main.appendChild(sec)}else if(o.serverStatus==='completed'){const sec=document.createElement('section');sec.className='section card panel sm-mvp-order-completion';sec.innerHTML='<span class="status ok">取引完了</span><h2>この取引は完了しています</h2><p>レビューは任意です。未投稿でも取引完了状態は維持されます。</p>';main.appendChild(sec)}}

function smMvpEnhanceCreatorSales(){if(!SM_MVP.live())return;const main=$('#main'),rows=SM_MVP.creatorSalesDetail||[];if(!main||main.querySelector('.sm-mvp-sales-detail')||!(currentUser()?.capabilities||[]).includes('creator'))return;const sec=document.createElement('section');sec.className='section card panel sm-mvp-sales-detail';sec.innerHTML=`<h2>取引別売上・報酬</h2><p class="muted">購入者の配送先・支払情報は表示しません。</p>${rows.length?`<div class="table-wrap"><table class="table"><thead><tr><th>注文</th><th>販売価格</th><th>製造原価</th><th>手数料</th><th>報酬予定</th><th>報酬確定</th><th>支払状態</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${esc(x.order_id)}<div class="small muted">${esc(productBy(x.product_id)?.name||x.product_id)}</div></td><td>${yen(Number(x.gross))}</td><td>${yen(Number(x.manufacturing_cost))}</td><td>${yen(Number(x.platform_fee))}</td><td>${yen(Number(x.payout_planned))}</td><td>${yen(Number(x.payout_confirmed))}</td><td><span class="status">${esc(smMvpPayoutLabel(x.payout_status))}</span></td></tr>`).join('')}</tbody></table></div>`:'<p class="muted">対象取引はありません。</p>'}`;main.appendChild(sec)}

async function smMvpAdminAutoComplete(){try{const n=await smMvpRpc('sm_admin_complete_delivered_orders',{p_older_than_days:7});await smMvpHydrateUser();toast(`${n}件を取引完了にしました`);render()}catch(e){toast(e.message||'自動完了処理に失敗しました')}}
function smMvpEnhanceAdminCompletion(){const main=$('#main');if(!SM_MVP.live()||currentUser()?.role!=='admin'||!main||main.querySelector('.sm-mvp-admin-complete'))return;const sec=document.createElement('section');sec.className='section card panel sm-mvp-admin-complete';sec.innerHTML='<h2>取引完了補助</h2><p class="muted">購入者が操作しない配送完了注文を永久に滞留させないため、7日以上経過した注文を管理者判断で完了できます。</p><button class="btn" onclick="smMvpAdminAutoComplete()">配送完了7日超を取引完了</button>';main.appendChild(sec)}

const smMvpDeltaBaseAccountClose=s1AccountClosePage;
s1AccountClosePage=async function(){if(!SM_MVP.live())return smMvpDeltaBaseAccountClose();const u=currentUser();if(!u)return go('login');shell('<h1>退会条件の確認</h1><div class="notice">サーバーで未完了取引を確認しています…</div>',{title:'退会',back:true,cart:false});try{const c=await smMvpRpc('sm_account_closure_check',{});const rows=[['未完了注文',c.incompleteOrders],['未処理返金',c.openRefunds],['未処理再製造',c.openReproductions],['未処理オーダーメイド',c.openCustomOrders],['未解決問い合わせ',c.openSupport],['公開・審査中商品',c.publicProducts],['未完了販売注文',c.incompleteSales],['未確定・未払い報酬',c.unpaidPayouts]].filter(x=>Number(x[1])>0);shell(`<h1>退会条件の確認</h1>${c.canClose?'<div class="card panel"><h2>退会可能です</h2><p>取引記録は法令・会計・監査上必要な範囲で保持します。</p><button class="btn danger" onclick="s1CloseAccount()">退会する</button></div>':`<div class="notice demo"><b>現在は退会できません。</b><div class="detail-list" style="margin-top:10px">${rows.map(x=>`<div><span>${x[0]}</span><b>${x[1]}件</b></div>`).join('')}</div></div>`}`,{title:'退会',back:true,cart:false})}catch(e){shell(`<div class="empty"><h2>退会条件を確認できません</h2><p>${esc(e.message||'サーバーエラー')}</p></div>`,{title:'退会',back:true,cart:false})}};

if(typeof s1NotificationTarget==='function'){const smMvpDeltaBaseNotificationTarget=s1NotificationTarget;s1NotificationTarget=function(n){const r=n?.ref||{};if(n?.type==='manufacturing'&&r.productId&&(currentUser()?.capabilities||[]).includes('creator'))return `work/${r.productId}?tab=edit`;if(n?.type==='manufacturing'&&r.manufacturingOrderId&&currentUser()?.role==='manufacturer')return 'manufacturer-orders';return smMvpDeltaBaseNotificationTarget(n)}}

const smMvpDeltaBaseEnhance=s1EnhanceCurrentPage;
s1EnhanceCurrentPage=function(){smMvpDeltaBaseEnhance();if(!SM_MVP.live())return;const path=routePath().split('?')[0],seg=path.split('/'),q=parseQuery();if(seg[0]==='work'&&seg[1]&&(q.tab||'overview')==='edit'){smMvpEnhanceWorkRevision(seg[1]);smMvpEnhanceSubmissionValidation(seg[1])}if(seg[0]==='order'&&seg[1])smMvpEnhanceOrderCompletion(seg[1]);if(path==='sales')smMvpEnhanceCreatorSales();if(path==='admin'||path==='admin-manufacturing')smMvpEnhanceAdminCompletion()};
