/* Sticker Market Commercial MVP — product, review, fulfillment, support and admin operations. */
function smMvpSafeFileName(name){return String(name||'file').normalize('NFKC').replace(/[^A-Za-z0-9._-]+/g,'_').slice(-100)||'file'}
async function smMvpUploadAndRegister(file,bucket,purpose,targetType,targetId){
 if(!SM_MVP.live())throw new Error('SERVER_MODE_REQUIRED');if(!file)throw new Error('FILE_REQUIRED');
 const key=`${currentUser().id}/${targetType||'misc'}/${targetId||'general'}/${crypto.randomUUID()}-${smMvpSafeFileName(file.name)}`;
 let res=await fetch(`${SM_MVP_CONFIG.supabaseUrl}/storage/v1/object/${bucket}/${key.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{...smMvpHeaders(true), 'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});
 if(res.status===401&&await smMvpRefresh())res=await fetch(`${SM_MVP_CONFIG.supabaseUrl}/storage/v1/object/${bucket}/${key.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{...smMvpHeaders(true),'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});
 if(!res.ok)throw new Error(`UPLOAD_FAILED:${res.status}`);
 try{return await smMvpEdge('sm-file-register',{bucket,objectKey:key,purpose,targetType,targetId})}catch(e){throw e}
}
function smMvpServerStatusToWork(s){return({draft:'下書き',reviewing:'審査中',published:'公開中',private:'非公開',suspended:'差し戻し',rejected:'差し戻し'})[s]||'下書き'}
async function smMvpMergeAccessibleProducts(){
 const [rows,variants]=await Promise.all([smMvpRest('sm_products?select=*&order=created_at.desc'),smMvpRest('sm_product_variants?select=*&order=created_at.asc')]);const vm=new Map();(variants||[]).forEach(v=>{if(!vm.has(v.product_id))vm.set(v.product_id,v)});
 for(const p of rows||[]){let x=products.find(v=>v.id===p.id),v=vm.get(p.id);const mapped={id:p.id,name:p.name,creatorId:p.creator_id,category:p.category,digital:Number(p.digital_price),physical:Number(p.physical_price),material:p.material||'',shape:p.shape||'',size:v?.size||'50mm',variantId:v?.id||null,useCases:p.use_cases||[],tags:p.tags||[],description:p.description||'',art:p.metadata?.art||x?.art||'type',color:p.metadata?.color||x?.color||'#ececec',updated:p.updated_at,rating:x?.rating||0,favs:x?.favs||0,sales:x?.sales||0,views:x?.views||0,digitalAssetKey:p.digital_asset_key||null,privatePrintKey:p.private_print_key||null,publicMedia:p.public_media||[],serverStatus:p.status,rights:p.rights||{},metadata:p.metadata||{},variants:(variants||[]).filter(z=>z.product_id===p.id).map(z=>({id:z.id,name:z.name,material:z.material,size:z.size,shape:z.shape,price:Number(z.price),cost:Number(z.cost),active:z.active}))};if(x)Object.assign(x,mapped);else products.push(x=mapped);if(typeof ensureWorkMeta==='function'){const m=ensureWorkMeta(x);m.status=smMvpServerStatusToWork(p.status);m.updatedAt=p.updated_at;m.publishedAt=p.published_at;m.sellPhysical=!!p.metadata?.sell_physical}}
}
async function smMvpHydrateOperationalCaches(){
 const u=currentUser();if(!u)return;
 await smMvpMergeAccessibleProducts();
 const d=userData(),sc=typeof s1Scenario==='function'?s1Scenario():null;
 const [apps,supports,customs,demands,reports,rights]=await Promise.all([
   smMvpRest('sm_creator_applications?select=*&order=created_at.desc'),smMvpRest('sm_support_cases?select=*&order=created_at.desc'),smMvpRest('sm_custom_orders?select=*&order=created_at.desc'),smMvpRest('sm_demand_requests?select=*&order=created_at.desc'),smMvpRest('sm_reports?select=*&order=created_at.desc'),smMvpRest('sm_rights_cases?select=*&order=created_at.desc')
 ]);
 if(apps?.length){const a=apps[0];d.creatorApplication={id:a.id,status:a.status==='pending'?'pending':a.status,shop:a.shop_name,bio:a.activity,category:a.categories?.[0]||'',url:a.portfolio_url,date:a.created_at}}
 if(sc){
   sc.supportCases=[];for(const x of supports||[]){const msgs=await smMvpRest(`sm_support_messages?select=*&case_id=eq.${encodeURIComponent(x.id)}&order=created_at.asc`);sc.supportCases.push({id:x.id,caseId:x.id,orderId:x.order_id,userId:x.user_id,type:x.type,body:x.body,status:({open:'受付',waiting_user:'ユーザー返信待ち',waiting_admin:'運営確認中',resolved:'回答済み',cancelled:'キャンセル'})[x.status]||x.status,date:x.created_at,updatedAt:x.updated_at,attachment:x.attachment_key,messages:(msgs||[]).map(m=>({id:m.id,userId:m.sender_user_id,sender:m.sender_user_id===u.id?u.name:'相手',text:m.body,date:m.created_at})),resolution:x.resolution,refundAmount:0});}
   sc.customOrders=[];for(const x of customs||[]){const msgs=await smMvpRest(`sm_custom_order_messages?select=*&custom_order_id=eq.${encodeURIComponent(x.id)}&order=created_at.asc`);const r=x.request||{};sc.customOrders.push({id:x.id,caseId:x.id,userId:x.buyer_user_id,creatorId:x.creator_id,title:r.title||'オーダーメイド',body:r.body||'',useCase:r.useCase||'',budget:Number(r.budget||0),status:({requested:'依頼',accepted:'受注',working:'制作中',draft:'初稿',revision:'修正',approved:'承認',checkout:'購入手続き',paid:'決済',cancelled:'キャンセル'})[x.status]||x.status,date:x.created_at,updatedAt:x.updated_at,messages:(msgs||[]).map(m=>({id:m.id,userId:m.sender_user_id,sender:m.sender_user_id===u.id?u.name:'相手',text:m.body,date:m.created_at})),draftNote:r.latest_note||'',revisionCount:Number(r.revisionCount||0),approvedProductId:r.approvedProductId||null,orderId:x.linked_order_id});}
   sc.demandRequests=(demands||[]).map(x=>({id:x.id,requestId:x.id,userId:x.user_id,title:x.desired_design,size:x.size||'指定なし',material:x.material||'指定なし',useCase:x.use_case||'指定なし',reference:x.reference_text||'',status:({open:'募集中',claimed:'対応中',fulfilled:'対応済み',closed:'終了'})[x.status]||x.status,linkedProductId:x.linked_product_id,date:x.created_at}));
   sc.reports=(reports||[]).map(x=>({id:x.id,reportId:x.id,reporterId:x.reporter_user_id,targetType:x.target_type,targetId:x.target_id,reason:x.reason,body:x.body,status:({pending:'確認待ち',investigating:'調査中',resolved:'確認済み',dismissed:'問題なし'})[x.status]||x.status,date:x.created_at}));
   sc.rightsCases=(rights||[]).map(x=>({id:x.id,productId:x.product_id,creatorId:x.creator_id,type:x.type,body:x.body,evidence:x.evidence_key,status:({pending:'確認待ち',investigating:'調査中',resolved:'承認',rejected:'却下'})[x.status]||x.status,date:x.created_at}));
 }
 if(u.role==='creator'){
   try{const summary=await smMvpRpc('sm_creator_sales_summary',{});db.creator.sales[u.creatorId]={month:Number(summary.gross||0),last:0,count:Number(summary.salesCount||0),favs:Number(summary.favorites||0),payout:Number(summary.payoutTotal||0),unpaid:Number(summary.payoutUnpaid||0)}}catch{}
   try{SM_MVP.creatorOrders=await smMvpRpc('sm_creator_order_summary',{})||[]}catch{SM_MVP.creatorOrders=[]}
 }
 if(u.role==='admin'){
   try{SM_MVP.adminKpi=await smMvpRpc('sm_admin_kpi_summary',{})}catch{SM_MVP.adminKpi=null}
   const [profiles,mfs,mfgs,payouts]=await Promise.all([smMvpRest('sm_user_profiles?select=*&order=created_at.desc'),smMvpRest('sm_manufacturers?select=*&order=created_at.asc'),smMvpRest('sm_manufacturing_orders?select=*&order=created_at.desc'),smMvpRest('sm_creator_payouts?select=*&order=created_at.desc')]);SM_MVP.adminProfiles=profiles||[];
   if(sc){sc.manufacturers=(mfs||[]).map(m=>({id:m.id,name:m.name,userId:m.user_id,materials:m.supported_materials||[],sizes:m.supported_sizes||[],baseCost:Number(m.base_cost),leadDays:Number(m.lead_days),active:m.active,defectRate:Number(m.defect_rate),onTimeRate:Number(m.on_time_rate)}));sc.payouts=(payouts||[]).map(p=>({id:p.id,creatorId:p.creator_id,productId:null,orderId:p.order_id,gross:Number(p.gross),cost:Number(p.manufacturing_cost),fee:Number(p.platform_fee),amount:Number(p.amount),status:smMvpPayoutLabel(p.status),updatedAt:p.updated_at}));for(const m of mfgs||[]){if(!sc.manufacturingOrders.some(x=>x.id===m.id))sc.manufacturingOrders.push({id:m.id,manufacturingOrderId:m.id,orderId:m.order_id,manufacturerId:m.manufacturer_id,status:smMvpMfgLabel(m.status),createdAt:m.created_at,updatedAt:m.updated_at,inspection:m.inspection||{},tracking:{carrier:'',number:'',shippedAt:null,deliveredAt:null},reproductionOf:m.reproduction_of,history:m.status_history||[]})}}
 }
 if(u.role==='manufacturer'){
   const ms=await smMvpRest('sm_manufacturers?select=*&limit=1');const mf=ms?.[0];if(mf){u.manufacturerId=mf.id;SM_MVP.manufacturer=mf;const rows=await smMvpRest('sm_manufacturing_orders?select=*&order=created_at.desc');if(sc)for(const m of rows||[]){const sh=await smMvpRest(`sm_shipments?select=*&manufacturing_order_id=eq.${encodeURIComponent(m.id)}`),s=sh?.[0];if(!sc.manufacturingOrders.some(x=>x.id===m.id))sc.manufacturingOrders.push({id:m.id,manufacturingOrderId:m.id,orderId:m.order_id,manufacturerId:m.manufacturer_id,status:smMvpMfgLabel(m.status),createdAt:m.created_at,updatedAt:m.updated_at,inspection:m.inspection||{},tracking:{carrier:s?.carrier||'',number:s?.tracking_number||'',shippedAt:s?.shipped_at,deliveredAt:s?.delivered_at},reproductionOf:m.reproduction_of,history:m.status_history||[]})}}
 }
 save();
}
const smMvpBaseHydrateUser=smMvpHydrateUser;
smMvpHydrateUser=async function(){const u=await smMvpBaseHydrateUser();if(u)await smMvpHydrateOperationalCaches();return u};

/* Creator application on the same buyer account. */
const smMvpDemoSubmitCreatorApply=submitCreatorApply;
submitCreatorApply=async function(){if(!SM_MVP.live())return smMvpDemoSubmitCreatorApply();if(!$('#caShop')?.value.trim()||!$('#caBio')?.value.trim()||!$('#caAgree')?.checked)return toast('必須項目と規約同意を確認してください');try{const id=smMvpNewId('creator_application');await smMvpRest('sm_creator_applications',{method:'POST',body:JSON.stringify({id,user_id:currentUser().id,shop_name:$('#caShop').value.trim(),activity:$('#caBio').value.trim(),categories:[$('#caCat').value],portfolio_url:$('#caUrl').value.trim()||null,terms_accepted_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}});userData().creatorApplication={id,status:'pending',shop:$('#caShop').value.trim(),bio:$('#caBio').value.trim(),category:$('#caCat').value,date:now()};save();closeModal();toast('クリエイター登録を申請しました')}catch(e){toast(e.message||'申請できませんでした',3000)}};

s1AdminCreatorApplications=async function(){if(!SM_MVP.live())return; if(currentUser()?.role!=='admin')return go('home');const apps=await smMvpRest('sm_creator_applications?select=*&status=eq.pending&order=created_at.asc');adminWorkbench('クリエイター登録審査',`${apps.length?apps.map(a=>{const p=SM_MVP.adminProfiles?.find(x=>x.user_id===a.user_id);return `<article class="card panel" style="margin:9px 0"><span class="status warn">審査中</span><h3>${esc(a.shop_name)}</h3><div class="small muted">${esc(p?.display_name||a.user_id)} / ${esc((a.categories||[]).join('、'))}</div><p>${esc(a.activity)}</p><div class="btn-row"><button class="btn primary" onclick="smMvpCreatorApplicationDecision('${a.id}','approved')">承認</button><button class="btn danger" onclick="smMvpCreatorApplicationDecision('${a.id}','rejected')">差し戻し</button></div></article>`}).join(''):'<div class="empty"><h2>審査待ちはありません</h2></div>'}`,'admin-users')};
async function smMvpCreatorApplicationDecision(id,decision){try{await smMvpRpc('sm_admin_decide_creator_application',{p_application_id:id,p_decision:decision,p_note:decision==='approved'?'審査承認':'申請内容を確認してください'});await smMvpHydrateUser();render()}catch(e){toast(e.message||'審査処理に失敗しました',3000)}}

/* Real product draft + file storage, preserving the existing product management entry point. */
const smMvpDemoSellWizard=sellWizard;
sellWizard=function(){if(!SM_MVP.live())return smMvpDemoSellWizard();if(currentUser()?.role!=='creator'||!currentUser()?.creatorId)return toast('クリエイター権限が必要です');showModal(`<div class="section-head"><h2>作品を登録</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="notice"><b>公開画像と購入後データを分離して保存します。</b><br>公開画像はPNG/JPEG/WebP、納品・印刷データはPNG/JPEG/WebP/PDF/ZIPに限定します。</div><div class="field"><label>商品名</label><input id="smNewName"></div><div class="field"><label>説明</label><textarea id="smNewDesc"></textarea></div><div class="search-filter-grid"><div class="field"><label>カテゴリ</label><select id="smNewCat">${CATEGORIES.map(c=>`<option>${c[0]}</option>`).join('')}</select></div><div class="field"><label>デジタル価格</label><input id="smNewDigital" type="number" min="0" value="380"></div><div class="field"><label>物理価格</label><input id="smNewPhysical" type="number" min="0" value="980"></div><div class="field"><label>素材</label><select id="smNewMaterial"><option>耐水PET</option><option>上質紙</option><option>透明PET</option><option>ホログラム</option></select></div><div class="field"><label>サイズ</label><select id="smNewSize"><option>30mm</option><option selected>50mm</option><option>70mm</option><option>100mm</option></select></div></div><label class="chip"><input id="smNewPhysicalEnabled" type="checkbox" checked> シールとして販売</label><label class="chip"><input id="smNewRights" type="checkbox"> 権利を保有、または販売許諾を得ています</label><label class="chip"><input id="smNewAi" type="checkbox"> AIを制作に利用しました</label><div class="field"><label>商品ページ公開画像</label><input id="smNewPublic" type="file" accept="image/png,image/jpeg,image/webp"></div><div class="field"><label>購入後に渡すデータ</label><input id="smNewDigitalFile" type="file" accept="image/png,image/jpeg,image/webp,application/pdf,application/zip,.zip"></div><div class="field"><label>印刷元データ（物理販売時）</label><input id="smNewPrint" type="file" accept="image/png,image/jpeg,image/webp,application/pdf,application/zip,.zip"></div><div class="btn-row"><button class="btn" onclick="smMvpCreateProduct(false)">下書き保存</button><button class="btn primary" onclick="smMvpCreateProduct(true)">保存して審査申請</button></div>`)};
async function smMvpCreateProduct(submit){const name=$('#smNewName')?.value.trim(),desc=$('#smNewDesc')?.value.trim(),digital=Number($('#smNewDigital')?.value),physical=Number($('#smNewPhysical')?.value),sellPhysical=$('#smNewPhysicalEnabled')?.checked,rights=$('#smNewRights')?.checked;if(!name||!desc||!Number.isFinite(digital)||digital<0||!rights)return toast('商品情報と権利確認を入力してください');const pub=$('#smNewPublic')?.files?.[0],digitalFile=$('#smNewDigitalFile')?.files?.[0],printFile=$('#smNewPrint')?.files?.[0];if(!pub)return toast('商品ページ画像が必要です');if(digital>0&&!digitalFile)return toast('デジタル納品データが必要です');if(sellPhysical&&!printFile)return toast('印刷元データが必要です');busy('商品下書きを保存しています…');const id=smMvpNewId('product');try{await smMvpRest('sm_products',{method:'POST',body:JSON.stringify({id,creator_id:currentUser().creatorId,name,description:desc,category:$('#smNewCat').value,status:'draft',digital_price:digital,physical_price:sellPhysical?physical:0,material:$('#smNewMaterial').value,shape:'ダイカット',use_cases:[],tags:[],rights:{ownerDeclared:true,aiUsed:$('#smNewAi').checked},metadata:{sell_physical:!!sellPhysical,art:'type',color:'#ececec'},created_by:currentUser().id}),headers:{Prefer:'return=minimal'}});if(sellPhysical)await smMvpRest('sm_product_variants',{method:'POST',body:JSON.stringify({id:`${id}_base`,product_id:id,name:'標準',material:$('#smNewMaterial').value,size:$('#smNewSize').value,shape:'ダイカット',price:physical,active:true,metadata:{}}),headers:{Prefer:'return=minimal'}});await smMvpUploadAndRegister(pub,'sm-product-public','product_public','product',id);if(digitalFile)await smMvpUploadAndRegister(digitalFile,'sm-product-private','digital_asset','product',id);if(printFile)await smMvpUploadAndRegister(printFile,'sm-product-private','print_source','product',id);if(submit)await smMvpRpc('sm_submit_product_review',{p_product_id:id});await smMvpHydrateUser();done();closeModal();toast(submit?'審査申請しました':'下書きを保存しました');go(`work/${id}`)}catch(e){done();toast(e.message||'商品を保存できませんでした',3500)}}

const smMvpDemoSaveWorkDraft=saveWorkDraft,smMvpDemoSubmitWorkReview=submitWorkReview,smMvpDemoChangeWorkVisibility=changeWorkVisibility,smMvpDemoAdminWorkDecision=adminWorkDecision;
saveWorkDraft=async function(id,submit){if(!SM_MVP.live())return smMvpDemoSaveWorkDraft(id,submit);const p=workOwnerProduct(id);if(!p)return;const name=$('#workEditName')?.value.trim(),description=$('#workEditDesc')?.value.trim(),digital=Number($('#workEditPrice')?.value);if(!name||!description||!Number.isFinite(digital)||digital<0)return toast('商品名・説明・価格を確認してください');try{await smMvpRest(`sm_products?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({name,description,digital_price:digital,category:$('#workEditCategory').value,tags:$('#workEditTags').value.split(/[、,]/).map(x=>x.trim()).filter(Boolean),metadata:{...(p.metadata||{}),sell_physical:$('#workEditPhysical').checked}}),headers:{Prefer:'return=minimal'}});if(submit)await smMvpRpc('sm_submit_product_review',{p_product_id:id});await smMvpHydrateUser();toast(submit?'審査申請しました':'下書きを保存しました');go(`work/${id}?tab=${submit?'review':'overview'}`,{replace:true})}catch(e){toast(e.message||'商品を更新できませんでした',3200)}};
submitWorkReview=async function(id){if(!SM_MVP.live())return smMvpDemoSubmitWorkReview(id);try{await smMvpRpc('sm_submit_product_review',{p_product_id:id});await smMvpHydrateUser();toast('審査申請しました');go(`work/${id}?tab=review`,{replace:true})}catch(e){toast(e.message||'審査申請できませんでした',3200)}};
changeWorkVisibility=function(id,status){if(!SM_MVP.live())return smMvpDemoChangeWorkVisibility(id,status);confirmAction(status==='非公開'?'商品を非公開にしますか？':'公開申請しますか？','公開状態をサーバー正本で変更します。',status==='非公開'?'非公開にする':'申請する',async()=>{try{await smMvpRpc('sm_creator_set_product_visibility',{p_product_id:id,p_private:status==='非公開'});await smMvpHydrateUser();render()}catch(e){toast(e.message||'公開状態を変更できませんでした',3000)}})};
adminWorkDecision=async function(id,status){if(!SM_MVP.live())return smMvpDemoAdminWorkDecision(id,status);const note=$('#adminReviewNote')?.value.trim()||'';if(status==='差し戻し'&&!note)return toast('差し戻し理由を入力してください');try{await smMvpRpc('sm_admin_decide_product',{p_product_id:id,p_status:status==='公開中'?'published':'rejected',p_note:note});await smMvpHydrateUser();toast(status==='公開中'?'商品を承認しました':'差し戻しました');go('admin-review')}catch(e){toast(e.message||'審査処理に失敗しました',3500)}};

/* Review + private digital delivery. */
const smMvpDemoSubmitReview=submitReview,smMvpDemoDownload=downloadDemo;
submitReview=async function(id){if(!SM_MVP.live())return smMvpDemoSubmitReview(id);if(!requireAuth(`review/${id}`,'レビュー投稿にはログインが必要です。'))return;const body=$('#reviewText')?.value.trim();if(!body)return toast('レビュー本文を入力してください');const reviewId=smMvpNewId('review');try{const order=userData().orders.find(o=>o.items.some(x=>x.productId===id)&&!['pending_payment','cancelled','refunded'].includes(o.serverStatus));const item=order?.items.find(x=>x.productId===id);if(!item)throw new Error('購入済みの商品だけレビューできます');await smMvpRest('sm_reviews',{method:'POST',body:JSON.stringify({id:reviewId,product_id:id,user_id:currentUser().id,order_item_id:item.id,rating:reviewStars,title:$('#reviewTitle')?.value.trim()||null,body,photo_key:null}),headers:{Prefer:'return=minimal'}});const f=$('.review-form input[type=file]')?.files?.[0];if(f){const up=await smMvpUploadAndRegister(f,'sm-user-private','review_photo','review',reviewId);await smMvpRest(`sm_reviews?id=eq.${encodeURIComponent(reviewId)}`,{method:'PATCH',body:JSON.stringify({photo_key:up.fileId}),headers:{Prefer:'return=minimal'}})}await smMvpLoadCatalog();toast('レビューを投稿しました');go(`product/${id}`)}catch(e){toast(e.message||'レビューを投稿できませんでした',3200)}};
downloadDemo=async function(id){if(!SM_MVP.live())return smMvpDemoDownload(id);const d=userData().downloads.find(x=>x.id===id);if(!d)return;try{const r=await smMvpEdge('sm-private-file',{productId:d.productId,purpose:'digital_asset',download:true});window.location.assign(r.url)}catch(e){toast(e.message||'ダウンロードできませんでした',3200)}};

/* Notifications persist read state on server. */
const smMvpDemoOpenNotification=s1OpenNotification;
s1OpenNotification=async function(id){if(!SM_MVP.live())return smMvpDemoOpenNotification(id);const n=userData().notifications.find(x=>x.id===id);if(!n)return;try{await smMvpRest(`sm_notifications?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({read_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}});n.read=true;save();const target=s1NotificationTarget(n);if(target)go(target);else render()}catch(e){toast(e.message||'通知を更新できませんでした')}};
aReadAll=async function(){if(!SM_MVP.live()){userData().notifications.forEach(n=>n.read=true);save();return render()}try{await smMvpRest('sm_notifications?read_at=is.null',{method:'PATCH',body:JSON.stringify({read_at:new Date().toISOString()}),headers:{Prefer:'return=minimal'}});userData().notifications.forEach(n=>n.read=true);save();render()}catch(e){toast(e.message||'通知を更新できませんでした')}};

/* Fulfillment server state and PII-minimized creator order list. */
creatorOrders=function(){if(!SM_MVP.live())return;const rows=SM_MVP.creatorOrders||[];shell(`<h1>注文管理</h1><p class="muted">購入者の配送先・支払情報は表示せず、自分の商品明細だけを確認します。</p>${rows.length?rows.map(x=>`<article class="card panel" style="margin:9px 0"><div class="section-head"><div><b>${esc(productBy(x.product_id)?.name||x.product_id)}</b><div class="small muted">${esc(x.order_id)} ・ ${fmtDate(x.order_created_at)}</div></div><span class="status">${esc(smMvpOrderLabel(x.order_status))}</span></div><div class="detail-list"><div><span>数量</span><b>${x.qty}</b></div><div><span>売上</span><b>${yen(Number(x.gross))}</b></div><div><span>報酬予定</span><b>${yen(Number(x.creator_payout_amount))}</b></div></div></article>`).join(''):`<div class="empty"><div class="emoji">📦</div><h2>対象注文はありません</h2></div>`}`,{title:'注文管理',bell:true,cart:false})};
const smMvpDemoSetMfg=s1SetManufacturingStatus,smMvpDemoAssignMfg=s1AssignManufacturer,smMvpDemoSaveMfg=s1SaveManufacturingDetail,smMvpDemoPayoutStatus=s1PayoutStatus;
s1SetManufacturingStatus=async function(id,status,note=''){if(!SM_MVP.live())return smMvpDemoSetMfg(id,status,note);const internal=({'注文受付':'confirmed','製造中':'manufacturing','検品':'inspection','発送済み':'shipped','配送完了':'delivered'})[status]||status;try{await smMvpRpc('sm_set_manufacturing_status',{p_mfg_id:id,p_status:internal,p_carrier:$('#mfgCarrier')?.value.trim()||null,p_tracking:$('#mfgTracking')?.value.trim()||null});await smMvpHydrateUser();render()}catch(e){toast(e.message||'製造状態を更新できませんでした',3200)}};
s1AssignManufacturer=async function(id){if(!SM_MVP.live())return smMvpDemoAssignMfg(id);const next=$('#s1MfgAssign')?.value;if(!next)return;try{await smMvpRpc('sm_assign_manufacturer',{p_mfg_id:id,p_manufacturer_id:next});await smMvpHydrateUser();toast('製造先を更新しました');render()}catch(e){toast(e.message||'製造先を変更できませんでした')}};
s1SaveManufacturingDetail=async function(id){if(!SM_MVP.live())return smMvpDemoSaveMfg(id);const m=s1Scenario().manufacturingOrders.find(x=>x.id===id);if(!m)return;try{await smMvpRpc('sm_set_manufacturing_status',{p_mfg_id:id,p_status:({'注文受付':'confirmed','製造中':'manufacturing','検品':'inspection','発送済み':'shipped','配送完了':'delivered'})[m.status]||'confirmed',p_carrier:$('#mfgCarrier')?.value.trim()||null,p_tracking:$('#mfgTracking')?.value.trim()||null});await smMvpHydrateUser();toast('製造情報を保存しました');render()}catch(e){toast(e.message||'製造情報を保存できませんでした')}};
s1PayoutStatus=async function(id,status){if(!SM_MVP.live())return smMvpDemoPayoutStatus(id,status);const internal=({'未確定':'unconfirmed','確定':'confirmed','支払予定':'scheduled','支払済み':'paid','調整済み':'adjusted'})[status]||status;try{await smMvpRpc('sm_set_payout_status',{p_payout_id:id,p_status:internal});await smMvpHydrateUser();render()}catch(e){toast(e.message||'報酬状態を更新できませんでした')}};

/* Support/refund/reproduction. */
const smMvpDemoSupportMessage=s1SupportMessage,smMvpDemoSupportResolve=s1SupportResolve,smMvpDemoRemanufacture=s1CreateRemanufacture,smMvpDemoSupportRefund=s1SupportRefund;
s1SupportMessage=async function(id){if(!SM_MVP.live())return smMvpDemoSupportMessage(id);const t=$('#supMsg')?.value.trim();if(!t)return;try{await smMvpRpc('sm_post_support_message',{p_case_id:id,p_body:t});await smMvpHydrateUser();render()}catch(e){toast(e.message||'返信できませんでした')}};
s1SupportResolve=async function(id,status){if(!SM_MVP.live())return smMvpDemoSupportResolve(id,status);try{await smMvpRpc('sm_admin_update_support_case',{p_case_id:id,p_status:'resolved',p_resolution:status});await smMvpHydrateUser();render()}catch(e){toast(e.message||'問い合わせを更新できませんでした')}};
s1CreateRemanufacture=async function(id){if(!SM_MVP.live())return smMvpDemoRemanufacture(id);const x=s1Scenario().supportCases.find(v=>v.id===id);if(!x)return;try{await smMvpRpc('sm_admin_create_reproduction',{p_order_id:x.orderId,p_support_case_id:id});await smMvpHydrateUser();toast('再製造を手配しました');render()}catch(e){toast(e.message||'再製造を手配できませんでした')}};
s1SupportRefund=function(id){if(!SM_MVP.live())return smMvpDemoSupportRefund(id);const x=s1Scenario().supportCases.find(v=>v.id===id),o=userData().orders.find(v=>v.id===x?.orderId);if(!x||!o)return;confirmAction('返金を実行しますか？',`Stripe経由で最大 ${yen(o.total)} を返金し、報酬台帳も同一トランザクションで調整します。`,'返金する',async()=>{busy('返金を処理しています…');try{await smMvpEdge('sm-refund',{orderId:o.id,reason:x.type||'support_refund',idempotencyKey:`refund:${x.id}`});await smMvpRpc('sm_admin_update_support_case',{p_case_id:id,p_status:'resolved',p_resolution:'返金処理を開始しました'});await smMvpHydrateUser();done();toast('返金処理を受け付けました');render()}catch(e){done();toast(e.message||'返金に失敗しました',3500)}})};

/* Creator payout/admin KPI from real server aggregates. */
const smMvpDemoCreatorDashboard=creatorDashboard,smMvpDemoAdminPage=adminPage;
creatorDashboard=function(){if(!SM_MVP.live())return smMvpDemoCreatorDashboard();const u=currentUser();if(u?.role!=='creator')return go('home');const s=db.creator.sales[u.creatorId]||{month:0,last:0,count:0,favs:0,payout:0,unpaid:0};shell(`<div class="creator-dashboard-hero"><div class="small">累計売上（MVP）</div><h1 style="font-size:38px;margin:5px 0">${yen(s.month)}</h1><div>報酬未払い ${yen(s.unpaid||0)}</div></div><div class="creator-shortcuts section"><button class="card btn" onclick="go('works')">▦<br>商品管理</button><button class="card btn" onclick="go('creator-orders')">▤<br>注文管理</button><button class="card btn" onclick="go('sales')">↗<br>売上レポート</button><button class="card btn" onclick="go('payouts')">¥<br>報酬管理</button></div><section class="section"><div class="section-head"><h2>売上サマリー</h2><button class="link-btn" onclick="go('sales')">すべて見る ›</button></div><div class="kpi-grid"><button class="card kpi" onclick="go('sales')"><span>売上</span><b>${yen(s.month)}</b></button><button class="card kpi" onclick="go('sales')"><span>販売数</span><b>${s.count}</b></button><button class="card kpi" onclick="go('sales')"><span>お気に入り</span><b>${s.favs}</b></button><button class="card kpi" onclick="go('payouts')"><span>報酬</span><b>${yen(s.payout||0)}</b></button></div></section>`,{title:'クリエイターダッシュボード',bell:true,cart:false})};
adminPage=function(){if(!SM_MVP.live())return smMvpDemoAdminPage();if(currentUser()?.role!=='admin')return go('home');const k=SM_MVP.adminKpi||{};shell(`<div class="section-head"><div><h1>管理者ダッシュボード</h1><p>サーバー正本の運営KPIと業務キュー。</p></div></div><div class="admin-grid"><button class="card kpi" onclick="go('admin-users')"><span>ユーザー</span><b>${Number(k.users||0).toLocaleString()}</b></button><button class="card kpi" onclick="go('admin-orders')"><span>注文</span><b>${Number(k.orders||0).toLocaleString()}</b></button><button class="card kpi" onclick="go('admin-review')"><span>審査待ち</span><b>${Number(k.reviewing||0).toLocaleString()}</b></button><button class="card kpi" onclick="go('admin-payouts')"><span>GMV</span><b>${yen(Number(k.gmv||0))}</b></button></div><div class="kpi-grid section"><div class="card kpi"><span>未解決問い合わせ</span><b>${k.openSupport||0}</b></div><div class="card kpi"><span>製造中</span><b>${k.manufacturing||0}</b></div><div class="card kpi"><span>返金額</span><b>${yen(Number(k.refunds||0))}</b></div><div class="card kpi"><span>未払い報酬</span><b>${yen(Number(k.unpaidPayout||0))}</b></div></div><div class="btn-row"><button class="btn" onclick="go('admin-review')">商品審査</button><button class="btn" onclick="go('admin-manufacturing')">製造・発送</button><button class="btn" onclick="go('admin-support')">問い合わせ・返金</button><button class="btn" onclick="go('admin-payouts')">報酬管理</button><button class="btn" onclick="go('admin-menu')">管理メニュー</button></div>`,{title:'管理トップ',bell:true,cart:false})};

/* Fix REST signup response and switch account closure to server-side status check in live mode. */
signupDo=async function(){if(!SM_MVP.live())return smMvpDemoSignupDo();const n=$('#suName')?.value.trim(),email=$('#suEmail')?.value.trim(),password=$('#suPass')?.value;if(!n||!email||!password||!$('#suAgree')?.checked)return toast('必須項目と規約同意を確認してください');busy('登録しています…');try{const r=await smMvpAuthRequest('signup',{method:'POST',body:JSON.stringify({email,password,data:{display_name:n}})});if(r?.access_token){smMvpAuthSave(r);await smMvpHydrateUser();done();go('home',{replace:true});render()}else{done();showModal(`<div class="section-head"><h2>メールを確認してください</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p>確認メールを送信しました。メール確認後にログインしてください。</p><button class="btn primary" onclick="closeModal();go('login')">ログインへ</button>`)}}catch(e){done();toast(e.message||'登録できませんでした',2500)}};

/* Server common analytics: keep existing client analytics, add durable event stream. */
const smMvpDemoTrack=s1Track;
s1Track=function(type,data={}){smMvpDemoTrack(type,data);if(!SM_MVP.live())return;const payload={user_id:currentUser()?.id||null,session_id:sessionStorage.sm_mvp_analytics_session||(sessionStorage.sm_mvp_analytics_session=crypto.randomUUID()),event_type:type,product_id:data.productId||null,query:data.query||null,result_count:Number.isFinite(data.resultCount)?data.resultCount:null,metadata:data};smMvpRest('sm_analytics_events',{method:'POST',auth:!!currentUser(),body:JSON.stringify(payload),headers:{Prefer:'return=minimal'}}).catch(()=>{})};
