/* Sticker Market Commercial MVP — final security/operations connectors. */
async function smMvpOpenPrivateProductFile(productId,purpose){try{const r=await smMvpEdge('sm-private-file',{productId,purpose,download:true});location.assign(r.url)}catch(e){toast(e.message||'ファイルを取得できませんでした',3200)}}

/* Add real asset replacement to the existing work edit screen, without replacing the form. */
const smMvpBaseEnhanceCurrentPage=s1EnhanceCurrentPage;
s1EnhanceCurrentPage=function(){smMvpBaseEnhanceCurrentPage();if(!SM_MVP.live())return;const path=routePath(),seg=path.split('?')[0].split('/'),tab=parseQuery().tab||'overview';if(seg[0]==='work'&&seg[1]&&tab==='edit'){const p=productBy(seg[1]),form=$('#main .work-edit-form');if(p&&form&&!form.querySelector('.sm-mvp-assets')){const sec=document.createElement('section');sec.className='section card panel sm-mvp-assets';sec.innerHTML=`<h2>販売ファイル</h2><p class="muted">公開画像と購入後データは別Storageに保存されます。既存Product IDは変更しません。</p><div class="detail-list"><div><span>デジタル納品データ</span><b>${p.digitalAssetKey?'登録済み':'未登録'}</b></div><div><span>印刷元データ</span><b>${p.privatePrintKey?'登録済み':'未登録'}</b></div></div><div class="field"><label>商品ページ画像を追加</label><input id="smReplacePublic" type="file" accept="image/png,image/jpeg,image/webp"></div><div class="field"><label>デジタル納品データを差し替え</label><input id="smReplaceDigital" type="file" accept="image/png,image/jpeg,image/webp,application/pdf,application/zip,.zip"></div><div class="field"><label>印刷元データを差し替え</label><input id="smReplacePrint" type="file" accept="image/png,image/jpeg,image/webp,application/pdf,application/zip,.zip"></div><button class="btn" onclick="smMvpReplaceProductAssets('${p.id}')">ファイルを保存</button>`;form.appendChild(sec)}}};
async function smMvpReplaceProductAssets(id){const pub=$('#smReplacePublic')?.files?.[0],digital=$('#smReplaceDigital')?.files?.[0],print=$('#smReplacePrint')?.files?.[0];if(!pub&&!digital&&!print)return toast('差し替えるファイルを選択してください');busy('ファイルを検証・保存しています…');try{if(pub)await smMvpUploadAndRegister(pub,'sm-product-public','product_public','product',id);if(digital)await smMvpUploadAndRegister(digital,'sm-product-private','digital_asset','product',id);if(print)await smMvpUploadAndRegister(print,'sm-product-private','print_source','product',id);await smMvpHydrateUser();done();toast('販売ファイルを保存しました');render()}catch(e){done();toast(e.message||'ファイルを保存できませんでした',3500)}}

/* Manufacturing: least-privilege view with print source and shipping address only where necessary. */
const smMvpDemoManufacturerOrderPage=s1ManufacturerOrderPage,smMvpDemoSaveManufacturer=s1SaveManufacturerStable;
s1ManufacturerOrderPage=function(id){if(!SM_MVP.live())return smMvpDemoManufacturerOrderPage(id);const u=currentUser(),m=s1Scenario().manufacturingOrders.find(x=>x.id===id);if(!m||!(u?.role==='admin'||(u?.role==='manufacturer'&&m.manufacturerId===u.manufacturerId)))return go(roleHome(u));const o=userData().orders.find(x=>x.id===m.orderId),addr=o?.shippingAddress;const physical=o?.items?.filter(x=>x.kind==='physical')||[];shell(`<div class="section-head"><div><span class="status ${s1StatusClass(m.status)}">${esc(m.status)}</span><h1>${esc(m.orderId)}</h1><p>製造注文 ${esc(m.id)}</p></div></div><div class="card panel"><h2>印刷仕様</h2>${physical.map(x=>{const p=productBy(x.productId);return `<div class="s1-inline-row"><span><b>${esc(p?.name||x.productId)}</b><div class="small muted">${esc(x.material||p?.material||'')} / ${esc(x.size||p?.size||'50mm')} / ${esc(x.shape||p?.shape||'')}</div></span><div><b>${x.qty}枚</b><button class="btn" onclick="smMvpOpenPrivateProductFile('${x.productId}','print_source')">印刷元データ</button></div></div>`}).join('')||'<p>物理商品なし</p>'}</div>${addr?`<section class="section card panel"><h2>発送先</h2><b>${esc(addr.name||'')}</b><div>〒${esc(addr.postal_code||'')}<br>${esc([addr.address1,addr.address2].filter(Boolean).join(' '))}<br>${esc(addr.phone||'')}</div><div class="small muted">製造・発送業務に必要な配送先だけを表示しています。購入履歴・支払情報・報酬情報は表示しません。</div></section>`:''}<section class="section card panel"><h2>工程更新</h2><div class="btn-row">${S1_MFG_FLOW.map(s=>`<button class="btn ${m.status===s?'primary':''}" onclick="s1SetManufacturingStatus('${m.id}','${s}')">${s}</button>`).join('')}</div><div class="search-filter-grid"><div class="field"><label>配送会社</label><input id="mfgCarrier" value="${esc(m.tracking?.carrier||'')}"></div><div class="field"><label>追跡番号</label><input id="mfgTracking" value="${esc(m.tracking?.number||'')}"></div></div><button class="btn primary" onclick="s1SaveManufacturingDetail('${m.id}')">製造・配送情報を保存</button></section>${u.role==='admin'?`<section class="section card panel s1-mfg-assignment"><h2>製造先割当</h2><select id="s1MfgAssign">${s1Scenario().manufacturers.filter(x=>x.active).map(x=>`<option value="${x.id}" ${x.id===m.manufacturerId?'selected':''}>${esc(x.name)}</option>`).join('')}</select><button class="btn primary" onclick="s1AssignManufacturer('${m.id}')">割当を更新</button></section>`:''}`,{title:'製造注文詳細',back:true,bell:true,cart:false})};
s1SaveManufacturerStable=async function(id){if(!SM_MVP.live())return smMvpDemoSaveManufacturer(id);const body={id:id||smMvpNewId('manufacturer'),name:$('#mfName').value.trim(),supported_materials:$('#mfMaterials').value.split(',').map(x=>x.trim()).filter(Boolean),supported_sizes:$('#mfSizes').value.split(',').map(x=>x.trim()).filter(Boolean),base_cost:Number($('#mfCost').value),lead_days:Number($('#mfLead').value),active:$('#mfActive').checked,defect_rate:Number($('#mfDefect').value||0),on_time_rate:Number($('#mfOnTime').value||100),metadata:{mode:'manual',api:false}};if(!body.name)return toast('会社名を入力してください');try{if(id)await smMvpRest(`sm_manufacturers?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify(body),headers:{Prefer:'return=minimal'}});else await smMvpRest('sm_manufacturers',{method:'POST',body:JSON.stringify(body),headers:{Prefer:'return=minimal'}});await smMvpHydrateUser();closeModal();render()}catch(e){toast(e.message||'製造事業者を保存できませんでした')}};

/* Moderation and rights decisions update the server records. */
const smMvpDemoModerationAction=s1ModerationAction,smMvpDemoRightsDecision=s1RightsDecision;
s1ModerationAction=async function(id,status){if(!SM_MVP.live())return smMvpDemoModerationAction(id,status);const r=s1Scenario().reports.find(x=>x.id===id);if(!r)return;const next=status==='非表示'?'investigating':'resolved';try{await smMvpRest(`sm_reports?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status:next}),headers:{Prefer:'return=minimal'}});if(status==='非表示'&&r.targetType==='product')await smMvpRpc('sm_admin_decide_product',{p_product_id:r.targetId,p_status:'suspended',p_note:`通報 ${id} の調査により一時停止`});await smMvpHydrateUser();render()}catch(e){toast(e.message||'通報処理を更新できませんでした')}};
s1RightsDecision=async function(id,status){if(!SM_MVP.live())return smMvpDemoRightsDecision(id,status);const x=s1Scenario().rightsCases.find(v=>v.id===id);if(!x)return;try{await smMvpRest(`sm_rights_cases?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({status:status==='承認'?'resolved':'rejected'}),headers:{Prefer:'return=minimal'}});if(status==='承認')await smMvpRpc('sm_admin_decide_product',{p_product_id:x.productId,p_status:'reviewing',p_note:'異議申立てを承認。再審査へ移行'});await smMvpHydrateUser();render()}catch(e){toast(e.message||'異議申立てを更新できませんでした')}};

/* Server audit log replaces the static rows in live modes. */
const smMvpDemoAuditPage=auditPage;
auditPage=async function(){if(!SM_MVP.live())return smMvpDemoAuditPage();if(currentUser()?.role!=='admin')return go('home');const rows=await smMvpRest('sm_audit_logs?select=*&order=created_at.desc&limit=100');adminWorkbench('監査ログ',`<div class="notice">サーバー側の追記専用監査記録です。UIから削除しません。</div><div class="table-wrap" style="margin-top:12px"><table class="table"><thead><tr><th>いつ</th><th>誰が</th><th>操作</th><th>対象</th><th>変更前</th><th>変更後</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(s1Date(r.created_at))}</td><td>${esc(r.actor_user_id||'system')}</td><td>${esc(r.action)}</td><td>${esc(r.target_type)} ${esc(r.target_id||'')}</td><td><code>${esc(JSON.stringify(r.before_data||{}))}</code></td><td><code>${esc(JSON.stringify(r.after_data||{}))}</code></td></tr>`).join('')}</tbody></table></div>`,'admin-audit')};

/* Closed/restricted users are rejected immediately after server profile hydration. */
const smMvpFinalHydrateUser=smMvpHydrateUser;
smMvpHydrateUser=async function(){const u=await smMvpFinalHydrateUser();if(u&&SM_MVP.profile?.status!=='active'){smMvpAuthSave(null);db.session.userId=null;save();throw new Error('このアカウントは現在利用できません')}return u};

/* Live mode banner makes environment explicit without changing the existing layout. */
const smMvpFinalShell=shell;
shell=function(content,opts={}){smMvpFinalShell(content,opts);if(SM_MVP.live()&&!$('#main .sm-mvp-env')){const b=document.createElement('div');b.className=`notice sm-mvp-env ${SM_MVP.mode==='PRODUCTION'?'':'demo'}`;b.innerHTML=`<b>${SM_MVP.mode}</b> — 注文・商品・権限・製造・返金・報酬はサーバー正本。AI等のMVP対象外機能は引き続きデモ表示です。`;$('#main')?.prepend(b)}};
