/* Sticker Market Commercial MVP — backend/auth/catalog/state adapter.
 * Additive layer. DEMO keeps all existing local behavior. STAGING/PRODUCTION use Supabase as source of truth.
 */
const SM_MVP_CONFIG={
 supabaseUrl:'https://oodalamuvycoajdrdszi.supabase.co',
 anonKey:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZGFsYW11dnljb2FqZHJkc3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NDM3NjMsImV4cCI6MjA2MzExOTc2M30.dZ9xi9WOGauVOR9aCmOYEGE2nagXCx6XitYZSai-BdQ',
 authStorageKey:'sm_mvp_auth_v1',modeStorageKey:'sm_mvp_mode',stripePkStorageKey:'sm_stripe_pk',checkoutKey:'sm_mvp_checkout_key'
};
const SM_MVP={mode:'DEMO',auth:null,profile:null,capabilities:[],creator:null,cartId:null,checkout:null,paymentMethod:null,initializing:false,ready:false};
(function(){const q=new URLSearchParams(location.search).get('sm_mode');const saved=localStorage.getItem(SM_MVP_CONFIG.modeStorageKey);const m=String(q||saved||'DEMO').toUpperCase();SM_MVP.mode=['DEMO','STAGING','PRODUCTION'].includes(m)?m:'DEMO';if(q)localStorage.setItem(SM_MVP_CONFIG.modeStorageKey,SM_MVP.mode)})();
SM_MVP.live=()=>SM_MVP.mode!=='DEMO';
function smMvpSetMode(mode){mode=String(mode||'').toUpperCase();if(!['DEMO','STAGING','PRODUCTION'].includes(mode))return;localStorage.setItem(SM_MVP_CONFIG.modeStorageKey,mode);location.reload()}
function smMvpAuthLoad(){try{return JSON.parse(localStorage.getItem(SM_MVP_CONFIG.authStorageKey)||'null')}catch{return null}}
function smMvpAuthSave(v){SM_MVP.auth=v;if(v)localStorage.setItem(SM_MVP_CONFIG.authStorageKey,JSON.stringify(v));else localStorage.removeItem(SM_MVP_CONFIG.authStorageKey)}
function smMvpHeaders(auth=false,extra={}){const h={apikey:SM_MVP_CONFIG.anonKey,...extra};if(auth&&SM_MVP.auth?.access_token)h.Authorization=`Bearer ${SM_MVP.auth.access_token}`;return h}
async function smMvpJson(res){const txt=await res.text();let data=null;try{data=txt?JSON.parse(txt):null}catch{data=txt}if(!res.ok){const e=new Error(data?.message||data?.msg||data?.error_description||data?.error||`HTTP ${res.status}`);e.status=res.status;e.data=data;throw e}return data}
async function smMvpAuthRequest(path,opts={}){return smMvpJson(await fetch(`${SM_MVP_CONFIG.supabaseUrl}/auth/v1/${path}`,{...opts,headers:{...smMvpHeaders(false,{'Content-Type':'application/json'}),...(opts.headers||{})}}))}
async function smMvpRefresh(){const s=SM_MVP.auth||smMvpAuthLoad();if(!s?.refresh_token)return false;try{const d=await smMvpAuthRequest('token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token})});smMvpAuthSave(d);return true}catch{smMvpAuthSave(null);return false}}
async function smMvpRest(path,opts={}){let res=await fetch(`${SM_MVP_CONFIG.supabaseUrl}/rest/v1/${path}`,{...opts,headers:{...smMvpHeaders(opts.auth!==false,{'Content-Type':'application/json'}),...(opts.headers||{})}});if(res.status===401&&opts.auth!==false&&await smMvpRefresh())res=await fetch(`${SM_MVP_CONFIG.supabaseUrl}/rest/v1/${path}`,{...opts,headers:{...smMvpHeaders(true,{'Content-Type':'application/json'}),...(opts.headers||{})}});return smMvpJson(res)}
async function smMvpRpc(name,args={},auth=true){return smMvpRest(`rpc/${name}`,{method:'POST',auth,body:JSON.stringify(args)})}
async function smMvpEdge(name,body){let res=await fetch(`${SM_MVP_CONFIG.supabaseUrl}/functions/v1/${name}`,{method:'POST',headers:smMvpHeaders(true,{'Content-Type':'application/json'}),body:JSON.stringify(body)});if(res.status===401&&await smMvpRefresh())res=await fetch(`${SM_MVP_CONFIG.supabaseUrl}/functions/v1/${name}`,{method:'POST',headers:smMvpHeaders(true,{'Content-Type':'application/json'}),body:JSON.stringify(body)});return smMvpJson(res)}
function smMvpNewId(prefix){return `${prefix}_${crypto.randomUUID().replaceAll('-','').slice(0,20)}`}
function smMvpClearCheckout(){SM_MVP.checkout=null;SM_MVP.paymentMethod=null;sessionStorage.removeItem(SM_MVP_CONFIG.checkoutKey);sessionStorage.removeItem('sm_mvp_payment_method')}
function smMvpPrimaryRole(caps){return caps.includes('admin')?'admin':caps.includes('manufacturer')?'manufacturer':caps.includes('creator')?'creator':'buyer'}
function smMvpOrderLabel(s){return({pending_payment:'支払い待ち',paid:'支払済み',confirmed:'注文確定',manufacturing:'製造中',inspection:'検品中',shipped:'発送済み',delivered:'配送完了',cancelled:'キャンセル',refunded:'返金済み'})[s]||s}
function smMvpMfgLabel(s){return({confirmed:'注文受付',manufacturing:'製造中',inspection:'検品',ready_to_ship:'検品',shipped:'発送済み',delivered:'配送完了',unable:'製造不能',cancelled:'キャンセル'})[s]||s}
function smMvpPayoutLabel(s){return({unconfirmed:'未確定',confirmed:'確定',scheduled:'支払予定',paid:'支払済み',adjusted:'調整済み'})[s]||s}

async function smMvpLoadCatalog(){
 const [ps,cs,vs,rs]=await Promise.all([
  smMvpRest('sm_products?select=*&status=eq.published&order=created_at.desc',{auth:false}),
  smMvpRest('sm_creators?select=*&status=eq.active&order=created_at.asc',{auth:false}),
  smMvpRest('sm_product_variants?select=*&active=eq.true',{auth:false}),
  smMvpRest('sm_reviews?select=*&hidden=eq.false&order=created_at.desc&limit=200',{auth:false})
 ]);
 const oldProducts=new Map(products.map(p=>[p.id,{...p}]));const vmap=new Map();(vs||[]).forEach(v=>{if(!vmap.has(v.product_id))vmap.set(v.product_id,v)});
 const mapped=(ps||[]).map(p=>{const old=oldProducts.get(p.id)||{},v=vmap.get(p.id);return {...old,id:p.id,name:p.name,creatorId:p.creator_id,category:p.category,digital:Number(p.digital_price),physical:Number(p.physical_price),material:p.material||old.material||'',shape:p.shape||old.shape||'',size:v?.size||old.size||'50mm',variantId:v?.id||null,useCases:p.use_cases||[],tags:p.tags||[],description:p.description||'',art:p.metadata?.art||old.art||'type',color:p.metadata?.color||old.color||'#ececec',updated:p.updated_at||p.created_at,rating:old.rating||0,favs:old.favs||0,sales:old.sales||0,views:old.views||0,digitalAssetKey:p.digital_asset_key||null,privatePrintKey:p.private_print_key||null,publicMedia:p.public_media||[],serverStatus:p.status,rights:p.rights||{},metadata:p.metadata||{}}});
 products.splice(0,products.length,...mapped);
 const oldCreators=new Map(CREATORS.map(c=>[c.id,{...c}]));const cm=(cs||[]).map(c=>{const old=oldCreators.get(c.id)||{};return {...old,id:c.id,shopId:old.shopId||`shop_${c.id}`,name:c.shop_name,genre:c.metadata?.genre||old.genre||'',followers:old.followers||0,rating:old.rating||0,sales:old.sales||0,avatar:old.avatar||String(c.shop_name||'?').slice(0,1).toUpperCase(),verified:c.metadata?.verified??old.verified??false,bio:c.bio||'',accent:old.accent||'#7658d5',userId:c.user_id||null}});CREATORS.splice(0,CREATORS.length,...cm);
 db.global.reviews=(rs||[]).map(r=>({id:r.id,productId:r.product_id,userId:r.user_id,rating:r.rating,title:r.title||'',text:r.body,date:r.created_at,kind:'physical',verified:r.verified,helpful:0,photoKey:r.photo_key||null}));
}
async function smMvpGetAuthUser(){if(!SM_MVP.auth?.access_token)return null;try{return await smMvpAuthRequest('user',{headers:{Authorization:`Bearer ${SM_MVP.auth.access_token}`}})}catch(e){if(e.status===401&&await smMvpRefresh())return smMvpAuthRequest('user',{headers:{Authorization:`Bearer ${SM_MVP.auth.access_token}`}});throw e}}
async function smMvpHydrateCart(d){const carts=await smMvpRest('sm_carts?select=id&limit=1');SM_MVP.cartId=carts?.[0]?.id||null;if(!SM_MVP.cartId){d.cart=[];return}const rows=await smMvpRest(`sm_cart_items?select=*&cart_id=eq.${encodeURIComponent(SM_MVP.cartId)}&order=created_at.asc`);d.cart=(rows||[]).map(x=>{const p=productBy(x.product_id);return{id:x.id,cartItemId:x.id,productId:x.product_id,kind:x.kind,qty:Number(x.qty),license:x.license,material:x.options?.material||p.material,size:x.options?.size||p.size||'50mm',shape:x.options?.shape||p.shape,price:x.kind==='digital'?p.digital:(x.variant_id===p.variantId?p.physical:p.physical),variantId:x.variant_id,options:x.options||{}}})}
async function smMvpHydrateAddresses(d){const rows=await smMvpRest('sm_addresses?select=*&order=is_default.desc,created_at.asc');d.addresses=(rows||[]).map(a=>({id:a.id,name:a.name,zip:a.postal_code,address:[a.address1,a.address2].filter(Boolean).join(' '),address1:a.address1,address2:a.address2||'',phone:a.phone,default:a.is_default}))}
async function smMvpHydrateOrders(d){const rows=await smMvpRest('sm_orders?select=*&order=created_at.desc&limit=100');const result=[];for(const o of rows||[]){const items=await smMvpRest(`sm_order_items?select=*&order_id=eq.${encodeURIComponent(o.id)}&order=created_at.asc`);result.push({id:o.id,orderId:o.id,userId:o.user_id,date:o.created_at,items:(items||[]).map(x=>{const p=productBy(x.product_id);return{id:x.id,productId:x.product_id,kind:x.kind,qty:Number(x.qty),price:Number(x.unit_price),license:x.license,material:x.options?.material||p.material,size:x.options?.size||p.size||'50mm',shape:x.options?.shape||p.shape,creatorId:x.creator_id,variantId:x.variant_id}}),shipping:Number(o.shipping),tax:Number(o.tax),discount:Number(o.discount),subtotal:Number(o.subtotal),total:Number(o.total),status:smMvpOrderLabel(o.status),serverStatus:o.status,statusHistory:o.status_history||[],paymentId:o.payment_id,shippingAddress:o.shipping_address})}d.orders=result;
 const ids=result.map(x=>x.id);if(ids.length&&typeof s1Scenario==='function'){const mfg=[];for(const id of ids){const ms=await smMvpRest(`sm_manufacturing_orders?select=*&order_id=eq.${encodeURIComponent(id)}`);for(const m of ms||[]){const sh=await smMvpRest(`sm_shipments?select=*&manufacturing_order_id=eq.${encodeURIComponent(m.id)}`);const s=sh?.[0];mfg.push({id:m.id,manufacturingOrderId:m.id,orderId:m.order_id,manufacturerId:m.manufacturer_id,status:smMvpMfgLabel(m.status),createdAt:m.created_at,updatedAt:m.updated_at,inspection:m.inspection||{},tracking:{carrier:s?.carrier||'',number:s?.tracking_number||'',shippedAt:s?.shipped_at||null,deliveredAt:s?.delivered_at||null},reproductionOf:m.reproduction_of,history:m.status_history||[]})}}s1Scenario().manufacturingOrders=mfg}
 d.downloads=[];for(const o of result){if(['pending_payment','cancelled','refunded'].includes(o.serverStatus))continue;for(const x of o.items.filter(i=>i.kind==='digital'))d.downloads.push({id:`download_${x.id}`,productId:x.productId,date:String(o.date).slice(0,10),expires:null,count:0,size:'—',license:x.license||'personal',updated:false,server:true,orderId:o.id})}
}
async function smMvpHydrateNotifications(d){const rows=await smMvpRest('sm_notifications?select=*&order=created_at.desc&limit=100');d.notifications=(rows||[]).map(n=>({id:n.id,type:n.type,text:[n.title,n.body].filter(Boolean).join('：'),title:n.title,body:n.body,ref:n.ref||{},read:!!n.read_at,date:n.created_at}))}
async function smMvpHydrateUser(){const au=await smMvpGetAuthUser();if(!au){db.session.userId=null;save();return null}const [profiles,caps,creatorRows]=await Promise.all([smMvpRest(`sm_user_profiles?select=*&user_id=eq.${au.id}`),smMvpRest(`sm_user_capabilities?select=capability&user_id=eq.${au.id}`),smMvpRest(`sm_creators?select=*&user_id=eq.${au.id}`)]);const profile=profiles?.[0],capabilities=(caps||[]).map(x=>x.capability),creator=creatorRows?.[0]||null;SM_MVP.profile=profile;SM_MVP.capabilities=capabilities;SM_MVP.creator=creator;let u=db.users.find(x=>x.id===au.id);const role=smMvpPrimaryRole(capabilities);const val={id:au.id,role,name:profile?.display_name||au.email||'User',email:profile?.email||au.email||'',points:0,creatorId:creator?.id||null,capabilities};if(u)Object.assign(u,val);else db.users.push(u=val);db.session.userId=u.id;const old=db.userData[u.id],settings=old?.settings||baseUserData().settings;db.userData[u.id]={...baseUserData(),settings,cart:[],favorites:[],orders:[],downloads:[],follows:[],reviews:[],messages:[],proposals:[],notifications:[],addresses:[]};const d=db.userData[u.id];const [favs,follows]=await Promise.all([smMvpRest('sm_favorites?select=product_id'),smMvpRest('sm_follows?select=creator_id')]);d.favorites=(favs||[]).map(x=>x.product_id);d.follows=(follows||[]).map(x=>x.creator_id);await Promise.all([smMvpHydrateCart(d),smMvpHydrateAddresses(d),smMvpHydrateOrders(d),smMvpHydrateNotifications(d)]);if(creator){const payouts=await smMvpRest(`sm_creator_payouts?select=*&creator_id=eq.${encodeURIComponent(creator.id)}&order=created_at.desc`);if(typeof s1Scenario==='function')s1Scenario().payouts=(payouts||[]).map(p=>({...p,creatorId:p.creator_id,orderId:p.order_id,productId:null,gross:Number(p.gross),cost:Number(p.manufacturing_cost),fee:Number(p.platform_fee),amount:Number(p.amount),status:smMvpPayoutLabel(p.status),updatedAt:p.updated_at}))}save();return u}
async function smMvpInit(){if(!SM_MVP.live()||SM_MVP.initializing)return;SM_MVP.initializing=true;try{SM_MVP.auth=smMvpAuthLoad();db.session.userId=null;await smMvpLoadCatalog();if(SM_MVP.auth)try{await smMvpHydrateUser()}catch(e){console.warn('MVP session hydrate failed',e);smMvpAuthSave(null);db.session.userId=null}SM_MVP.ready=true;save();render()}catch(e){console.error('Commercial MVP init failed',e);toast('商用MVP接続を初期化できませんでした',2500)}finally{SM_MVP.initializing=false}}

const smMvpDemoLoginPage=loginPage,smMvpDemoLoginDo=loginDo,smMvpDemoSignupDo=signupDo,smMvpDemoLogoutConfirm=logoutConfirm,smMvpDemoToggleFav=toggleFav,smMvpDemoFollowCreator=followCreator,smMvpDemoAddCart=addCart,smMvpDemoCartQty=cartQty,smMvpDemoRemoveCart=removeCart,smMvpDemoSaveLater=saveLater,smMvpDemoSaveAddress=saveAddress,smMvpDemoSelectAddress=selectAddress,smMvpDemoAccountModal=accountModal,smMvpDemoLegal=legal,smMvpDemoLegalFooter=legalFooter;
loginPage=function(){if(!SM_MVP.live())return smMvpDemoLoginPage();shell(`<div style="max-width:480px;margin:auto"><h1>ログイン</h1><p class="muted">Supabase Authによる本番認証です。</p><div class="field"><label>メールアドレス</label><input id="loginEmail" type="email" autocomplete="email"></div><div class="field"><label>パスワード</label><input id="loginPass" type="password" autocomplete="current-password"></div><button class="btn primary full" onclick="loginDo()">ログイン</button><p style="text-align:center">アカウントをお持ちでない方 <button class="link-btn" onclick="go('signup')">無料で新規登録</button></p></div>`,{title:'ログイン',back:true,noNav:true,cart:false})};
loginDo=async function(){if(!SM_MVP.live())return smMvpDemoLoginDo();const email=$('#loginEmail')?.value.trim(),password=$('#loginPass')?.value;if(!email||!password)return toast('メールアドレスとパスワードを入力してください');busy('ログインしています…');try{const s=await smMvpAuthRequest('token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});smMvpAuthSave(s);await smMvpHydrateUser();const a=sessionStorage.getItem('sm20_after');sessionStorage.removeItem('sm20_after');done();go(a||roleHome(currentUser()),{replace:true});render()}catch(e){done();toast(e.message||'ログインできませんでした',2500)}};
signupDo=async function(){if(!SM_MVP.live())return smMvpDemoSignupDo();const n=$('#suName')?.value.trim(),email=$('#suEmail')?.value.trim(),password=$('#suPass')?.value;if(!n||!email||!password||!$('#suAgree')?.checked)return toast('必須項目と規約同意を確認してください');busy('登録しています…');try{const r=await smMvpAuthRequest('signup',{method:'POST',body:JSON.stringify({email,password,data:{display_name:n}})});if(r?.session){smMvpAuthSave(r.session);await smMvpHydrateUser();done();go('home',{replace:true});render()}else{done();showModal(`<div class="section-head"><h2>メールを確認してください</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p>確認メールを送信しました。メール確認後にログインしてください。</p><button class="btn primary" onclick="closeModal();go('login')">ログインへ</button>`)}}catch(e){done();toast(e.message||'登録できませんでした',2500)}};
logoutConfirm=function(){if(!SM_MVP.live())return smMvpDemoLogoutConfirm();confirmAction('ログアウトしますか？','現在のセッションを終了してLPへ戻ります。','ログアウト',async()=>{try{if(SM_MVP.auth?.access_token)await fetch(`${SM_MVP_CONFIG.supabaseUrl}/auth/v1/logout`,{method:'POST',headers:smMvpHeaders(true)})}catch{}smMvpAuthSave(null);SM_MVP.profile=null;SM_MVP.capabilities=[];SM_MVP.creator=null;db.session.userId=null;save();history.replaceState({},'','#/landing');render()})};

toggleFav=async function(id){if(!SM_MVP.live())return smMvpDemoToggleFav(id);if(!requireAuth(`product/${id}`,'お気に入りを保存するにはログインが必要です。'))return;const d=userData(),has=d.favorites.includes(id);try{if(has)await smMvpRest(`sm_favorites?product_id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});else await smMvpRest('sm_favorites',{method:'POST',body:JSON.stringify({user_id:currentUser().id,product_id:id}),headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});d.favorites=has?d.favorites.filter(x=>x!==id):[...d.favorites,id];save();render()}catch(e){toast(e.message||'お気に入りを更新できませんでした')}};
followCreator=async function(id,e){if(!SM_MVP.live())return smMvpDemoFollowCreator(id,e);e?.stopPropagation();if(!requireAuth(`creator/${id}`,'クリエイターをフォローするにはログインが必要です。'))return;const d=userData(),has=d.follows.includes(id);try{if(has)await smMvpRest(`sm_follows?creator_id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});else await smMvpRest('sm_follows',{method:'POST',body:JSON.stringify({user_id:currentUser().id,creator_id:id}),headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});d.follows=has?d.follows.filter(x=>x!==id):[...d.follows,id];save();toast(has?'フォローを解除しました':'フォローしました');render()}catch(err){toast(err.message||'フォローを更新できませんでした')}};
addCart=async function(id,kind,opt={}){if(!SM_MVP.live())return smMvpDemoAddCart(id,kind,opt);if(!requireAuth(`product/${id}`,'カートに追加するにはログインが必要です。'))return;const p=productBy(id);if(kind==='digital'&&!p.digitalAssetKey)return toast('この商品のデジタル納品データは本番販売準備中です',2600);if(kind==='physical'&&!p.privatePrintKey)return toast('この商品の印刷元データは本番販売準備中です',2600);try{if(!SM_MVP.cartId)await smMvpHydrateCart(userData());const options={material:opt.material||p.material,size:opt.size||p.size||'50mm',shape:opt.shape||p.shape,...(opt.options||{})};await smMvpRest('sm_cart_items',{method:'POST',body:JSON.stringify({cart_id:SM_MVP.cartId,product_id:id,variant_id:kind==='physical'?(opt.variantId||p.variantId||null):null,kind,qty:opt.qty||1,license:opt.license||null,options}),headers:{Prefer:'return=minimal'}});smMvpClearCheckout();await smMvpHydrateCart(userData());save();toast('カートに追加しました');setTimeout(()=>go('cart'),300)}catch(e){toast(e.message||'カートに追加できませんでした',2600)}};
cartQty=async function(id,diff){if(!SM_MVP.live())return smMvpDemoCartQty(id,diff);const x=userData().cart.find(x=>x.id===id);if(!x)return;const qty=Math.max(1,x.qty+diff);try{await smMvpRest(`sm_cart_items?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({qty}),headers:{Prefer:'return=minimal'}});smMvpClearCheckout();x.qty=qty;save();render()}catch(e){toast(e.message||'数量を更新できませんでした')}};
removeCart=function(id){if(!SM_MVP.live())return smMvpDemoRemoveCart(id);confirmAction('カートから削除','この商品をカートから削除します。','削除',async()=>{try{await smMvpRest(`sm_cart_items?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});smMvpClearCheckout();await smMvpHydrateCart(userData());save();render()}catch(e){toast(e.message||'削除できませんでした')}})};
saveLater=async function(id){if(!SM_MVP.live())return smMvpDemoSaveLater(id);const x=userData().cart.find(x=>x.id===id);if(!x)return;if(!userData().favorites.includes(x.productId))await toggleFav(x.productId);try{await smMvpRest(`sm_cart_items?id=eq.${encodeURIComponent(id)}`,{method:'DELETE',headers:{Prefer:'return=minimal'}});smMvpClearCheckout();await smMvpHydrateCart(userData());save();toast('お気に入りへ移動しました');render()}catch(e){toast(e.message||'移動できませんでした')}};
saveAddress=async function(){if(!SM_MVP.live())return smMvpDemoSaveAddress();const name=$('#an')?.value.trim(),zip=$('#az')?.value.trim(),address=$('#aa')?.value.trim(),phone=$('#ap')?.value.trim();if(!name||!zip||!address||!phone)return toast('配送先をすべて入力してください');try{await smMvpRest('sm_addresses',{method:'POST',body:JSON.stringify({user_id:currentUser().id,name,postal_code:zip,address1:address,address2:'',phone,is_default:userData().addresses.length===0}),headers:{Prefer:'return=minimal'}});smMvpClearCheckout();await smMvpHydrateAddresses(userData());save();closeModal();render()}catch(e){toast(e.message||'配送先を保存できませんでした')}};
selectAddress=async function(id){if(!SM_MVP.live())return smMvpDemoSelectAddress(id);try{await smMvpRpc('sm_set_default_address',{p_address_id:id});smMvpClearCheckout();await smMvpHydrateAddresses(userData());save();render()}catch(e){toast(e.message||'配送先を変更できませんでした')}};
accountModal=function(){if(!SM_MVP.live())return smMvpDemoAccountModal();const u=currentUser();showModal(`<div class="section-head"><h2>プロフィール</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>表示名</label><input id="profileName" value="${esc(u.name)}"></div><div class="field"><label>メール</label><input value="${esc(u.email)}" disabled></div><button class="btn primary" onclick="smMvpUpdateProfile()">変更する</button>`)};
async function smMvpUpdateProfile(){const name=$('#profileName')?.value.trim();if(!name)return;try{await smMvpRest(`sm_user_profiles?user_id=eq.${currentUser().id}`,{method:'PATCH',body:JSON.stringify({display_name:name}),headers:{Prefer:'return=minimal'}});currentUser().name=name;save();closeModal();render()}catch(e){toast(e.message||'プロフィールを更新できませんでした')}}
legalFooter=function(){const html=smMvpDemoLegalFooter();if(!SM_MVP.live())return html;return html.replace('PUBLIC DEMO',SM_MVP.mode)};
legal=async function(k){if(!SM_MVP.live())return smMvpDemoLegal(k);const titles={terms:'利用規約',privacy:'プライバシーポリシー',security:'セキュリティポリシー',commerce:'特定商取引法に基づく表記',refund:'返品・返金ポリシー',ip:'著作権・知的財産ポリシー',ai:'AI生成作品ポリシー',community:'コミュニティガイドライン',contact:'問い合わせ',about:'運営情報'};showModal(`<div class="section-head"><h2>${titles[k]||k}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p class="muted">読み込み中…</p>`);try{const rows=await smMvpRest(`sm_legal_documents?select=*&key=eq.${encodeURIComponent(k)}&status=eq.published`,{auth:false});const d=rows?.[0];showModal(`<div class="section-head"><h2>${esc(d?.title||titles[k]||k)}</h2><button class="icon-btn" onclick="closeModal()">×</button></div>${d?`<div class="legal-document">${esc(d.body).replace(/\n/g,'<br>')}</div><p class="small muted">Version ${esc(d.version)}</p>`:`<div class="notice demo">正式文書はまだ公開されていません。PRODUCTION公開前の必須設定です。</div>`}`)}catch(e){showModal(`<div class="section-head"><h2>${titles[k]||k}</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="notice danger">法務文書を取得できませんでした。</div>`)}};

setTimeout(()=>smMvpInit(),0);
