/* Sticker Market scenario-fit patch v1.0 — market circulation and buyer flows. */

function s1SearchParams(){return new URLSearchParams(routePath().split('?')[1]||'')}
function s1SearchUrl(sp){const q=sp.toString();return 'search'+(q?'?'+q:'')}
function s1SetSearch(k,v){const sp=s1SearchParams();if(v)sp.set(k,v);else sp.delete(k);sp.set('page','1');go(s1SearchUrl(sp))}
function s1RelaxSearch(){const sp=s1SearchParams();['material','shape','size','use','min','max','excludeAi'].forEach(k=>sp.delete(k));sp.set('page','1');go(s1SearchUrl(sp))}
function s1TrackSearchOnce(key,count){const k=`s1_search_${key}_${count}`;if(sessionStorage.getItem(k))return;sessionStorage.setItem(k,'1');s1Track('search',{query:key,resultCount:count})}

/* D-01 / D-07: preserve existing search and extend only with use-case and zero-result actions. */
searchPage=function(){
 const sp=s1SearchParams(),keyword=sp.get('q')||'',cat=sp.get('category')||'',material=sp.get('material')||'',shape=sp.get('shape')||'',size=sp.get('size')||'',useCase=sp.get('use')||'',min=Number(sp.get('min')||0),max=Number(sp.get('max')||5000),excludeAi=sp.get('excludeAi')==='1',sort=sp.get('sort')||'relevance';
 const savedCols=currentUser()?Number(userData()?.settings?.columns||2):Number(localStorage.getItem('sm20_guest_cols')||2),cols=clamp(savedCols,1,3);
 let list=products.filter(p=>!p.hidden).map(p=>[p,score(p,keyword)]).filter(([p,s])=>(!keyword||s>0)&&(!cat||p.category===cat)&&(!material||p.material===material)&&(!shape||p.shape===shape)&&(!size||p.size===size)&&(!useCase||(p.useCases||[]).includes(useCase))&&p.digital>=min&&p.digital<=max&&(!excludeAi||!p.aiGenerated));
 if(sort==='popular')list.sort((a,b)=>b[0].sales-a[0].sales);else if(sort==='rating')list.sort((a,b)=>b[0].rating-a[0].rating);else if(sort==='new')list.sort((a,b)=>String(b[0].updated).localeCompare(String(a[0].updated)));else list.sort((a,b)=>b[1]-a[1]);
 list=list.map(x=>x[0]);s1TrackSearchOnce([keyword,cat,material,shape,size,useCase,min,max,excludeAi,sort].join('|'),list.length);
 const pageSize=Number(sp.get('pageSize')||6),pages=Math.max(1,Math.ceil(list.length/pageSize)),page=clamp(Number(sp.get('page')||1),1,pages),shown=list.slice((page-1)*pageSize,page*pageSize);
 const chips=[['q',keyword],['category',cat],['material',material],['shape',shape],['size',size],['use',useCase],['excludeAi',excludeAi?'AI生成除外':'']].filter(x=>x[1]);
 const rel=v21Related(keyword,cat,list.length?list:products.filter(p=>!p.hidden));
 const zeroRelated=products.filter(p=>!p.hidden).sort((a,b)=>{const aa=(a.tags||[]).filter(t=>keyword&&keyword.includes(t)).length,bb=(b.tags||[]).filter(t=>keyword&&keyword.includes(t)).length;return bb-aa||b.rating-a.rating}).slice(0,4);
 shell(`<div class="section-head"><div><h1>検索結果</h1><p>${list.length}件の作品</p></div><button class="btn" onclick="filterSheet()">⚙ 絞り込み</button></div><div class="toolbar"><div class="filter-chips">${chips.map(([k,v])=>`<button class="filter-chip-btn" onclick="removeSearchParam('${k}')">${esc(v)} <span class="x">×</span></button>`).join('')}${chips.length?`<button class="link-btn" onclick="go('search')">すべてクリア</button>`:''}</div><div class="btn-row"><select class="btn" onchange="searchSet('sort',this.value)"><option value="relevance" ${sort==='relevance'?'selected':''}>関連順</option><option value="popular" ${sort==='popular'?'selected':''}>人気順</option><option value="rating" ${sort==='rating'?'selected':''}>評価順</option><option value="new" ${sort==='new'?'selected':''}>新着順</option></select><div class="segmented" aria-label="表示列数"><button class="${cols===1?'active':''}" onclick="setCols(1)">1列</button><button class="${cols===2?'active':''}" onclick="setCols(2)">2列</button><button class="${cols===3?'active':''}" onclick="setCols(3)">3列</button></div></div></div>${shown.length?`<div id="searchGrid" class="product-grid" data-cols="${cols}" style="--cols:${cols}">${shown.map(productCard).join('')}</div><div class="toolbar"><div class="pager" style="flex:1"><button class="btn" ${page<=1?'disabled':''} onclick="searchPageMove(${page-1})">‹ 前へ</button><div class="center">${Array.from({length:pages},(_,i)=>i+1).slice(Math.max(0,page-2),Math.max(0,page-2)+5).map(n=>`<button class="page-dot ${n===page?'active':''}" onclick="searchPageMove(${n})">${n}</button>`).join('')}</div><button class="btn" ${page>=pages?'disabled':''} onclick="searchPageMove(${page+1})">次へ ›</button></div><label class="small">表示件数 <select class="btn" onchange="searchSet('pageSize',this.value);searchSet('page','1')"><option ${pageSize===6?'selected':''}>6</option><option ${pageSize===12?'selected':''}>12</option><option ${pageSize===24?'selected':''}>24</option></select></label></div>`:`<div class="empty s1-zero-search"><div class="emoji">🔎</div><h2>該当する作品がありません</h2><p class="muted">条件を緩めるか、欲しい作品をクリエイターへ需要として届けられます。</p><div class="btn-row" style="justify-content:center"><button class="btn primary" onclick="s1RelaxSearch()">条件を緩める</button><button class="btn" onclick="s1DemandModal('${esc(keyword)}','${esc(useCase)}')">リクエストする</button></div>${zeroRelated.length?`<div class="section"><h3>近い候補</h3><div class="h-scroll">${zeroRelated.map(productCard).join('')}</div></div>`:''}</div>`}<section class="section"><h2>関連する検索をもっと見る</h2><div class="btn-row">${rel.map(x=>`<button class="chip" onclick="go('search?q=${encodeURIComponent(x)}')">${esc(x)}</button>`).join('')}</div></section>`,{title:'検索結果',back:true,search:true,footer:true});
};

filterSheet=function(){
 const sp=s1SearchParams(),mn=Number(sp.get('min')||0),mx=Number(sp.get('max')||5000);
 showSheet(`<div class="section-head"><h2>絞り込み</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="search-filter-grid"><div class="field"><label>カテゴリ</label><select id="fCat"><option value="">指定なし</option>${CATEGORIES.map(c=>`<option ${sp.get('category')===c[0]?'selected':''}>${c[0]}</option>`).join('')}</select></div><div class="field"><label>用途</label><select id="fUse"><option value="">指定なし</option>${S1_USE_CASES.map(v=>`<option ${sp.get('use')===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>素材</label><select id="fMat"><option value="">指定なし</option>${['耐水PET','上質紙','透明PET','ホログラム'].map(v=>`<option ${sp.get('material')===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>形状</label><select id="fShape"><option value="">指定なし</option>${['ダイカット','円形','角丸','スクエア'].map(v=>`<option ${sp.get('shape')===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>サイズ</label><select id="fSize"><option value="">指定なし</option>${['30mm','50mm','70mm','100mm'].map(v=>`<option ${sp.get('size')===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="field"><label>価格帯</label><div class="range-values"><span id="fMinLabel">${yen(mn)}</span><span>〜</span><span id="fMaxLabel">${yen(mx)}${mx>=5000?'+':''}</span></div><input id="fMin" type="range" min="0" max="5000" step="100" value="${mn}" oninput="v21SyncRange()"><input id="fMax" type="range" min="0" max="5000" step="100" value="${mx}" oninput="v21SyncRange()"></div><label class="chip"><input id="fAi" type="checkbox" ${sp.get('excludeAi')==='1'?'checked':''}> AI生成作品を除外</label><div class="btn-row" style="margin-top:18px"><button class="btn" onclick="closeModal();go('search')">条件をクリア</button><button class="btn primary" onclick="applyV21Filters()">絞り込む</button></div>`);
};
applyV21Filters=function(){const sp=s1SearchParams();[['category',$('#fCat').value],['use',$('#fUse').value],['material',$('#fMat').value],['shape',$('#fShape').value],['size',$('#fSize').value],['min',$('#fMin').value],['max',$('#fMax').value]].forEach(([k,v])=>{if(v&&!(k==='min'&&v==='0')&&!(k==='max'&&v==='5000'))sp.set(k,v);else sp.delete(k)});if($('#fAi').checked)sp.set('excludeAi','1');else sp.delete('excludeAi');sp.set('page','1');closeModal();go(s1SearchUrl(sp))};

/* D-03: product series keeps favorites separate and adds collection navigation. */
function s1SeriesPage(id){
 const s=s1Scenario().series.find(x=>x.id===id);if(!s)return go('search');const list=products.filter(p=>p.seriesId===id&&!p.hidden);
 shell(`<div class="section-head"><div><span class="eyebrow">SERIES</span><h1>${esc(s.name)}</h1><p>${esc(s.description)}</p></div></div>${list.length?`<div class="product-grid" style="--cols:2">${list.map(productCard).join('')}</div>`:`<div class="empty"><h2>シリーズ作品を準備中です</h2></div>`}`,{title:'シリーズ',back:true,footer:true});
}
function s1EnhanceProductPage(id){
 const main=$('#main');if(!main||main.querySelector('.s1-product-extra'))return;const p=productBy(id);if(!p)return;const s=s1Scenario().series.find(x=>x.id===p.seriesId);
 const sec=document.createElement('section');sec.className='section card panel s1-product-extra';sec.innerHTML=`<div class="section-head"><div><h2>この作品について</h2><p>用途・シリーズ・権利情報</p></div></div><div class="btn-row">${(p.useCases||[]).map(x=>`<button class="chip" onclick="go('search?use=${encodeURIComponent(x)}')">${esc(x)}</button>`).join('')}</div>${s?`<div class="s1-inline-row"><div><b>シリーズ：${esc(s.name)}</b><div class="small muted">${esc(s.description)}</div></div><button class="btn" onclick="go('series/${s.id}')">シリーズを見る</button></div>`:''}<div class="s1-inline-row"><div><b>権利・AI利用</b><div class="small muted">権利申告 ${p.rights?.ownerDeclared?'済み':'未確認'} ・ AI利用 ${p.rights?.aiUsed?'あり':'なし'}</div></div><button class="link-btn" onclick="s1ReportOpen('product','${p.id}')">商品を通報</button></div>`;
 const footer=main.querySelector('.legal-footer');main.insertBefore(sec,footer||null);
}
function s1EnhanceCreatorPage(id){
 const main=$('#main');if(!main||main.querySelector('.s1-creator-actions'))return;const cover=main.querySelector('.shop-cover');if(!cover)return;
 const box=document.createElement('div');box.className='s1-creator-actions btn-row';box.innerHTML=`<button class="btn" onclick="go('custom-order/new/${id}')">オーダーメイド相談</button><button class="link-btn" onclick="s1ReportOpen('creator','${id}')">クリエイターを通報</button>`;cover.appendChild(box);
}

/* D-07: unmet demand request loop. */
function s1DemandModal(keyword='',useCase=''){
 if(!requireAuth(routePath(),'需要リクエストを登録するにはログインが必要です。'))return;
 showModal(`<div class="section-head"><h2>欲しいデザインをリクエスト</h2><button class="icon-btn" onclick="closeModal()">×</button></div><p class="muted">検索で見つからなかった希望を、個人情報を含めずクリエイターへ共有します。</p><div class="field"><label>希望デザイン</label><input id="drTitle" value="${esc(keyword)}" placeholder="例：防水の柴犬ステッカー"></div><div class="search-filter-grid"><div class="field"><label>サイズ</label><select id="drSize"><option>指定なし</option><option>30mm</option><option>50mm</option><option>70mm</option><option>100mm</option></select></div><div class="field"><label>素材</label><select id="drMat"><option>指定なし</option><option>耐水PET</option><option>上質紙</option><option>透明PET</option><option>ホログラム</option></select></div><div class="field"><label>用途</label><select id="drUse"><option>${useCase||'指定なし'}</option>${S1_USE_CASES.filter(x=>x!==useCase).map(x=>`<option>${x}</option>`).join('')}</select></div></div><div class="field"><label>参考情報（任意）</label><textarea id="drRef" placeholder="色、雰囲気、使う場所など"></textarea></div><button class="btn primary full" onclick="s1SubmitDemand()">リクエストを登録</button>`);
}
function s1SubmitDemand(){
 const title=$('#drTitle').value.trim();if(!title){toast('希望デザインを入力してください');return}
 const r={id:uid('demand'),requestId:uid('demand'),userId:currentUser().id,title,size:$('#drSize').value,material:$('#drMat').value,useCase:$('#drUse').value,reference:$('#drRef').value.trim(),status:'募集中',linkedProductId:null,date:now()};s1Scenario().demandRequests.unshift(r);s1Track('demand_request',{requestId:r.id,query:title});save();closeModal();toast('需要リクエストを登録しました');go('demand-requests');
}
function s1DemandRequestsPage(){
 const mine=s1Scenario().demandRequests.filter(x=>x.userId===currentUser()?.id);
 shell(`<div class="section-head"><div><h1>需要リクエスト</h1><p>欲しい作品の対応状況を確認できます。</p></div><button class="btn primary" onclick="s1DemandModal()">＋ リクエスト</button></div>${mine.length?mine.map(r=>`<article class="card panel" style="margin:9px 0"><div class="section-head"><div><span class="status ${s1StatusClass(r.status)}">${r.status}</span><h3>${esc(r.title)}</h3></div></div><div class="small muted">${esc(r.useCase)} ・ ${esc(r.material)} ・ ${esc(r.size)}</div>${r.linkedProductId?`<div class="notice" style="margin-top:10px">対応商品が公開されました。<button class="link-btn" onclick="go('product/${r.linkedProductId}')">商品を見る ›</button></div>`:''}</article>`).join(''):`<div class="empty"><div class="emoji">💡</div><h2>リクエストはまだありません</h2><p class="muted">検索で見つからない作品があれば需要として登録できます。</p><button class="btn primary" onclick="go('search')">商品を探す</button></div>`}`,{title:'需要リクエスト',back:true});
}
function s1CreatorDemandPage(){
 if(currentUser()?.role!=='creator')return go('home');const rows=s1Scenario().demandRequests.filter(x=>x.status!=='対応済み');
 shell(`<div class="section-head"><div><h1>需要一覧</h1><p>購入者から集まった未充足需要です。</p></div></div>${rows.length?rows.map(r=>`<article class="card panel" style="margin:9px 0"><span class="status">${r.status}</span><h3>${esc(r.title)}</h3><div class="small muted">用途 ${esc(r.useCase)} ・ 素材 ${esc(r.material)} ・ サイズ ${esc(r.size)}</div><p>${esc(r.reference||'参考情報なし')}</p><button class="btn primary" onclick="s1LinkDemandModal('${r.id}')">自分の商品で対応</button></article>`).join(''):`<div class="empty"><h2>未対応の需要はありません</h2></div>`}`,{title:'需要一覧',back:true,bell:true,cart:false});
}
function s1LinkDemandModal(id){const own=products.filter(p=>p.creatorId===currentUser()?.creatorId&&!p.hidden);showModal(`<div class="section-head"><h2>対応商品を紐付け</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>公開済み商品</label><select id="demandProduct">${own.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select></div><button class="btn primary" onclick="s1LinkDemand('${id}')">紐付けて通知</button>`)}
function s1LinkDemand(id){const r=s1Scenario().demandRequests.find(x=>x.id===id),pid=$('#demandProduct').value;if(!r||!pid)return;r.linkedProductId=pid;r.status='対応済み';r.respondedAt=now();s1Notify(r.userId,'demand',`リクエスト「${r.title}」に対応する商品が公開されました`,{requestId:id,productId:pid});save();closeModal();toast('購入者へ通知しました');render()}

/* D-08: custom order is a separate case until approval, then reuses the existing cart/checkout. */
function s1CustomOrdersPage(){
 const u=currentUser();if(!u)return go('login');let rows=s1Scenario().customOrders.filter(x=>x.userId===u.id);if(u.role==='creator')rows=s1Scenario().customOrders.filter(x=>x.creatorId===u.creatorId);
 shell(`<div class="section-head"><div><h1>オーダーメイド</h1><p>依頼から承認までを案件単位で管理します。</p></div></div>${rows.length?rows.map(x=>`<button class="card panel s1-case-row" onclick="go('custom-order/${x.id}')"><div><span class="status ${s1StatusClass(x.status)}">${x.status}</span><h3>${esc(x.title)}</h3><div class="small muted">${esc(creatorBy(x.creatorId).name)} ・ 希望 ${yen(x.budget)}</div></div><span>›</span></button>`).join(''):`<div class="empty"><div class="emoji">🎨</div><h2>オーダーメイド案件はありません</h2><button class="btn primary" onclick="go('creators')">クリエイターを探す</button></div>`}`,{title:'オーダーメイド',back:true,bell:true});
}
function s1CustomOrderNewPage(creatorId){
 const c=creatorBy(creatorId);if(!c)return go('creators');if(!requireAuth(`custom-order/new/${creatorId}`,'オーダーメイドを依頼するにはログインが必要です。'))return;
 shell(`<h1>${esc(c.name)}へ依頼</h1><div class="notice">通常商品とは別の案件として進行し、作品承認後の決済だけ既存Checkoutへ接続します。</div><div class="field"><label>依頼タイトル</label><input id="coTitle" placeholder="例：愛犬をモチーフにしたステッカー"></div><div class="field"><label>希望内容</label><textarea id="coBody"></textarea></div><div class="search-filter-grid"><div class="field"><label>希望用途</label><select id="coUse">${S1_USE_CASES.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>希望予算</label><select id="coBudget"><option value="500">〜500円</option><option value="1000">〜1,000円</option><option value="3000">〜3,000円</option><option value="5000">〜5,000円</option></select></div></div><button class="btn primary full" onclick="s1CreateCustomOrder('${creatorId}')">依頼する</button>`,{title:'オーダーメイド依頼',back:true,cart:false});
}
function s1CreateCustomOrder(creatorId){const title=$('#coTitle').value.trim(),body=$('#coBody').value.trim();if(!title||!body){toast('タイトルと希望内容を入力してください');return}const x={id:uid('customOrder'),caseId:uid('customOrder'),userId:currentUser().id,creatorId,title,body,useCase:$('#coUse').value,budget:Number($('#coBudget').value),status:'依頼',date:now(),updatedAt:now(),messages:[],draftNote:'',revisionCount:0,approvedProductId:null};s1Scenario().customOrders.unshift(x);s1NotifyCreator(creatorId,'order',`新しいオーダーメイド依頼「${title}」が届きました`,{customOrderId:x.id});save();go(`custom-order/${x.id}`)}
function s1CanAccessCustom(x){const u=currentUser();return !!u&&(u.role==='admin'||x.userId===u.id||(u.role==='creator'&&x.creatorId===u.creatorId))}
function s1CustomOrderDetailPage(id){
 const x=s1Scenario().customOrders.find(v=>v.id===id);if(!x||!s1CanAccessCustom(x))return go('custom-orders');const u=currentUser(),isCreator=u.role==='creator'&&u.creatorId===x.creatorId,isBuyer=x.userId===u.id;
 shell(`<div class="section-head"><div><span class="status ${s1StatusClass(x.status)}">${x.status}</span><h1>${esc(x.title)}</h1><p>${esc(creatorBy(x.creatorId).name)}とのオーダーメイド案件</p></div></div><div class="management-grid"><div><div class="card panel"><h2>依頼内容</h2><p>${esc(x.body)}</p><div class="detail-list"><div><span>用途</span><b>${esc(x.useCase)}</b></div><div><span>希望予算</span><b>${yen(x.budget)}</b></div><div><span>修正回数</span><b>${x.revisionCount}</b></div></div>${x.draftNote?`<div class="notice" style="margin-top:12px"><b>現在の初稿・提案</b><p>${esc(x.draftNote)}</p></div>`:''}<div class="btn-row" style="margin-top:14px">${isCreator&&x.status==='依頼'?`<button class="btn primary" onclick="s1CustomTransition('${id}','受注')">受注する</button>`:''}${isCreator&&['受注','制作中','修正'].includes(x.status)?`<button class="btn" onclick="s1CustomDraftModal('${id}')">初稿を提出</button>`:''}${isBuyer&&x.status==='初稿'?`<button class="btn" onclick="s1CustomTransition('${id}','修正')">修正を依頼</button><button class="btn primary" onclick="s1ApproveCustomOrder('${id}')">承認して購入へ</button>`:''}</div></div></div><div><div class="card panel"><h2>メッセージ</h2><div class="message-thread">${x.messages.length?x.messages.map(m=>`<div class="message-bubble ${m.userId===u.id?'mine':'admin'}"><b>${esc(m.sender)}</b><p>${esc(m.text)}</p><small>${s1Date(m.date)}</small></div>`).join(''):'<p class="muted">案件について確認したい内容を送れます。</p>'}</div><div class="field"><textarea id="coMsg" placeholder="メッセージ"></textarea></div><button class="btn primary full" onclick="s1CustomSendMessage('${id}')">送信</button></div></div></div>`,{title:'オーダーメイド詳細',back:true,bell:true,cart:false});
}
function s1CustomTransition(id,status){const x=s1Scenario().customOrders.find(v=>v.id===id);if(!x||!s1CanAccessCustom(x))return;const before=x.status;x.status=status;x.updatedAt=now();if(status==='受注')x.status='制作中';if(status==='修正')x.revisionCount++;s1Audit('オーダーメイド状態更新',before,x.status,'オーダーメイド');s1Notify(x.userId,'order',`オーダーメイド「${x.title}」：${x.status}`,{customOrderId:id});s1NotifyCreator(x.creatorId,'order',`オーダーメイド「${x.title}」：${x.status}`,{customOrderId:id});save();render()}
function s1CustomDraftModal(id){showModal(`<div class="section-head"><h2>初稿を提出</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>初稿・制作内容</label><textarea id="coDraft" placeholder="デザインの方向性、修正ポイントなど"></textarea></div><div class="field"><label>参考画像（任意）</label><input type="file" accept="image/*"></div><button class="btn primary" onclick="s1SubmitCustomDraft('${id}')">購入者へ提出</button>`)}
function s1SubmitCustomDraft(id){const x=s1Scenario().customOrders.find(v=>v.id===id),t=$('#coDraft').value.trim();if(!x||!t)return toast('初稿内容を入力してください');x.draftNote=t;x.status='初稿';x.updatedAt=now();s1Notify(x.userId,'order',`オーダーメイド「${x.title}」の初稿が届きました`,{customOrderId:id});save();closeModal();render()}
function s1CustomSendMessage(id){const x=s1Scenario().customOrders.find(v=>v.id===id),t=$('#coMsg').value.trim();if(!x||!t)return;x.messages.push({id:uid('message'),userId:currentUser().id,sender:currentUser().name,text:t,date:now()});const target=currentUser().id===x.userId?s1CreatorUser(x.creatorId)?.id:x.userId;if(target)s1Notify(target,'support',`オーダーメイド「${x.title}」に新しいメッセージ`,{customOrderId:id});save();render()}
function s1ApproveCustomOrder(id){
 const x=s1Scenario().customOrders.find(v=>v.id===id);if(!x||x.userId!==currentUser()?.id)return;let p=products.find(p=>p.privateCustomOrderId===id);
 if(!p){const src=products.find(p=>p.creatorId===x.creatorId)||products[0];p={...src,id:uid('customProduct'),name:`オーダーメイド：${x.title}`,description:x.body,digital:x.budget,physical:x.budget,price:x.budget,sales:0,favs:0,views:0,rating:0,updated:new Date().toISOString().slice(0,10),hidden:true,privateCustomOrderId:id,tags:[...(src.tags||[]),'オーダーメイド']};products.push(p)}
 x.status='承認';x.approvedProductId=p.id;x.updatedAt=now();save();addCart(p.id,'digital',{license:'personal'});
}

/* D-09 / D-10: support cases remain linked to the original order. */
const S1_SUPPORT_TYPES=['キャンセル','製造後キャンセル相談','発送遅延','未着','印刷不良','破損','誤配送','返金'];
function s1SupportNewPage(){
 const sp=new URLSearchParams(routePath().split('?')[1]||''),orderId=sp.get('order')||'',o=s1FindOrder(orderId)?.order;
 if(!currentUser())return go('login');
 shell(`<h1>注文について問い合わせ</h1><div class="notice">注文情報は自動で紐付きます。注文番号や商品情報の再入力は不要です。</div><div class="field"><label>対象注文</label><select id="supOrder">${userData().orders.map(x=>`<option value="${x.id}" ${x.id===orderId?'selected':''}>${x.id} ・ ${yen(x.total)}</option>`).join('')}</select></div><div class="field"><label>問い合わせ種類</label><select id="supType">${S1_SUPPORT_TYPES.map(x=>`<option>${x}</option>`).join('')}</select></div><div class="field"><label>状況</label><textarea id="supBody" placeholder="現在の状況を教えてください"></textarea></div><div class="field"><label>写真・資料（任意）</label><input id="supFile" type="file" accept="image/*,.pdf"></div><button class="btn primary full" onclick="s1CreateSupport()">問い合わせを開始</button>`,{title:'問い合わせ',back:true,cart:false});
}
function s1CreateSupport(){const orderId=$('#supOrder').value,type=$('#supType').value,body=$('#supBody').value.trim();if(!orderId||!body){toast('注文と状況を確認してください');return}const x={id:uid('support'),caseId:uid('support'),orderId,userId:currentUser().id,type,body,status:'受付',date:now(),updatedAt:now(),attachment:$('#supFile').files?.[0]?.name||null,messages:[],resolution:null,remanufacturingOrderId:null,refundAmount:0};s1Scenario().supportCases.unshift(x);s1Notify('user_admin_001','support',`新しい${type}問い合わせ：${orderId}`,{supportCaseId:x.id,orderId});save();go(`support/${x.id}`)}
function s1SupportListPage(){const u=currentUser();if(!u)return go('login');let rows=s1Scenario().supportCases.filter(x=>x.userId===u.id);if(u.role==='admin')rows=s1Scenario().supportCases;shell(`<div class="section-head"><div><h1>問い合わせ・トラブル</h1><p>注文に紐付くサポート案件です。</p></div></div>${rows.length?rows.map(x=>`<button class="card panel s1-case-row" onclick="go('support/${x.id}')"><div><span class="status ${s1StatusClass(x.status)}">${x.status}</span><h3>${esc(x.type)}</h3><div class="small muted">${esc(x.orderId)} ・ ${s1Date(x.date)}</div></div><span>›</span></button>`).join(''):`<div class="empty"><h2>問い合わせはありません</h2><button class="btn primary" onclick="go('orders')">注文履歴を見る</button></div>`}`,{title:'問い合わせ',back:true,bell:true});
}
function s1SupportDetailPage(id){const x=s1Scenario().supportCases.find(v=>v.id===id),u=currentUser();if(!x||!u||(u.role!=='admin'&&x.userId!==u.id))return go('support');const row=s1FindOrder(x.orderId),m=s1FindManufacturingByOrder(x.orderId);shell(`<div class="section-head"><div><span class="status ${s1StatusClass(x.status)}">${x.status}</span><h1>${esc(x.type)}</h1><p>${esc(x.orderId)}</p></div></div><div class="management-grid"><div><div class="card panel"><h2>申告内容</h2><p>${esc(x.body)}</p>${x.attachment?`<div class="status">添付：${esc(x.attachment)}</div>`:''}<div class="detail-list"><div><span>注文状態</span><b>${esc(row?.order.status||'—')}</b></div><div><span>製造状態</span><b>${esc(m?.status||'対象外')}</b></div><div><span>解決内容</span><b>${esc(x.resolution||'対応中')}</b></div></div>${u.role==='admin'?`<div class="btn-row" style="margin-top:14px"><button class="btn" onclick="s1SupportResolve('${id}','回答済み')">回答済みにする</button>${['印刷不良','破損','誤配送'].includes(x.type)?`<button class="btn primary" onclick="s1CreateRemanufacture('${id}')">再製造を手配</button>`:''}<button class="btn danger" onclick="s1SupportRefund('${id}')">返金処理</button></div>`:''}</div></div><div><div class="card panel"><h2>サポートメッセージ</h2><div class="message-thread">${x.messages.map(m=>`<div class="message-bubble ${m.userId===u.id?'mine':'admin'}"><b>${esc(m.sender)}</b><p>${esc(m.text)}</p><small>${s1Date(m.date)}</small></div>`).join('')}</div><div class="field"><textarea id="supMsg"></textarea></div><button class="btn primary full" onclick="s1SupportMessage('${id}')">送信</button></div></div></div>`,{title:'問い合わせ詳細',back:true,bell:true,cart:false});}
function s1SupportMessage(id){const x=s1Scenario().supportCases.find(v=>v.id===id),t=$('#supMsg').value.trim();if(!x||!t)return;x.messages.push({id:uid('message'),userId:currentUser().id,sender:currentUser().role==='admin'?'Sticker Market運営':currentUser().name,text:t,date:now()});x.updatedAt=now();const target=currentUser().role==='admin'?x.userId:'user_admin_001';s1Notify(target,'support',`問い合わせ ${x.orderId} に新しい返信があります`,{supportCaseId:id});save();render()}
function s1SupportResolve(id,status){const x=s1Scenario().supportCases.find(v=>v.id===id);if(!x)return;x.status=status;x.resolution='運営回答済み';x.updatedAt=now();s1Notify(x.userId,'support',`問い合わせ ${x.orderId} が更新されました：${status}`,{supportCaseId:id});save();render()}
function s1CreateRemanufacture(id){const x=s1Scenario().supportCases.find(v=>v.id===id),orig=s1FindManufacturingByOrder(x?.orderId);if(!x||!orig)return toast('製造注文が見つかりません');const m={...orig,id:uid('mfgOrder'),manufacturingOrderId:uid('mfgOrder'),status:'注文受付',createdAt:now(),updatedAt:now(),reproductionOf:orig.id,history:[{date:now(),status:'注文受付',note:`サポート案件 ${x.id} から再製造`}],inspection:{status:'未実施',note:''},tracking:{carrier:'',number:'',shippedAt:null,deliveredAt:null}};s1Scenario().manufacturingOrders.push(m);x.remanufacturingOrderId=m.id;x.status='再製造手配済み';x.resolution='元注文の売上を維持したまま再製造注文を作成';s1Notify(x.userId,'support',`注文 ${x.orderId} の再製造を手配しました`,{supportCaseId:id,manufacturingOrderId:m.id});save();render()}
function s1SupportRefund(id){const x=s1Scenario().supportCases.find(v=>v.id===id),row=s1FindOrder(x?.orderId);if(!x||!row)return;confirmAction('返金処理を記録しますか？','公開デモでは実送金せず、注文と報酬の調整状態を記録します。','返金を記録',()=>{x.status='返金済み';x.refundAmount=row.order.total;x.resolution=`${yen(row.order.total)}を返金記録`;row.order.status='返金済み';s1Scenario().payouts.filter(p=>p.orderId===row.order.id).forEach(p=>p.status='調整済み');s1Notify(x.userId,'support',`注文 ${x.orderId} の返金処理を記録しました`,{supportCaseId:id});save();render()})}

/* D-11: common report mechanism. */
function s1ReportOpen(type,targetId){if(!requireAuth(routePath(),'通報を送信するにはログインが必要です。'))return;const names={product:'商品',creator:'クリエイター',user:'ユーザー',review:'レビュー'};showModal(`<div class="section-head"><h2>${names[type]||type}を通報</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>理由</label><select id="repReason"><option>権利侵害の疑い</option><option>迷惑・スパム</option><option>不適切な内容</option><option>誤解を招く表示</option><option>その他</option></select></div><div class="field"><label>詳細（任意）</label><textarea id="repBody"></textarea></div><button class="btn danger" onclick="s1SubmitReport('${type}','${targetId}')">通報する</button>`)}
function s1SubmitReport(type,targetId){const r={id:uid('report'),reportId:uid('report'),reporterId:currentUser().id,targetType:type,targetId,reason:$('#repReason').value,body:$('#repBody').value.trim(),status:'確認待ち',date:now(),history:[]};s1Scenario().reports.unshift(r);s1Notify('user_admin_001','moderation',`${type}への新しい通報：${r.reason}`,{reportId:r.id});save();closeModal();toast('通報を受け付けました')}
