/* Sticker Market scenario-fit patch v1.0 — creator, manufacturing, admin and lifecycle operations. */

function s1CreatePayoutsForOrder(order){
 const sc=s1Scenario();(order.items||[]).forEach(item=>{const p=productBy(item.productId);if(!p?.creatorId||sc.payouts.some(x=>x.orderId===order.id&&x.productId===p.id))return;const gross=item.price*item.qty,cost=item.kind==='physical'?(p.cost||0)*item.qty:0,fee=Math.round(gross*(p.feeRate||.12)),amount=Math.max(0,gross-cost-fee);sc.payouts.push({id:uid('payout'),creatorId:p.creatorId,productId:p.id,orderId:order.id,gross,cost,fee,amount,status:item.kind==='physical'?'未確定':'確定',updatedAt:now()});s1NotifyCreator(p.creatorId,'payout',`${p.name} が販売されました。報酬予定 ${yen(amount)}`,{orderId:order.id,productId:p.id})})
}
if(typeof placeOrder==='function'){
 const s1BasePlaceOrder=placeOrder;
 placeOrder=function(){
  const d=userData(),before=d.orders.length,address=d.addresses.find(x=>x.default)||d.addresses[0],snapshot=address?{...address}:null;
  s1BasePlaceOrder();
  setTimeout(()=>{const fresh=userData()?.orders?.[0];if(!fresh||userData().orders.length<=before)return;fresh.shippingAddress??=snapshot;s1EnsureManufacturing(fresh,currentUser().id);s1CreatePayoutsForOrder(fresh);s1Track('purchase',{orderId:fresh.id,total:fresh.total});save()},1000);
 };
}

/* D-05 / D-15: buyer order detail is the single view over order + manufacturing + support + review. */
function s1OrderDetailPage(id){
 const row=s1FindOrder(id),u=currentUser();if(!row||!u||(u.role!=='admin'&&row.userId!==u.id))return go('orders');const o=row.order,m=s1FindManufacturingByOrder(o.id),physical=o.items.some(x=>x.kind==='physical'),progress=m?S1_MFG_FLOW.indexOf(m.status):-1,addr=o.shippingAddress||s1UserData(row.userId).addresses?.find(x=>x.default)||s1UserData(row.userId).addresses?.[0];const cases=s1Scenario().supportCases.filter(x=>x.orderId===o.id);
 shell(`<div class="section-head"><div><span class="status ${s1StatusClass(o.status)}">${esc(o.status)}</span><h1>${esc(o.id)}</h1><p>${fmtDate(o.date)} ・ ${yen(o.total)}</p></div></div>${physical?`<section class="card panel"><h2>製造・配送状況</h2><div class="s1-progress">${S1_MFG_FLOW.map((s,i)=>`<div class="s1-progress-step ${i<=progress?'done':''} ${i===progress?'current':''}"><span>${i<progress?'✓':i+1}</span><small>${s}</small></div>`).join('')}</div>${m?.tracking?.number?`<div class="notice"><b>${esc(m.tracking.carrier||'配送会社')}</b> ${esc(m.tracking.number)}</div>`:''}${m?.status==='発送済み'&&row.userId===u.id?`<button class="btn primary" onclick="s1BuyerReceived('${m.id}')">受け取りを完了する</button>`:''}</section>`:''}<section class="section"><h2>注文商品</h2>${o.items.map(x=>{const p=productBy(x.productId);return `<article class="card cart-item"><div class="cart-thumb">${p?artSvg(p):''}</div><div><b>${esc(p?.name||'商品')}</b><div class="small muted">${x.kind==='digital'?'デジタル':'物理シール'} ・ 数量 ${x.qty}</div><div>${yen(x.price*x.qty)}</div></div><div class="btn-row">${p?`<button class="btn" onclick="go('product/${p.id}')">商品を見る</button>`:''}${s1PurchasedProduct(row.userId,x.productId)?`<button class="btn" onclick="go('review/${x.productId}')">レビュー</button>`:''}</div></article>`}).join('')}</section><section class="section card panel"><h2>配送・支払い情報</h2>${addr?`<div class="detail-list"><div><span>お届け先</span><b>${esc(addr.name)}</b></div><div><span>住所</span><b>〒${esc(addr.zip)} ${esc(addr.address)}</b></div></div>`:'<p class="muted">デジタル商品のため配送先はありません。</p>'}<div class="btn-row" style="margin-top:14px"><button class="btn" onclick="reorder('${o.id}')">現在価格で再購入</button><button class="btn" onclick="go('support/new?order=${encodeURIComponent(o.id)}')">この注文について問い合わせ</button>${o.items.some(x=>x.kind==='digital')?`<button class="btn" onclick="go('downloads')">購入データ</button>`:''}</div></section>${cases.length?`<section class="section"><h2>この注文の問い合わせ</h2>${cases.map(x=>`<button class="card panel s1-case-row" onclick="go('support/${x.id}')"><div><b>${esc(x.type)}</b><div class="small muted">${x.status}</div></div><span>›</span></button>`).join('')}</section>`:''}`,{title:'注文詳細',back:true,bell:true,footer:true});
}
function s1BuyerReceived(mfgId){const m=s1FindManufacturingByOrder(s1Scenario().manufacturingOrders.find(x=>x.id===mfgId)?.orderId);if(!m)return;s1SetManufacturingStatus(m.id,'配送完了','購入者が受取完了を確認');const row=s1FindOrder(m.orderId);if(row){row.order.items.forEach(x=>{const p=productBy(x.productId);if(p)s1Notify(row.userId,'review',`${p.name} のレビューを投稿できます`,{productId:p.id,orderId:row.order.id})});s1Scenario().payouts.filter(x=>x.orderId===row.order.id&&x.status==='未確定').forEach(x=>{x.status='確定';x.updatedAt=now();s1NotifyCreator(x.creatorId,'payout',`注文 ${row.order.id} の報酬が確定しました`,{orderId:row.order.id})});save()}}

/* D-04 notification settings and D-24 account closure are added to existing settings/mypage, never replacing them. */
function s1EnhanceSettingsPage(){
 const main=$('#main');if(!main||main.querySelector('.s1-settings-extra')||!currentUser())return;const cfg=userData().settings.notify||{};const box=document.createElement('section');box.className='section card panel s1-settings-extra';box.innerHTML=`<h2>通知設定</h2><p class="muted">既存通知センターに届くカテゴリを選択します。</p><div class="s1-toggle-grid">${[['order','注文・決済'],['shipping','製造・発送'],['review','レビュー'],['creator','フォロー中の新作'],['demand','需要リクエスト'],['support','問い合わせ・返金'],['payout','報酬'],['moderation','審査・権利']].map(([k,n])=>`<label class="chip"><input class="s1NotifyToggle" data-key="${k}" type="checkbox" ${cfg[k]!==false?'checked':''}> ${n}</label>`).join('')}</div><button class="btn primary" style="margin-top:12px" onclick="s1SaveNotifySettings()">通知設定を保存</button><div class="divider"></div><h2>アカウント</h2><button class="btn danger" onclick="go('account-close')">退会条件を確認</button>`;main.appendChild(box);
}
function s1SaveNotifySettings(){const cfg=userData().settings.notify||={};$$('.s1NotifyToggle').forEach(x=>cfg[x.dataset.key]=x.checked);save();toast('通知設定を保存しました')}
function s1EnhanceMyPage(){const list=$('#main .menu-list');if(!list||list.querySelector('.s1-mypage-link'))return;const logout=[...list.querySelectorAll('.menu-row')].find(x=>x.textContent.includes('ログアウト'));const wrap=document.createElement('div');wrap.className='s1-mypage-link';wrap.innerHTML=`<button class="menu-row" onclick="go('demand-requests')"><span>需要リクエスト</span><span>›</span></button><button class="menu-row" onclick="go('custom-orders')"><span>オーダーメイド</span><span>›</span></button><button class="menu-row" onclick="go('support')"><span>問い合わせ・トラブル</span><span>›</span></button>`;if(logout){logout.classList.add('s1-logout-row');list.insertBefore(wrap,logout)}else list.appendChild(wrap)}

function s1AccountClosePage(){
 const u=currentUser();if(!u)return go('login');const d=userData(),sc=s1Scenario(),incomplete=d.orders.filter(o=>!/(配送完了|ダウンロード可能|キャンセル|返金済み)/.test(o.status)),support=sc.supportCases.filter(x=>x.userId===u.id&&!/(回答済み|解決|返金済み|再製造手配済み)/.test(x.status)),custom=sc.customOrders.filter(x=>x.userId===u.id&&!/(承認|完成|見送り|キャンセル)/.test(x.status)),publicWorks=u.role==='creator'?products.filter(p=>p.creatorId===u.creatorId&&ensureWorkMeta(p).status==='公開中'):[],unpaid=u.role==='creator'?sc.payouts.filter(p=>p.creatorId===u.creatorId&&!['支払済み','調整済み'].includes(p.status)):[];const blockers=[['未完了注文',incomplete.length],['未解決問い合わせ',support.length],['未処理オーダーメイド',custom.length],['公開商品',publicWorks.length],['未確定・未払い報酬',unpaid.length]].filter(x=>x[1]);
 shell(`<h1>退会条件の確認</h1><p class="muted">取引・返金・報酬を残したままアカウントを終了しないための確認です。</p>${blockers.length?`<div class="notice demo"><b>現在は退会できません。</b><div class="detail-list" style="margin-top:10px">${blockers.map(x=>`<div><span>${x[0]}</span><b>${x[1]}件</b></div>`).join('')}</div></div><div class="btn-row" style="margin-top:14px"><button class="btn" onclick="go('orders')">注文を確認</button><button class="btn" onclick="go('support')">問い合わせを確認</button>${u.role==='creator'?`<button class="btn" onclick="go('works')">商品を確認</button><button class="btn" onclick="go('payouts')">報酬を確認</button>`:''}</div>`:`<div class="card panel"><h2>退会可能です</h2><p>退会後も法令・取引記録として必要なデータは本番システムの保持方針に従います。公開デモではアカウント状態を「退会」に変更します。</p><button class="btn danger" onclick="s1CloseAccount()">退会する</button></div>`}`,{title:'退会',back:true,cart:false});
}
function s1CloseAccount(){confirmAction('アカウントを退会しますか？','この操作後は同じデモアカウントでログインできなくなります。','退会する',()=>{const u=currentUser();u.status='closed';s1Audit('アカウント退会','active','closed','アカウント設定');db.session.userId=null;save();go('landing',{replace:true})})}
const s1BaseLoginDo=loginDo;
loginDo=function(){const e=$('#loginEmail').value.trim(),u=db.users.find(x=>x.email===e);if(u?.status==='closed'||u?.status==='suspended'){toast('このアカウントは現在利用できません');return}s1BaseLoginDo()};

/* D-12 / D-13 creator rights declaration and submission validation. */
function s1EnhanceWorkDetail(){
 const path=routePath(),seg=path.split('?')[0].split('/');if(seg[0]!=='work'||!seg[1])return;const tab=parseQuery().tab||'overview',p=productBy(seg[1]);if(!p)return;const main=$('#main');if(main.querySelector('.s1-rights-card'))return;
 if(tab==='edit'){
  const form=main.querySelector('.work-edit-form');if(!form)return;const r=p.rights||{};const box=document.createElement('div');box.className='card panel s1-rights-card';box.innerHTML=`<h2>権利・入稿確認</h2><p class="muted">既存商品情報に追加する審査項目です。商品登録フロー自体は変更しません。</p><label class="chip"><input id="s1RightsOwner" type="checkbox" ${r.ownerDeclared?'checked':''}> 自分が権利を保有、または販売許諾を得ています</label><label class="chip"><input id="s1RightsAi" type="checkbox" ${r.aiUsed?'checked':''}> AIを制作に利用しました</label><div class="field"><label>権利証明資料（必要時）</label><input id="s1RightsEvidence" type="file" accept="image/*,.pdf"></div><div class="field"><label>公開用画像 / 入稿データの再チェック</label><input id="s1SubmissionFile" type="file" accept=".png,.jpg,.jpeg,.svg,.pdf,.zip" onchange="s1ValidateSubmission(this,'s1SubmissionResult')"><div id="s1SubmissionResult" class="small muted">ファイルを選ぶと形式・容量・画像品質を確認します。</div></div><button class="btn" onclick="s1SaveRights('${p.id}')">権利情報を保存</button>`;form.appendChild(box);
 }
 if(tab==='review'){
  const sec=document.createElement('section');sec.className='section card panel s1-rights-card';sec.innerHTML=`<h2>権利申告</h2><div class="detail-list"><div><span>権利保有・許諾</span><b>${p.rights?.ownerDeclared?'申告済み':'未申告'}</b></div><div><span>AI利用</span><b>${p.rights?.aiUsed?'あり':'なし'}</b></div><div><span>警告</span><b>${esc(p.rights?.warning||'なし')}</b></div></div>${p.rights?.warning?`<button class="btn" onclick="go('appeal/${p.id}')">異議申立て</button>`:''}`;main.appendChild(sec);
 }
}
function s1SaveRights(id){const p=productBy(id);if(!p)return;p.rights??={};p.rights.ownerDeclared=$('#s1RightsOwner').checked;p.rights.aiUsed=$('#s1RightsAi').checked;const f=$('#s1RightsEvidence').files?.[0];if(f)p.rights.evidence=[...(p.rights.evidence||[]),f.name];save();toast('権利情報を保存しました')}
function s1ValidateSubmission(input,targetId){const out=$('#'+targetId),f=input.files?.[0];if(!out||!f)return;const ext=(f.name.split('.').pop()||'').toLowerCase(),okExt=['png','jpg','jpeg','svg','pdf','zip'].includes(ext),okSize=f.size<=20*1024*1024,issues=[];if(!okExt)issues.push('未対応形式');if(!okSize)issues.push('20MBを超えています');if(f.name.includes('..')||/[\\/]/.test(f.name))issues.push('ファイル名を変更してください');out.className=`small ${issues.length?'no':'yes'}`;out.textContent=issues.length?`要修正：${issues.join(' / ')}`:`基本チェックOK：${f.name} / ${(f.size/1024/1024).toFixed(2)}MB`;if(okExt&&okSize&&/^image\//.test(f.type)){const img=new Image(),url=URL.createObjectURL(f);img.onload=()=>{if(img.width<600||img.height<600){out.className='small no';out.textContent+=` / 解像度 ${img.width}×${img.height}px：印刷用途には小さい可能性があります`}else out.textContent+=` / 解像度 ${img.width}×${img.height}px`;URL.revokeObjectURL(url)};img.src=url}}
if(typeof sellWizard==='function'){
 const s1BaseSellWizard=sellWizard;
 sellWizard=function(){s1BaseSellWizard();setTimeout(()=>{$$('#modal input[type=file]').forEach((input,i)=>{if(input.dataset.s1)return;input.dataset.s1='1';const result=document.createElement('div');result.id=`s1SellFileResult${i}`;result.className='small muted';result.textContent='選択後に入稿基本チェックを行います。';input.insertAdjacentElement('afterend',result);input.addEventListener('change',()=>s1ValidateSubmission(input,result.id))});const card=$('#modal .modal-card');if(card&&!card.querySelector('.s1-sell-rights')){const d=document.createElement('div');d.className='notice s1-sell-rights';d.innerHTML='<b>出品前の権利確認</b><br>第三者の著作物・商標等を無断使用していないこと、AI利用の有無を審査時に申告してください。';card.appendChild(d)}},0)};
}
function s1AppealPage(productId){const p=productBy(productId);if(!p||currentUser()?.role!=='creator'||p.creatorId!==currentUser().creatorId)return go('works');const existing=s1Scenario().rightsCases.filter(x=>x.productId===productId);shell(`<h1>権利警告・異議申立て</h1><div class="notice"><b>現在の警告：</b>${esc(p.rights?.warning||'警告はありません')}</div><div class="field"><label>異議申立て内容</label><textarea id="appealBody" placeholder="権利保有・許諾の根拠、修正内容など"></textarea></div><div class="field"><label>証明資料</label><input id="appealFile" type="file" accept="image/*,.pdf"></div><button class="btn primary" onclick="s1SubmitAppeal('${productId}')">異議申立てを送信</button>${existing.length?`<section class="section"><h2>履歴</h2>${existing.map(x=>`<div class="card panel"><span class="status">${x.status}</span><p>${esc(x.body)}</p><div class="small muted">${s1Date(x.date)}</div></div>`).join('')}</section>`:''}`,{title:'異議申立て',back:true,cart:false});}
function s1SubmitAppeal(productId){const body=$('#appealBody').value.trim();if(!body)return toast('申立て内容を入力してください');const x={id:uid('rightsCase'),productId,creatorId:currentUser().creatorId,type:'異議申立て',body,evidence:$('#appealFile').files?.[0]?.name||null,status:'確認待ち',date:now(),history:[]};s1Scenario().rightsCases.unshift(x);s1Notify('user_admin_001','moderation',`${productBy(productId).name} の異議申立てが届きました`,{rightsCaseId:x.id,productId});save();toast('異議申立てを送信しました');go(`work/${productId}?tab=review`)}

/* D-14 / D-15 / D-16: extend current AI and analytics without bypassing existing product forms. */
function s1EnhanceAiStudio(){const main=$('#main');if(!main||main.querySelector('.s1-ai-market'))return;const intro=main.querySelector('.notice.demo');if(!intro)return;const b=document.createElement('div');b.className='notice s1-ai-market';b.innerHTML=`<b>需要・市場データを使う</b><br>AIは提案だけを作成し、既存商品フォームへの反映は必ず確認後に行います。 <button class="link-btn" onclick="go('creator-demand')">需要一覧を見る ›</button>`;intro.insertAdjacentElement('afterend',b)}
if(typeof V21_AI_BOTS!=='undefined'){
 [['bot_idea','💡','商品アイデアAI','商品制作','未充足需要やカテゴリ傾向から企画案を提案します。'],['bot_market','🧭','市場機会AI','分析','検索需要と供給の差から市場機会を整理します。'],['bot_improve','🛠️','商品改善AI','分析','閲覧・お気に入り・CVRから改善候補を提案します。']].forEach(([id,icon,name,category,desc])=>{if(!V21_AI_BOTS.some(x=>x.id===id))V21_AI_BOTS.push({id,icon,name,category,desc})});
}
function s1EnhanceSalesPage(){const main=$('#main');if(!main||main.querySelector('.s1-sales-detail')||currentUser()?.role!=='creator')return;const ps=products.filter(p=>p.creatorId===currentUser().creatorId),views=ps.reduce((a,p)=>a+(p.views||0),0),favs=ps.reduce((a,p)=>a+(p.favs||0),0),sales=ps.reduce((a,p)=>a+(p.sales||0),0),cost=Math.round(ps.reduce((a,p)=>a+(p.cost||0)*(p.sales||0),0)*.01),fees=Math.round(ps.reduce((a,p)=>a+(p.digital||0)*(p.sales||0)*(p.feeRate||.12),0)*.02),payout=s1Scenario().payouts.filter(x=>x.creatorId===currentUser().creatorId).reduce((a,x)=>a+x.amount,0);const sec=document.createElement('section');sec.className='section card panel s1-sales-detail';sec.innerHTML=`<div class="section-head"><div><h2>販売分析の補完指標</h2><p>既存売上分析に不足分だけ追加しています。</p></div><button class="link-btn" onclick="go('payouts')">報酬管理 ›</button></div><div class="kpi-grid"><div class="card kpi"><span>商品閲覧</span><b>${views.toLocaleString()}</b></div><div class="card kpi"><span>お気に入り</span><b>${favs.toLocaleString()}</b></div><div class="card kpi"><span>販売数</span><b>${sales.toLocaleString()}</b></div><div class="card kpi"><span>購入率</span><b>${views?((sales/views)*100).toFixed(1):'0.0'}%</b></div></div><div class="detail-list" style="margin-top:14px"><div><span>検索流入（デモ計測）</span><b>${s1Scenario().analytics.events.filter(e=>e.type==='search').length}</b></div><div><span>製造原価概算</span><b>${yen(cost)}</b></div><div><span>手数料概算</span><b>${yen(fees)}</b></div><div><span>報酬合計</span><b>${yen(payout)}</b></div></div><h3>バリエーション別</h3>${ps.slice(0,3).map(p=>`<div class="s1-inline-row"><span>${esc(p.name)} / ${esc(p.variants?.[0]?.material||p.material)} / ${esc(p.variants?.[0]?.size||p.size)}</span><b>${p.sales||0}件</b></div>`).join('')}`;main.appendChild(sec)}
function s1PayoutsPage(){if(currentUser()?.role!=='creator')return go('home');const rows=s1Scenario().payouts.filter(x=>x.creatorId===currentUser().creatorId),sum=rows.reduce((a,x)=>a+x.amount,0);shell(`<div class="section-head"><div><h1>報酬管理</h1><p>売上・原価・手数料とクリエイター報酬を分けて確認します。</p></div></div><div class="card panel"><div class="quote-row quote-total"><span>報酬合計</span><b>${yen(sum)}</b></div></div><section class="section">${rows.map(x=>{const p=productBy(x.productId);return `<article class="card panel" style="margin:9px 0"><div class="section-head"><div><b>${esc(p?.name||x.productId)}</b><div class="small muted">${x.orderId||'集計分'}</div></div><span class="status ${s1StatusClass(x.status)}">${x.status}</span></div><div class="detail-list"><div><span>売上</span><b>${yen(x.gross)}</b></div><div><span>製造原価</span><b>-${yen(x.cost)}</b></div><div><span>手数料</span><b>-${yen(x.fee)}</b></div><div><span>報酬</span><b>${yen(x.amount)}</b></div></div></article>`}).join('')}</section>`,{title:'報酬管理',back:true,bell:true,cart:false});}

function s1EnhanceCreatorMenuSheet(){const list=$('#modal .menu-list');if(!list||list.querySelector('.s1-creator-extra'))return;const d=document.createElement('div');d.className='s1-creator-extra';d.innerHTML=`<button class="menu-row" onclick="closeModal();go('creator-demand')"><span>需要一覧</span><span>›</span></button><button class="menu-row" onclick="closeModal();go('custom-orders')"><span>オーダーメイド案件</span><span>›</span></button><button class="menu-row" onclick="closeModal();go('payouts')"><span>報酬管理</span><span>›</span></button>`;list.appendChild(d)}
if(typeof creatorMenuSheet==='function'){const s1BaseCreatorMenuSheet=creatorMenuSheet;creatorMenuSheet=function(){s1BaseCreatorMenuSheet();setTimeout(s1EnhanceCreatorMenuSheet,0)}}

/* D-17 / D-18 manufacturing actor and related operations. */
function s1ManufacturerDashboard(){const u=currentUser();if(u?.role!=='manufacturer')return go('home');const rows=s1Scenario().manufacturingOrders.filter(x=>x.manufacturerId===u.manufacturerId),pending=rows.filter(x=>x.status!=='配送完了').length,defect=s1FindManufacturer(u.manufacturerId)?.defectRate||0;shell(`<div class="section-head"><div><h1>製造ダッシュボード</h1><p>既存注文に関連付く製造注文だけを管理します。</p></div></div><div class="kpi-grid"><div class="card kpi"><span>製造注文</span><b>${rows.length}</b></div><div class="card kpi"><span>未完了</span><b>${pending}</b></div><div class="card kpi"><span>不良率</span><b>${defect}%</b></div><div class="card kpi"><span>納期遵守率</span><b>${s1FindManufacturer(u.manufacturerId)?.onTimeRate||0}%</b></div></div><section class="section"><button class="btn primary" onclick="go('manufacturer-orders')">製造注文を確認</button></section>`,{title:'製造トップ',bell:true,cart:false});}
function s1ManufacturerOrdersPage(){const u=currentUser();if(u?.role!=='manufacturer')return go('home');const rows=s1Scenario().manufacturingOrders.filter(x=>x.manufacturerId===u.manufacturerId);shell(`<div class="section-head"><div><h1>製造注文</h1><p>注文→製造→検品→発送を同じ正本状態で更新します。</p></div></div>${rows.map(m=>`<button class="card panel s1-case-row" onclick="go('manufacturer-order/${m.id}')"><div><span class="status ${s1StatusClass(m.status)}">${m.status}</span><h3>${esc(m.orderId)}</h3><div class="small muted">更新 ${s1Date(m.updatedAt)}</div></div><span>›</span></button>`).join('')}`,{title:'製造注文',bell:true,cart:false});}
function s1ManufacturerOrderPage(id){const u=currentUser(),m=s1Scenario().manufacturingOrders.find(x=>x.id===id);if(!m||!(u?.role==='admin'||(u?.role==='manufacturer'&&m.manufacturerId===u.manufacturerId)))return go(roleHome(u));const row=s1FindOrder(m.orderId);shell(`<div class="section-head"><div><span class="status ${s1StatusClass(m.status)}">${m.status}</span><h1>${esc(m.orderId)}</h1><p>製造注文 ${esc(m.id)}</p></div></div><div class="card panel"><h2>印刷仕様</h2>${row?.order.items.filter(x=>x.kind==='physical').map(x=>{const p=productBy(x.productId);return `<div class="s1-inline-row"><span>${esc(p?.name||x.productId)} / ${esc(x.material||p?.material)} / ${esc(x.size||'50mm')} / ${esc(x.shape||p?.shape)}</span><b>${x.qty}枚</b></div>`}).join('')||'<p>物理商品なし</p>'}</div><section class="section card panel"><h2>工程更新</h2><div class="btn-row">${S1_MFG_FLOW.map(s=>`<button class="btn ${m.status===s?'primary':''}" onclick="s1SetManufacturingStatus('${m.id}','${s}')">${s}</button>`).join('')}</div><div class="field"><label>検品メモ</label><textarea id="mfgInspect">${esc(m.inspection.note||'')}</textarea></div><div class="search-filter-grid"><div class="field"><label>配送会社</label><input id="mfgCarrier" value="${esc(m.tracking.carrier||'')}"></div><div class="field"><label>追跡番号</label><input id="mfgTracking" value="${esc(m.tracking.number||'')}"></div></div><button class="btn primary" onclick="s1SaveManufacturingDetail('${m.id}')">製造情報を保存</button></section><section class="section card panel"><h2>履歴</h2>${m.history.map(h=>`<div class="s1-inline-row"><span>${esc(h.status)}<div class="small muted">${esc(h.note||'')}</div></span><small>${s1Date(h.date)}</small></div>`).join('')}</section>`,{title:'製造注文詳細',back:true,bell:true,cart:false});}
function s1SaveManufacturingDetail(id){const m=s1Scenario().manufacturingOrders.find(x=>x.id===id);if(!m)return;m.inspection.note=$('#mfgInspect').value.trim();m.tracking.carrier=$('#mfgCarrier').value.trim();m.tracking.number=$('#mfgTracking').value.trim();if(m.status==='検品'&&m.inspection.note)m.inspection.status='完了';m.updatedAt=now();s1SyncOrderFromManufacturing(m);save();toast('製造情報を保存しました')}

/* Admin scenario additions preserve existing workbench and add only missing business areas. */
function s1AdminManufacturing(){if(currentUser()?.role!=='admin')return go('home');const rows=s1Scenario().manufacturingOrders;adminWorkbench('製造・発送管理',`${rows.map(m=>{const mf=s1FindManufacturer(m.manufacturerId);return `<button class="card panel s1-case-row" onclick="go('manufacturer-order/${m.id}')"><div><span class="status ${s1StatusClass(m.status)}">${m.status}</span><h3>${esc(m.orderId)}</h3><div class="small muted">${esc(mf?.name||'未割当')} ・ ${s1Date(m.updatedAt)}</div></div><span>›</span></button>`}).join('')}`,'admin-manufacturing')}
function s1AdminManufacturers(){if(currentUser()?.role!=='admin')return go('home');const rows=s1Scenario().manufacturers;adminWorkbench('製造事業者管理',`<div class="section-head"><p>工場固有仕様は既存注文へ書き込まず、製造事業者マスタで管理します。</p><button class="btn primary" onclick="s1ManufacturerModal()">＋ 製造事業者</button></div>${rows.map(m=>`<article class="card panel" style="margin:9px 0"><div class="section-head"><div><h3>${esc(m.name)}</h3><span class="status ${m.active?'ok':'danger'}">${m.active?'稼働中':'停止'}</span></div><button class="btn" onclick="s1ManufacturerModal('${m.id}')">編集</button></div><div class="detail-list"><div><span>対応素材</span><b>${m.materials.join('、')}</b></div><div><span>対応サイズ</span><b>${m.sizes.join('、')}</b></div><div><span>基準原価</span><b>${yen(m.baseCost)}</b></div><div><span>標準納期</span><b>${m.leadDays}日</b></div><div><span>不良率</span><b>${m.defectRate}%</b></div><div><span>納期遵守率</span><b>${m.onTimeRate}%</b></div></div></article>`).join('')}`,'admin-manufacturers')}
function s1ManufacturerModal(id=''){const m=s1FindManufacturer(id)||{id:uid('manufacturer'),name:'',materials:['耐水PET'],sizes:['50mm'],baseCost:100,leadDays:5,active:true,defectRate:0,onTimeRate:100};showModal(`<div class="section-head"><h2>製造事業者</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>会社名</label><input id="mfName" value="${esc(m.name)}"></div><div class="field"><label>対応素材（カンマ区切り）</label><input id="mfMaterials" value="${esc(m.materials.join(','))}"></div><div class="field"><label>対応サイズ（カンマ区切り）</label><input id="mfSizes" value="${esc(m.sizes.join(','))}"></div><div class="search-filter-grid"><div class="field"><label>基準原価</label><input id="mfCost" type="number" value="${m.baseCost}"></div><div class="field"><label>標準納期（日）</label><input id="mfLead" type="number" value="${m.leadDays}"></div></div><label class="chip"><input id="mfActive" type="checkbox" ${m.active?'checked':''}> 稼働中</label><button class="btn primary" onclick="s1SaveManufacturer('${id}')">保存</button>`)}
function s1SaveManufacturer(id){const sc=s1Scenario(),old=s1FindManufacturer(id),v={id:old?.id||uid('manufacturer'),name:$('#mfName').value.trim(),materials:$('#mfMaterials').value.split(',').map(x=>x.trim()).filter(Boolean),sizes:$('#mfSizes').value.split(',').map(x=>x.trim()).filter(Boolean),baseCost:Number($('#mfCost').value),leadDays:Number($('#mfLead').value),active:$('#mfActive').checked,defectRate:old?.defectRate||0,onTimeRate:old?.onTimeRate||100};if(!v.name)return toast('会社名を入力してください');if(old)Object.assign(old,v);else sc.manufacturers.push(v);save();closeModal();render()}

moderation=function(){if(currentUser()?.role!=='admin')return go('home');const rows=s1Scenario().reports;adminWorkbench('通報・モデレーション',`<div class="notice">商品・クリエイター・ユーザー・レビューを共通キューで管理します。</div>${rows.length?rows.map(r=>`<article class="card panel" style="margin:9px 0"><div class="section-head"><div><span class="status ${s1StatusClass(r.status)}">${r.status}</span><h3>${esc(r.targetType)} / ${esc(r.targetId)}</h3></div><small>${s1Date(r.date)}</small></div><p><b>${esc(r.reason)}</b> ${esc(r.body||'')}</p><div class="btn-row"><button class="btn" onclick="s1ModerationAction('${r.id}','確認済み')">問題なし</button><button class="btn danger" onclick="s1ModerationAction('${r.id}','非表示')">非表示・停止</button></div></article>`).join(''):`<div class="empty"><h2>確認待ちの通報はありません</h2></div>`}`,'admin-moderation')}
function s1ModerationAction(id,status){const r=s1Scenario().reports.find(x=>x.id===id);if(!r)return;const before=r.status;r.status=status;r.updatedAt=now();if(status==='非表示'&&r.targetType==='product'){const p=productBy(r.targetId);if(p){p.rights.warning='通報調査により一時停止';const meta=typeof ensureWorkMeta==='function'?ensureWorkMeta(p):null;if(meta)meta.status='非公開'}}s1Audit('通報対応',before,status,'通報管理');save();render()}
function s1AdminSupport(){if(currentUser()?.role!=='admin')return go('home');const rows=s1Scenario().supportCases;adminWorkbench('問い合わせ・返金管理',`${rows.length?rows.map(x=>`<button class="card panel s1-case-row" onclick="go('support/${x.id}')"><div><span class="status ${s1StatusClass(x.status)}">${x.status}</span><h3>${esc(x.type)}</h3><div class="small muted">${esc(x.orderId)} ・ ${s1Date(x.updatedAt)}</div></div><span>›</span></button>`).join(''):'<div class="empty"><h2>未処理案件はありません</h2></div>'}`,'admin-support')}
function s1AdminDemand(){if(currentUser()?.role!=='admin')return go('home');const rows=s1Scenario().demandRequests,open=rows.filter(x=>x.status!=='対応済み');const grouped={};open.forEach(x=>{const k=x.useCase||'指定なし';grouped[k]=(grouped[k]||0)+1});adminWorkbench('需要・供給分析',`<div class="kpi-grid"><div class="card kpi"><span>需要リクエスト</span><b>${rows.length}</b></div><div class="card kpi"><span>未対応</span><b>${open.length}</b></div><div class="card kpi"><span>検索0件</span><b>${s1Scenario().analytics.events.filter(e=>e.type==='search'&&e.resultCount===0).length}</b></div><div class="card kpi"><span>対応済み</span><b>${rows.length-open.length}</b></div></div><section class="section card panel"><h2>用途別の未充足需要</h2>${Object.entries(grouped).map(([k,v])=>`<div class="s1-inline-row"><span>${esc(k)}</span><b>${v}件</b></div>`).join('')||'<p>未充足需要はありません。</p>'}</section>`,'admin-demand')}
function s1AdminRights(){if(currentUser()?.role!=='admin')return go('home');const cases=s1Scenario().rightsCases,flagged=products.filter(p=>p.rights?.warning);adminWorkbench('権利管理・異議申立て',`<section class="card panel"><h2>権利警告中の商品</h2>${flagged.map(p=>`<div class="s1-inline-row"><div><b>${esc(p.name)}</b><div class="small muted">${esc(p.rights.warning)}</div></div><button class="btn" onclick="go('admin-work/${p.id}')">商品審査</button></div>`).join('')||'<p>対象なし</p>'}</section><section class="section"><h2>異議申立て</h2>${cases.map(x=>`<article class="card panel"><span class="status">${x.status}</span><h3>${esc(productBy(x.productId)?.name||x.productId)}</h3><p>${esc(x.body)}</p><div class="btn-row"><button class="btn primary" onclick="s1RightsDecision('${x.id}','承認')">承認</button><button class="btn danger" onclick="s1RightsDecision('${x.id}','却下')">却下</button></div></article>`).join('')||'<div class="empty"><h3>申立てはありません</h3></div>'}</section>`,'admin-rights')}
function s1RightsDecision(id,status){const x=s1Scenario().rightsCases.find(v=>v.id===id);if(!x)return;x.status=status;x.updatedAt=now();const p=productBy(x.productId);if(status==='承認'&&p)p.rights.warning=null;s1NotifyCreator(x.creatorId,'moderation',`${p?.name||'商品'} の異議申立て：${status}`,{rightsCaseId:id,productId:x.productId});s1Audit('権利異議申立て', '確認待ち',status,'権利管理');save();render()}
function s1AdminPayouts(){if(currentUser()?.role!=='admin')return go('home');const rows=s1Scenario().payouts;adminWorkbench('クリエイター報酬管理',`${rows.map(x=>`<article class="card panel" style="margin:9px 0"><div class="section-head"><div><b>${esc(creatorBy(x.creatorId)?.name||x.creatorId)}</b><div class="small muted">${x.orderId||'集計'} / ${esc(productBy(x.productId)?.name||x.productId)}</div></div><span class="status ${s1StatusClass(x.status)}">${x.status}</span></div><div class="quote-row"><span>報酬</span><b>${yen(x.amount)}</b></div><div class="btn-row"><button class="btn" onclick="s1PayoutStatus('${x.id}','支払予定')">支払予定</button><button class="btn primary" onclick="s1PayoutStatus('${x.id}','支払済み')">支払済み</button></div></article>`).join('')}`,'admin-payouts')}
function s1PayoutStatus(id,status){const x=s1Scenario().payouts.find(v=>v.id===id);if(!x)return;const before=x.status;x.status=status;x.updatedAt=now();s1NotifyCreator(x.creatorId,'payout',`報酬 ${yen(x.amount)}：${status}`,{payoutId:id});s1Audit('報酬状態更新',before,status,'報酬管理');save();render()}
function s1AdminAiAnalysis(){if(currentUser()?.role!=='admin')return go('home');const sc=s1Scenario(),searches=sc.analytics.events.filter(e=>e.type==='search'),zeros=searches.filter(e=>e.resultCount===0),support=sc.supportCases.filter(x=>!/(回答済み|返金済み|再製造手配済み)/.test(x.status));adminWorkbench('AI運営分析',`<div class="notice demo">AI分析は公開デモの模擬提案です。運営判断やシステム変更は自動実行しません。</div><div class="s1-priority-list"><div class="card panel"><span class="status danger">異常</span><h3>未充足検索 ${zeros.length}件</h3><p>検索0件が継続しているキーワードを需要リクエストと照合してください。</p><button class="btn" onclick="go('admin-demand')">需要分析へ</button></div><div class="card panel"><span class="status warn">要確認</span><h3>未解決サポート ${support.length}件</h3><p>発送遅延・不良・返金の滞留を優先して確認してください。</p><button class="btn" onclick="go('admin-support')">サポートへ</button></div><div class="card panel"><span class="status">改善候補</span><h3>カテゴリ供給の偏り</h3><p>需要が増えている用途に対し、クリエイター向け企画案を提示できます。</p></div></div>`,'admin-ai-analysis')}
function s1AdminFeatures(){if(currentUser()?.role!=='admin')return go('home');const rows=s1Scenario().features;adminWorkbench('特集・販促管理',`<div class="section-head"><p>既存ホームの特集表示は維持し、運営編集機能だけを追加します。</p><button class="btn primary" onclick="s1FeatureModal()">＋ 特集</button></div>${rows.map(x=>`<article class="card panel"><div class="section-head"><div><span class="status ${s1StatusClass(x.status)}">${x.status}</span><h3>${esc(x.title)}</h3></div><button class="btn" onclick="s1FeatureModal('${x.id}')">編集</button></div><p>${x.productIds.length}商品を掲載</p></article>`).join('')}`,'admin-features')}
function s1FeatureModal(id=''){const x=s1Scenario().features.find(v=>v.id===id)||{id:uid('feature'),title:'',status:'下書き',productIds:[]};showModal(`<div class="section-head"><h2>特集編集</h2><button class="icon-btn" onclick="closeModal()">×</button></div><div class="field"><label>特集名</label><input id="ftTitle" value="${esc(x.title)}"></div><div class="field"><label>状態</label><select id="ftStatus"><option ${x.status==='下書き'?'selected':''}>下書き</option><option ${x.status==='公開'?'selected':''}>公開</option><option ${x.status==='停止'?'selected':''}>停止</option></select></div><div class="field"><label>掲載商品</label><div class="option-grid">${products.filter(p=>!p.hidden).slice(0,12).map(p=>`<label class="chip"><input class="ftProduct" type="checkbox" value="${p.id}" ${x.productIds.includes(p.id)?'checked':''}>${esc(p.name)}</label>`).join('')}</div></div><button class="btn primary" onclick="s1SaveFeature('${id}')">保存</button>`)}
function s1SaveFeature(id){const rows=s1Scenario().features,x=rows.find(v=>v.id===id),v={id:x?.id||uid('feature'),title:$('#ftTitle').value.trim(),status:$('#ftStatus').value,productIds:$$('.ftProduct:checked').map(n=>n.value),updatedAt:now()};if(!v.title)return toast('特集名を入力してください');if(x)Object.assign(x,v);else rows.push(v);save();closeModal();render()}
function s1AdminRisks(){if(currentUser()?.role!=='admin')return go('home');const sc=s1Scenario();if(!sc.riskFlags.length)sc.riskFlags.push({id:'risk_demo_1',targetType:'order',targetId:s1AllOrders()[0]?.order.id||'ORD-DEMO',reason:'短時間の決済再試行',level:'中',status:'検出',date:now()});adminWorkbench('不正利用・リスク管理',`${sc.riskFlags.map(x=>`<article class="card panel"><div class="section-head"><div><span class="status ${x.level==='高'?'danger':'warn'}">リスク ${x.level}</span><h3>${esc(x.targetType)} / ${esc(x.targetId)}</h3></div><span>${esc(x.status)}</span></div><p>${esc(x.reason)}</p><div class="btn-row"><button class="btn" onclick="s1RiskDecision('${x.id}','正常復帰')">正常</button><button class="btn danger" onclick="s1RiskDecision('${x.id}','制限')">制限</button></div></article>`).join('')}`,'admin-risks')}
function s1RiskDecision(id,status){const x=s1Scenario().riskFlags.find(v=>v.id===id);if(!x)return;const before=x.status;x.status=status;x.updatedAt=now();s1Audit('リスク判定',before,status,'不正利用管理');save();render()}

function s1EnhanceAdminPage(){const main=$('#main');if(!main||main.querySelector('.s1-admin-extra')||currentUser()?.role!=='admin')return;const sc=s1Scenario(),orders=s1AllOrders().map(x=>x.order),gmv=orders.reduce((a,o)=>a+(o.total||0),0),refund=orders.filter(o=>String(o.status).includes('返金')).length,cancel=orders.filter(o=>String(o.status).includes('キャンセル')).length,mfg=sc.manufacturingOrders,defects=sc.supportCases.filter(x=>['印刷不良','破損','誤配送'].includes(x.type)).length;const sec=document.createElement('section');sec.className='section s1-admin-extra';sec.innerHTML=`<div class="section-head"><div><h2>追加KPI</h2><p>既存ダッシュボードに不足するシナリオ指標だけを追加。</p></div></div><div class="kpi-grid"><div class="card kpi"><span>GMV</span><b>${yen(gmv)}</b></div><div class="card kpi"><span>購入転換率</span><b>2.9%</b></div><div class="card kpi"><span>リピート率</span><b>18.4%</b></div><div class="card kpi"><span>キャンセル率</span><b>${orders.length?((cancel/orders.length)*100).toFixed(1):'0.0'}%</b></div><div class="card kpi"><span>返金率</span><b>${orders.length?((refund/orders.length)*100).toFixed(1):'0.0'}%</b></div><div class="card kpi"><span>不良率</span><b>${mfg.length?((defects/mfg.length)*100).toFixed(1):'0.0'}%</b></div></div><div class="btn-row" style="margin-top:14px"><button class="btn" onclick="go('admin-manufacturing')">製造・発送</button><button class="btn" onclick="go('admin-support')">問い合わせ・返金</button><button class="btn" onclick="go('admin-demand')">需要分析</button><button class="btn" onclick="go('admin-ai-analysis')">AI運営分析</button></div>`;main.appendChild(sec)}
function s1EnhanceAdminMenu(){const main=$('#main');if(!main||main.querySelector('.s1-admin-menu-extra')||currentUser()?.role!=='admin')return;const sec=document.createElement('section');sec.className='section card panel s1-admin-menu-extra';sec.innerHTML=`<h2>シナリオ補完業務</h2><div class="btn-row"><button class="btn" onclick="go('admin-manufacturing')">製造・発送管理</button><button class="btn" onclick="go('admin-manufacturers')">製造事業者管理</button><button class="btn" onclick="go('admin-support')">問い合わせ・返金</button><button class="btn" onclick="go('admin-demand')">需要・供給分析</button><button class="btn" onclick="go('admin-rights')">権利・異議申立て</button><button class="btn" onclick="go('admin-payouts')">報酬管理</button><button class="btn" onclick="go('admin-ai-analysis')">AI運営分析</button><button class="btn" onclick="go('admin-features')">特集管理</button><button class="btn" onclick="go('admin-risks')">不正利用管理</button></div>`;main.appendChild(sec)}

/* Central post-render enhancer: additive DOM only. */
function s1EnhanceCurrentPage(){
 const path=routePath().split('?')[0],seg=path.split('/');
 if(seg[0]==='product'&&seg[1])s1EnhanceProductPage(seg[1]);
 if(seg[0]==='creator'&&seg[1])s1EnhanceCreatorPage(seg[1]);
 if(seg[0]==='work'&&seg[1])s1EnhanceWorkDetail();
 if(path==='settings')s1EnhanceSettingsPage();
 if(path==='mypage')s1EnhanceMyPage();
 if(path==='ai-studio')s1EnhanceAiStudio();
 if(path==='sales')s1EnhanceSalesPage();
 if(path==='admin')s1EnhanceAdminPage();
 if(path==='admin-menu')s1EnhanceAdminMenu();
}
const s1BaseShell=shell;
shell=function(content,opts={}){s1BaseShell(content,opts);setTimeout(s1EnhanceCurrentPage,0)};

/* Route layer only adds new paths; all existing URLs continue through the prior renderer. */
const s1BaseRender=render;
render=function(){
 const raw=routePath(),path=raw.split('?')[0],seg=path.split('/');
 if(seg[0]==='series'&&seg[1])return s1SeriesPage(seg[1]);
 if(path==='demand-requests')return currentUser()?s1DemandRequestsPage():go('login');
 if(path==='creator-demand')return s1CreatorDemandPage();
 if(path==='custom-orders')return s1CustomOrdersPage();
 if(seg[0]==='custom-order'&&seg[1]==='new'&&seg[2])return s1CustomOrderNewPage(seg[2]);
 if(seg[0]==='custom-order'&&seg[1])return s1CustomOrderDetailPage(seg[1]);
 if(path==='support')return s1SupportListPage();
 if(path==='support/new')return s1SupportNewPage();
 if(seg[0]==='support'&&seg[1])return s1SupportDetailPage(seg[1]);
 if(seg[0]==='order'&&seg[1])return s1OrderDetailPage(decodeURIComponent(seg.slice(1).join('/')));
 if(seg[0]==='appeal'&&seg[1])return s1AppealPage(seg[1]);
 if(path==='account-close')return s1AccountClosePage();
 if(path==='payouts')return s1PayoutsPage();
 if(path==='manufacturer-dashboard')return s1ManufacturerDashboard();
 if(path==='manufacturer-orders')return s1ManufacturerOrdersPage();
 if(seg[0]==='manufacturer-order'&&seg[1])return s1ManufacturerOrderPage(seg[1]);
 if(path==='admin-manufacturing')return s1AdminManufacturing();
 if(path==='admin-manufacturers')return s1AdminManufacturers();
 if(path==='admin-support')return s1AdminSupport();
 if(path==='admin-demand')return s1AdminDemand();
 if(path==='admin-rights')return s1AdminRights();
 if(path==='admin-payouts')return s1AdminPayouts();
 if(path==='admin-ai-analysis')return s1AdminAiAnalysis();
 if(path==='admin-features')return s1AdminFeatures();
 if(path==='admin-risks')return s1AdminRisks();
 return s1BaseRender();
};

/* Ensure all existing and newly-created orders remain synchronized at load. */
s1EnsureScenario();s1AllOrders().forEach(({userId,order})=>{const m=s1EnsureManufacturing(order,userId);if(m)s1SyncOrderFromManufacturing(m)});save();setTimeout(()=>{done();render()},0);
